### ISSUE TITLE
AI appears to always target fighters

### ISSUE THREAD

**Issue by ondrej008** [BeeStation/NSV13#1001]
## Round ID:

doesn't really matter but 1154 and then some previous

## Testmerges:

none

## Reproduction:

have AI syndie engaging mainship

have a player fighter fly by

AI syndie stops shooting mainship and shoots the fighter,
it appears that some AI ship types also disengage the mainship completely and start chasing the fighter

**Comment by Karmic-Skink** [comment]
You'll need to include which syndie ships you are talking about because we do have prioritizing behaviour.

**Comment by ondrej008** [comment]
> 
> 
> You'll need to include which syndie ships you are talking about because we do have prioritizing behaviour.

For shooting fighters instead of main ships, it feels like *every* single syndie ship does that
For disengaging the main ship and starting to chase fighters, I'll look into that
