### ISSUE TITLE
Dials being piles of junk

### ISSUE THREAD

**Issue by theboy6545** [BeeStation/NSV13#1005]
## Round ID:

 Try start the FTL, you have about a 50/50 chance of it starting or just looking like it started and it not doing anything.

**Comment by ondrej008** [comment]
Dials are pieces of junk, but they're not that hard to use,
the way I do it is I click the dial directly once, then click away somewhere on the same window, this seems to work 100% for me.
It would honestly be best if we got some kind of ON/OFF switch or something as a TGUI control.

**Comment by MacBlaze1** [comment]
This is not even a suggestion, but a complaint, and such it should be closed

**Comment by Corsaka** [comment]
Duplicate of #942
