### ISSUE TITLE
Flight Leader can be part of an squad

### ISSUE THREAD

**Issue by Googles-Hands** [BeeStation/NSV13#1016]
An oversight in configs seems to have made the Flight Lead able to be part of an squad, when he really, like normal Pilots/ATC/Munition Techs shouldnt be able to be in one as he already has an primary general quarters duty.

Issue reported from  Round ID: 1233 (NSV 13 | Official | MRP | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1536

**Comment by Bamhalazam** [comment]
Done, could ping some github maintainer to add a resolved tag.

**Comment by MacBlaze1** [comment]
This was supposed to be resolved exactly 1 month ago, but was not.

**Comment by Jalleo** [comment]
Make a new bug report if this is still a issue. Trying to clean out ones we believe are fixed.
