### ISSUE TITLE
Parralax code confliction.

### ISSUE THREAD

**Issue by Jalleo** [BeeStation/NSV13#1039]
## Reproduction:
Move between areas (Likely space and station areas.

Notice that it resets to generic space every so often causing lag to the client and potentially the server by having this occur across multiple clients.

Likely a conflict between base and NSV specific code due to how parallax is coded.

**Comment by Kmc2000** [comment]
Fixed with the PVP branch, this was due to throttling the parallax update rate to mitigate lag rather than actually fixing the lag.
