### ISSUE TITLE
Chameleon kit don't work correctly for NSV-specific role clothing such as Fighter Pilot, Munitions Tech etc.

### ISSUE THREAD

**Issue by pupertino** [BeeStation/NSV13#1043]
## Reproduction:

1. Obtain chameleon clothes, such as by spawning a chameleon kit
2. Wear the chameleon clothes
3. Use the icon at top left to choose a disguise such as fighter pilot
4. Note missing sprites on the character

**Comment by francinum** [comment]
Likely due to their use of alternate icon plates.

**Comment by Bamhalazam** [comment]
yeah so the NSV specific clothing is under a file within the game data so im not even sure how to fix that? chameleon 2.0?
