### ISSUE TITLE
Tycoon airlocks aren't linked properly

### ISSUE THREAD

**Issue by Koekiegast** [BeeStation/NSV13#1048]
## Round ID:
1373

## Testmerges:
#1013: 'missions 2' by TMTIME at commit cab2f7007e
#1035: 'Makes pilots not get deleted (Should fix uncloneability)' by Bokkiewokkie at commit 3b61a55f93
#999: 'The Rook, A mining ship for the SGV Atherwhisp' by theboy6545 at commit d628321873
#1027: 'Armor increasing fighter max hp is no longer completely useless' by DeltaFire15 at commit fad56ea2e5
#1040: 'New map: NSV Eclipse' by Ansome101 at commit 996b6085ef
#1046: 'should fix LOOC' by Corsaka at commit 2a746688cb

## Reproduction:
Play on the tycoon, find that the scrubber mix is spreading around the ship and mainly around deck 2.
It's either problems with the way the airlocks and maybe their double vents are set up, but also just seperate vents are set up or just something with gas leaking out trough scrubbers because completely untouched rooms also had plasma in them even though distro was completely clean.
Anyhow the airlocks on the tycoon need to be double checked, atleast the big one in the engineering hangar and the one on the second deck because their scrubber and distro vents aren't set properly.

**Comment by Bokkiewokkie** [comment]
Pretty sure this issue was fixed already and never linked in the PR
