### ISSUE TITLE
[Aegis] Arrival shuttle door

### ISSUE THREAD

**Issue by Tuulipommi** [BeeStation/NSV13#105]
So... I opened the aft door on the arrival shuttle and it just leads straight into the wall. If you could map that out, that would be fine and dandy.

**Comment by francinum** [comment]
The arrivals shuttle is generic and needs to be specifically remapped for this station.

**Comment by Jalleo** [comment]
We need to make the Aegis arrival shuttle a special escape pod style. I can do that quickly.

**Comment by Jalleo** [comment]
I have created a ship for it but I have no understanding of the shuttle code itself and so cannot finalize it.
