### ISSUE TITLE
You can put torps in crates

### ISSUE THREAD

**Issue by Bokkiewokkie** [BeeStation/NSV13#1087]
## Reproduction:

1. make torp
2. open crate
3. drag torp sprote on crate
4. torp in crate
5. repeat
6. sell munitions trolley

**Comment by kiVts** [comment]
c-c-c-close it

**Comment by Bokkiewokkie** [comment]
> c-c-c-close it

@SharkeeByond maybe actually put "fixes" in front of the mention of the issue next time so it auto-closes it
