### ISSUE TITLE
Some missions don't work

### ISSUE THREAD

**Issue by DeltaFire15** [BeeStation/NSV13#1100]
Reporting client version: 513.1536

## Testmerges:
#1095: 'Fixes some camera errors, fighter docking slightly cleaned up' by Kmc2000 at commit f1f2e66649
#1083: 'Brazil 2.0' by francinum at commit 72e0e1d336
#1052: 'New Map: NSV Gladius' by Cenrus at commit 977c977bce

## Reproduction
Part 1:
Accept cargo mission. Put cargo into cargo torp, launch it at target station. Watch torp pass through the station as the mission stays at 0 / x delivered cargo.

Part 2:
Get Rubicon scouting mission. Travel to Rubicon through the hell that is sector 3, arrive at Rubicon, watch the mission stay uncompleted.

**Comment by Jalleo** [comment]
@Kmc2000

**Comment by Bokkiewokkie** [comment]
Closing this as the missions system has been refactored.
