### ISSUE TITLE
Jeppson munitions issues

### ISSUE THREAD

**Issue by Omppusolttu** [BeeStation/NSV13#1168]
A few issues I've encountered in the Jeppison's munitions as a MAA
1. No 50. Cal guns and the flaks in their place don't work at all
2. No NAV and instead a Railgun that doesn't get used either
3. No project space, which is an issue for a medpop ship
Now I understand that the CIC being in the way causes issues, but frankly when two of the new guns that are supposed to help the ship not die don't exist on a ship? That causes issues

**Comment by theboy6545** [comment]
Use the correct issue template for this so that it gets marked as a map issue, so I can see it by just sorting by map issue
