### ISSUE TITLE
Ship handling 

### ISSUE THREAD

**Issue by Omppusolttu** [BeeStation/NSV13#1178]
Many people have complained about how ships handle, and there seems to be a minor communication error between the playerbase.and staff

Players don't want faster ships, as timers breaking is a very good reason to avoid it. What players do want is faster acceleration to max speed and a swifter turnspeed

It feels like the turn distance has remained the same while speed is lower, while it could be said that this makes you think about your actions more in combat. 

In practice due to unpredictability to combat it just feels like you can't respond to changing circumstances.

**Comment by covertcorvid** [comment]
Closing as this isn't truly a bug, but appreciate the feedback.
