### ISSUE TITLE
Can't use durasteel floor tiles to make plating

### ISSUE THREAD

**Issue by Bokkiewokkie** [BeeStation/NSV13#1190]
So over here on NSV we got these wacky material, one of which is called durasteel.
Durasteel is funky as it's used for our special funny walls and floors, giving the entire ship a neat unique style.
Unfortunately, while it is possible to make floor tiles with this durasteel (to make the cool floors of course) which make up most of the floors on our ships, it's not possible to use these tiles on lattices to make plating!

I'll probably fix this later but if anyone wants to do it first, feel free to.
Just think it's a good idea to have durasteel (mono, tech, whatever they're called) tiles be able to be used as plating on lattices.

**Comment by Jalleo** [comment]
It honestly would be easier to override metal at this point and call it Durasteel. That isnt so easy though.......

**Comment by Bokkiewokkie** [comment]
If only it was 😔 Also I'm stupid cause this is already possible, just not for nanoweave carpet
