### ISSUE TITLE
Bridge Staff need a new headset type.

### ISSUE THREAD

**Issue by ta3370** [BeeStation/NSV13#1210]

**Comment by James-source** [comment]
Lets actually do it right then;
BOs get Command,Common and Muni(maybe).
XO gets captains headset but renamed.

**Comment by AU518987077** [comment]
I can agree to this. and I will.

**Comment by Corsaka** [comment]
I'm pretty sure I made a PR to fix this and it got shot down because nobody cared.

OR because I proceeded to spend three days replacing all instances of HoP with XO and then got told I should've done it with children of the items.

**Comment by AU518987077** [comment]
~~I will continue to break into the captain's office and steal their bowman's headset if there is no captain to ask politely for it until this important change is made.~~ I would appreciate this being reconsidered as the correct course of action. not just for the XO but for BO's as well please and thank you.

**Comment by Karmic-Skink** [comment]
The chain of command is supposed to be BS -> MAA/Captain/XO via Command or same room chat -> MT via Munitions.

Having Command radio is enough.
