### ISSUE TITLE
Janicart cannot go up stairs

### ISSUE THREAD

**Issue by theboy6545** [BeeStation/NSV13#1213]
Issue reported from  Round ID: 1758 (NSV 13 | Official | MRP | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1536

Whenever you try go up a set of stairs, your janiecart will go up the stairs, but you will be stuck, however when you move back down the stairs, you will automatically become remounted.

**Comment by AU518987077** [comment]
confirmed this behavior. as undesirable in both directions.
[dreamseeker.exe 2021.02.15 - 19.30.45.17.zip Video](https://github.com/BeeStation/NSV13/files/5985786/dreamseeker.exe.2021.02.15.-.19.30.45.17.zip)

cannot ride janicart up stairs as described, but can drag or push 
also cannot ride down the stairs.

in my opinion, maybe you should not be able to ride it up/down stairs but should be able to drag or push it up/down stairs, the elevator exists and should be used for the janicart and the mop cart in my opinion.
