### ISSUE TITLE
Frontal phasers hit the shields from the inside (Aetherwhisp)

### ISSUE THREAD

**Issue by Grabovvski** [BeeStation/NSV13#1233]
## Round ID:
1830

## Testmerges:
#1227 
#1232 

## Reproduction:
Go on Aetherwhisp
Raise shields
Fire frontal phasers
The phasers will hit the shield, the shield will light up, like when it is damaged

**Comment by Bokkiewokkie** [comment]
I'm pretty sure this has been fixed
