### ISSUE TITLE
Pirate controlled systems have a flat line on the map instead of a circle

### ISSUE THREAD

**Issue by Bokkiewokkie** [BeeStation/NSV13#1235]
## Description:

Whenever a pirate fleet captures a system it has no color marker dot on the starmap, it's just a red outline that looks like it's fallen into the 1st dimension.

## Reproduction:

Look at the FTL console once a pirate fleet has captured a system, see this:
![image](https://user-images.githubusercontent.com/43698041/107282941-fe8aa780-6a5b-11eb-942f-d17e8e4fdc0e.png)

**Comment by jzburda** [comment]
The wikia is not well documented. I was thinking this was due to an inability outright to jump to the sector.
