### ISSUE TITLE
Muscled Vein Surgery - Wrong Result

### ISSUE THREAD

**Issue by BetaCentari** [BeeStation/NSV13#1238]
When performing the muscled vein experimental surgery, it does not produce the intended result of replacing the function and need of the heart. It instead finishes with the Vein Threading experimental surgery result along with the text "You weave _Patient's_ veins into a resistant mesh!" I've tried to remove the heart of a patient after performing the Muscled Veins surgery and the patient shortly dies without being able to pump blood without a heart.

To reproduce, perform the Muscled Vein surgery and the Vein Threading finish text and result will affect the patient.

**Comment by AU518987077** [comment]
Can confirm.
performed the Vein Muscled Membrane Surgery and made a Vein thread mesh instead.
[Github issue NSV 1238 Muscled Vein Surgery - Wrong Result.zip](https://github.com/BeeStation/NSV13/files/5979946/Github.issue.NSV.1238.Muscled.Vein.Surgery.-.Wrong.Result.zip)
![image](https://user-images.githubusercontent.com/24924661/107915156-2c229580-6f21-11eb-9c5e-715fc829d512.png)
