### ISSUE TITLE
New plumbing component (refilling tanks to slow)

### ISSUE THREAD

**Issue by b1ades** [BeeStation/NSV13#1247]
A simple idea for a new plumbing component a port similar to a tank port that enable you to attach carts/fuel tanks to pumping networks for draining or filling (it would have 2 ports one for adding chemicals one for removing) just like you would do with canisters on a atmos line wrenching the cart ontop of the port.

Why this is good for the game:
Let Muni make a oil cart for gun maintenance. 
Gives pilots something to do in there downtime making a fuel factory.
Would also work for any other jobs that want certain chemicals a lot like the botanist, clown oh god not the lube cart, medical imagine a mutadone cart after Radiation events or just general other shenanigans. PLUS this could all be setup by chemist and shipped to people giving them more to do in a round .

**Comment by Jalleo** [comment]
This is a idea not a bug. https://forums-nsv.beestation13.com/c/byond-machine-go-brrr/ideasguy/13 Place it in here.
