### ISSUE TITLE
Ghost can not use ladders

### ISSUE THREAD

**Issue by Vasily2013** [BeeStation/NSV13#1251]
## Round ID:

1857

## Testmerges:

#1241: 'Skynet : The Tweakening' by DeltaFire15 at commit 34f5206f53
#1237: 'Armour Plate Regeneration' by Karmic-Skink at commit 38d00210b6
#1249: '[Map] NSV Atlas, somehow smaller than eclipse! :tm:' by Kmc2000 at commit 577200661c

## Reproduction:

Be ghost, use ladder.

**Comment by SerynEngi** [comment]
This seems like the sort of low hanging fruit I can use to learn. I'll get on it.

**Comment by Karmic-Skink** [comment]
Use verb.

**Comment by SerynEngi** [comment]
This bug has been solved, Recommend closing.
