### ISSUE TITLE
Space Dragons cannot go down decks. (Without elevators)

### ISSUE THREAD

**Issue by QAI-07** [BeeStation/NSV13#1263]
## Testmerges:
#1254 
#1249 
#1259 

## Reproduction:

Be a space dragon. (Ghostrole Antagonist)
Go to the upper deck of any ship. (The round this was discovered in was on the NSV Atlas.)
Dragons destroy ladders by trying to use them, and cannot go down Z-Levels via stairs due to having wings. They cannot also fall down open space tiles.

**Comment by Corsaka** [comment]
I actually really like the idea that dragons are forced to go into the elevator and listen to elevator music before they can continue their mass destruction.

**Comment by covertcorvid** [comment]
Mobs that defy gravity can use the "Move Upwards" and "Move Down" verbs in the IC tab. If this turns out to not be the case, please let me know.
