### ISSUE TITLE
Muni Techfab Research Broke [Atlas]

### ISSUE THREAD

**Issue by johnsonfreeman** [BeeStation/NSV13#1269]
## Round ID:  N/A

 Testmerges:  N/A

## Reproduction:
Researching muni tech (macro-ballistics, etc...) doesn't give all the tech it's supposed to/missing tech after researching it.

![](https://cdn.discordapp.com/attachments/533051649401421827/817597258949459998/buce.PNG)

![](https://cdn.discordapp.com/attachments/533051649401421827/817597267506626640/niceo.PNG)

**Comment by Bokkiewokkie** [comment]
yeah that's cause they're designs for the circuit imprinter and not the protolathe, but I'll switch em around
