### ISSUE TITLE
Gauss Cannons Firing Without Input From Operator

### ISSUE THREAD

**Issue by SerynEngi** [BeeStation/NSV13#1274]
## Reproduction:
The gauss guns appear to occasionally fire without input from the operator, as soon as the rounds are chambered, they do appear to fire in the direction that the cursor is pointed.

Noted factors- 
-This does not appear to happen frequently for the first couple magazines of the weapon, though it does seem to happen.
-This has occurred with the 50 cals firing, and with the 50 cals not firing.
-It fires the entire magazine as soon as it is chambered, ignoring the status of the safeties (even if the safeties are engaged, it will fire).

As a side note, and request pertaining to them- request that the magazine size of the gauss guns be increased. There is space on the loading racks for more, and the weapons feel highly underwhelming when compared to the 50 cal turrets.

**Comment by jzburda** [comment]
Will confirm this is an issue

**Comment by SerynEngi** [comment]
Also, I am unsure if its related, but I've seen other weapons autofire on occasion without input.
