### ISSUE TITLE
Fighter engine bug

### ISSUE THREAD

**Issue by b1ades** [BeeStation/NSV13#1276]
## Reproduction: 
Part 1: The FL fighter has the same thrust as the basic fighter at round start you can test this by changing the fuel tank and plates over but leaving the engine in this is fixed by simply changing the engine or dropping it out of the fighter and putting it back in.

Part 2: Performing this action on the basic fighter also increase there speed however this doesn't seem to happen with player built fighters as they all ready move at this faster speed.

Part 3: When the canopy breaks this seems to update the fighters speed increasing the speed the same way dropping the engine out did. This happened when I was playing as the syndicate fighter though so needs more testing to see if I can reproduce. (not sure if breaking the armour would also cause this but droping/changing the armour and cockpit them dosent as NT at least)

Another good example is that with t2 plates and a brrt the FL fighter is unable to fly forwards just like a t1 engine removing the secondary weapon enables the fighter to fly forwards at very slow speed.

good luck figuring this stuff out and I will update if I can find out anything more.

**Comment by covertcorvid** [comment]
Flight Lead role is no longer in the game
