### ISSUE TITLE
The Haunted Magic Eightball is broken

### ISSUE THREAD

**Issue by thudner24** [BeeStation/NSV13#1288]
## Round ID:
Don't remember, confirmed the bug on a private server.

## Reproduction:

A traitor buys the 8ball, asks the question and shakes it.

At this point ghosts should simply be able to open the menu and vote for an answer.
However, you can only press the buttons if you are orbiting the player asking the question, and the interface is broken in a way that makes only the first three options visible, all of which are variations of "yes".

Edit: I probably should've checked that first, there is already an issue for this on beestation

**Comment by Bobbanz1** [comment]
@covertcorvid Issue should have been fixed as a result of [1720](https://github.com/BeeStation/NSV13/pull/1720)
