### ISSUE TITLE
Centcomm still bugs the ship to patrol after being taken off active patrol

### ISSUE THREAD

**Issue by jzburda** [BeeStation/NSV13#1303]
## Testmerges:

#1294: 'Fleet combat - Tabletop edition' by DeltaFire15 at commit 166c221c61
-Entirely unsure this was the cause. This issue's been happening since last week too

## Reproduction:
After being sent a message that the ship is taken off active patrol, Centcomm will then 10 minutes later send the ship a message to explore. This is despite the fact the "off active patrol" message states something along the lines of being able to do "other activities"

**Comment by Pontenerd** [comment]
This has been an issue for a LONG time

**Comment by jzburda** [comment]
> 
> 
> This has been an issue for a LONG time

I only checked "Centcomm" as a tag. My bad.

**Comment by jzburda** [comment]
#1080
