### ISSUE TITLE
Cryoing SSD traitors may be what causes rounds to end abruptly

### ISSUE THREAD

**Issue by GoatMonarch** [BeeStation/NSV13#1304]
## Testmerges:
Likely old code

## Reproduction:
We had a single miner traitor this round, me the clown went up, put them into cryo, minutes after their body was prossesed, the anouncement came. A few minutes there after the round ended likely due to the traitor being gone.
Cryo code may be kinda shit.
(Side note; dude was standing in a hallway with weapons, not leaving that around. Bruh.)

**Comment by Bokkiewokkie** [comment]
Fixed through the config
