### ISSUE TITLE
Cannot scan seemingly completely random sectors on Astrometrics, round nodes outside of Foothold would not show up

### ISSUE THREAD

**Issue by jzburda** [BeeStation/NSV13#1307]
## Reproduction: In round 2083, the nodes outside of Foothold (S- nodes and N- Nodes) were completely unavailable. In 2084, I cannot scan anything with a red outer circle

[https://i.imgur.com/XOTu5XT.png](url)

**Comment by Bokkiewokkie** [comment]
The red outer circle means the ship's scanners are out of range, so you have to move the ship closer to them on the starmap to actually be in range.

**Comment by jzburda** [comment]
> 
> 
> The red outer circle means the ship's scanners are out of range, so you have to move the ship closer to them on the starmap to actually be in range.

Usually that would mean you can't warp to it, so a pull happened I'm completely unaware of that drastically nerfed Astrometrics

**Comment by covertcorvid** [comment]
The astrometrics console has been range-limited for as long as I can remember, wasn't a recent nerf. Your sensors only reach so far.
The nodes appearing as lines is a bug with sectors occupied by pirates.

**Comment by Bokkiewokkie** [comment]
Closing this because it's clearly not an issue
