### ISSUE TITLE
Optional objective to kill bubblegum

### ISSUE THREAD

**Issue by Pontenerd** [BeeStation/NSV13#1316]
Issue reported from  Round ID: 2104 (NSV 13 | Official | MRP | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1536

![image](https://user-images.githubusercontent.com/68692362/112736230-08536600-8f49-11eb-9110-d65bfb6a98b6.png)

**Comment by Bokkiewokkie** [comment]
Is he dead if he doesn't exist at all?
