### ISSUE TITLE
People on Atlas arrivals shuttle can get stunlocked and deafened

### ISSUE THREAD

**Issue by Grabovvski** [BeeStation/NSV13#1320]
## Round ID:
multiple rounds

## Testmerges:
I think this has been a problem for a long time

## Reproduction:
If you arrive on the Atlas when the guns are fifring (most likely the Gauss), you will get stunlocked and deafened for all eternity. Also there is no Atlas map issue template.

**Comment by Bokkiewokkie** [comment]
Forgot to link this issue in #1371, it should be closed now
