### ISSUE TITLE
Dynamic room fails to spawn - Atlas

### ISSUE THREAD

**Issue by AU518987077** [BeeStation/NSV13#1349]
## Round ID: 
2225 and few others

## Reproduction:
walk to the 3x3 room portside door of the engineering equipment vendor in atlas top deck portside maint's at any point of the shift and observe. seen it three times now. so very rare.
![image](https://user-images.githubusercontent.com/24924661/114986329-1bbf6600-9e51-11eb-8bb7-936bd0f09a08.png)

[![](http://img.youtube.com/vi/E6NvxjxJIB8/0.jpg)](https://youtu.be/E6NvxjxJIB8?list=PLMDmYuVZH5LN25LJBZel8RPZoGniI8m7y&t=1026 "It is just open vacuum")
It is just open vacuum

Ansome might recollect this happening atleast two other times to this exact room because i ahelped those times as well.

**Comment by Vasily2013** [comment]
Attempted to verify, unable.
