### ISSUE TITLE
Tyrosene fuel pump has potential to bug out and spam chat every time player that bugged it out moves a tile(?)

### ISSUE THREAD

**Issue by jzburda** [BeeStation/NSV13#1351]
## Testmerges:

#1332: 'Resolves some airlock and parallax issues from the rebase' by Kmc2000 at commit 39be6629eb
#1331: 'Fixes some things I guess' by Bokkiewokkie at commit 27a2071008
#1324: 'April fools is literally bricking the job selection this is funny but also really isn't' by DeltaFire15 at commit 0539160d3d
#1334: 'Fixes AI up/down buttons' by covertcorvid at commit 929814e1e2
#1337: 'Gave brigphys access to brig' by covertcorvid at commit d614f7e482
#1330: 'NPC Hitbox Expansion' by Karmic-Skink at commit 6275e3144c
#1342: 'Allowed AI to see the AI multicam room and the Overmap' by covertcorvid at commit 025a106162
#1343: 'Increases maximum TGUI windows and timeout for opening windows' by covertcorvid at commit bac958d8f8
#1289: '[WIP] [ANTAG] IT CAME FROM OUTER SPACE....' by Kmc2000 at commit 1476466169

## Reproduction:
While refueling, click the Tyrosene pump. The pump will become bugged out and every time the character that bugged it out moves, the tyrosene pump will play an emote that says "Aviation fuel delivery hose snaps back into Tyrosene fuel pump!"

**Comment by covertcorvid** [comment]
Believe this was closed with the cryofuels PR.
