### ISSUE TITLE
Munitions chat is white

### ISSUE THREAD

**Issue by Pontenerd** [BeeStation/NSV13#1353]
Issue reported from  Round ID: 2240 (NSV 13 | Official | MRP | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1536

![image](https://user-images.githubusercontent.com/68692362/115100700-3fa8a780-9f36-11eb-880d-15bc7d49ebef.png)

**Comment by Karmic-Skink** [comment]
https://github.com/BeeStation/NSV13/pull/1339
Check current PRs first.

**Comment by Pontenerd** [comment]
> 
> 
> #1339
> Check current PRs first.

> Issue reported from Round ID: 2240 (NSV 13 | Official | MRP | 98% Free Lag | Fresh Tupelo)
