### ISSUE TITLE
NAC construction jank

### ISSUE THREAD

**Issue by Omppusolttu** [BeeStation/NSV13#1354]
NAC construction hitboxes are a mess, and even roundstart ones don't line up properly with the sprite. Making them is utter jank as just rotating them 4 times ends up with the sprite changing place, I frankly have no idea where the actual hitbox is, which isn't THAT much of an issue until you take into account that it needs to be lined up perfectly with a gun core to work.

## Reproduction:
Try walking at a NAC ingame at all angles, and then try to construct one.

**Comment by Ikalpo** [comment]
this was fixed back in #1431
