### ISSUE TITLE
HoS does not spawn with the spare safe's code

### ISSUE THREAD

**Issue by Grabovvski** [BeeStation/NSV13#1378]
## Round ID:
multiple rounds

## Testmerges:
multiple rounds

## Reproduction:
Basically what the title says. Its not on a paper, not in the Notes, not in the office. Most likely caused by the fact that the HoS spawns with a flash and handcuffs in his pockets.

**Comment by covertcorvid** [comment]
It's supposed to spawn in your backpack or one of your hands if your pockets are full, and failing that at your feet. Will investigate.

**Comment by covertcorvid** [comment]
In testing as the only head the paper spawned in the backpack. Please let me know if that's not the case for you as ranking head whenever you get to do it next.

**Comment by covertcorvid** [comment]
This seems to be fixed.
