### ISSUE TITLE
Munitions trolleys not unloading properly

### ISSUE THREAD

**Issue by jdeuce22** [BeeStation/NSV13#1399]
## Round ID:
happens in pretty much every round, but I discovered it in: round 2351

## Testmerges:
Boarding

## Reproduction:
load any munitions trolley at all, then unload the missile, you'll notice that the trolley doesn't have the sprite, BUT IT STILL HAS IT SET SO THAT SLOT IS LOADED, THIS HAPPENS WITH EVERY GOT DAMN SLOT

**Comment by covertcorvid** [comment]
Unable to reproduce on master, will need to try it with boarding whenever we go up again.

**Comment by jdeuce22** [comment]
tried it in the current round, still there

**Comment by jdeuce22** [comment]
actually, maybe it's because I accidently took the trolley into the dropship while  being a dumbass and trying to load missiles into the dropship

**Comment by jzburda** [comment]
Can confirm this happens with torpedo casings and fully built missiles

**Comment by jdeuce22** [comment]
not related to the main issue, but nice

**Comment by jzburda** [comment]
> 
> 
> not related to the main issue, but nice

This is related to the munitions trolley. This proves that just about no matter what is loaded on the trolley, it's never counted as unloaded.

**Comment by jdeuce22** [comment]
> > not related to the main issue, but nice
> 
> This is related to the munitions trolley. This proves that just about no matter what is loaded on the trolley, it's never counted as unloaded.

I meant the comment, but I didn't know that, so perhaps the code is set so that it doesn't change the slots remaining when you load it with casings and missiles.. perhaps it's the changing from torp code to missile code that messes it up? and I think I have an idea that'd fix the missile problem

**Comment by jzburda** [comment]
> 
> 
> > > not related to the main issue, but nice
> > 
> > 
> > This is related to the munitions trolley. This proves that just about no matter what is loaded on the trolley, it's never counted as unloaded.
> 
> I meant the comment, but I didn't know that, so perhaps the code is set so that it doesn't change the slots remaining when you load it with casings and missiles.. perhaps it's the changing from torp code to missile code that messes it up? and I think I have an idea that'd fix the missile problem

Oh, that's fair. I'll just snip that off. Just thought it was funny as hell.

**Comment by covertcorvid** [comment]
I'm told that the issue happens when you **don't** use the UI to unload, so that's why it wasn't happening to me. Thanks all.
