### ISSUE TITLE
Revenant can't move z levels without piggybacking in a lift

### ISSUE THREAD

**Issue by covertcorvid** [BeeStation/NSV13#1405]
What it says on the tin

**Comment by Pontenerd** [comment]
Do you think this could be solved by giving them the move up/down verbs? They are essentially ghosts after all

**Comment by covertcorvid** [comment]
> 
> 
> Do you think this could be solved by giving them the move up/down verbs? They are essentially ghosts after all

Yes, I think that's the ideal solution. They should have the verbs but are currently unable to use them without an openspace tile.

**Comment by Bokkiewokkie** [comment]
This also applies to Sentient disease when picking a first target I believe
