### ISSUE TITLE
AI status displays not updating or working

### ISSUE THREAD

**Issue by CRISPR-core** [BeeStation/NSV13#1412]
## Reproduction:

1. Be AI.
2. Attempt to change AI status display to 'red dot, blue dot'. 
3. Notice nothing changes.
4. Attempt to change AI status display to 'friend computer.'
5. Notice it is now stuck on 'friend computer,' and will not change.
6. Confirming the larger map works. This seems to only affect the smaller map.

Issue: AI status displays either do not work, or get stuck.

**Comment by covertcorvid** [comment]
Saw a status display get set last weekend, so this seems to be fixed.
