### ISSUE TITLE
Air to Air resupply over-fill fighters with ammo / Cargo hold can't hold torepdo or missiles

### ISSUE THREAD

**Issue by KacperRaid** [BeeStation/NSV13#1423]
## Reproduction:
Air to Air resupply over-fill fighters with ammo:
1. load few boxes of light cannon OR heavy cannon into cargo hold.
2. use BRRRRR cannon till it run out.
3. try to resupply that fighter.
4. over-supply it with as much ammo
 you throwed into cargo hold (they will be dropped on ground, no way of getting them back from overmap tho)
**5?** (it will probably tie to same problem of loading torpedo/missiles, that might over-supply them as well)
![Over-filled](https://user-images.githubusercontent.com/82459794/119819443-adaa9c00-bef0-11eb-8eca-277c068e8a48.png)

cargo hold can't hold torepdos nor missiles
1.try to load torpedo/missiles to cargo hold
2. it won't let you
(probably oversight in code)

**Comment by covertcorvid** [comment]
I think this is fixed. If not, we'll reopen it.
