### ISSUE TITLE
Boarding pins don't work on enemy ships

### ISSUE THREAD

**Issue by Vivalas** [BeeStation/NSV13#1436]
## Reproduction:
Take a gun to an enemy ship, and try to fire it.
Proceed to get murdered by simplemobs.

I've been informed by players on two occasions now  (and personally witnessed one of those occassions), where the boarding M16s don't work on enemy ships, and the boarders resort to using glocks. Admin logs corroborate this as they end up attacking syndie crew with 9mm rounds.

**Comment by covertcorvid** [comment]
Thanks, I put in a fix for this but I don't think the code on the server has been updated yet

**Comment by Vivalas** [comment]
gotcha, wanted to make sure this was logged since it's happened a few times
