### ISSUE TITLE
Missing techpriest robe textures

### ISSUE THREAD

**Issue by Freakycrafter** [BeeStation/NSV13#144]
## Reproduction: Wear a techpriest robe and put on the hood.

Basically just missing textures for the techpriest robe, its just squares.
![image](https://user-images.githubusercontent.com/57047909/69484019-815f1c80-0e2e-11ea-85eb-d9c53dcf789f.png)
![image](https://user-images.githubusercontent.com/57047909/69484046-e4e94a00-0e2e-11ea-8422-d11b7da08c66.png)

**Comment by Vasily2013** [comment]
upstream
