### ISSUE TITLE
Fighter Fuel Pump UI is broken

### ISSUE THREAD

**Issue by SerynEngi** [BeeStation/NSV13#1445]
## Round ID:

Multiple Rounds

## Testmerges:

Not Relevant.

## Reproduction:

Fighter Fuel Pumps work, but visually this message pops up instead of the proper UI when you grab them to use them.

![](https://cdn.discordapp.com/attachments/697454064480288828/853433737122283550/Broken_UI.PNG)

**Comment by covertcorvid** [comment]
This has been fixed
