### ISSUE TITLE
Unable to dock with Mainship- Galactica

### ISSUE THREAD

**Issue by SerynEngi** [BeeStation/NSV13#1456]
## Round ID:

2592

## Testmerges:

https://github.com/BeeStation/NSV13/pull/1418
https://github.com/BeeStation/NSV13/pull/1454

## Reproduction:

Long and short of it, in this Galactica round, all fighters lost the ability to dock with mainship. Multiple methods were tried to make that work, but none succeeded. Ansome would be a better person to ask for admin methods that he attempted, but for me, I attempted to reset the docking computer and turned the ship on and back off again. No other fighters were able to dock, either. 

When I was respawned on the ship, I was prevented from docking the next time I launched, as well.

**Comment by Bokkiewokkie** [comment]
From what I can tell, the boarding PR (#1397) was not testmerged during this, and since the boarding PR fixes Galactica's magcat issues this will most likely be resolved already by that. Please do try to recreate this *with* the boarding PR testmerged if you can, to make sure it's actually fixed.
