### ISSUE TITLE
Sleeper regression related to beebase

### ISSUE THREAD

**Issue by Freakycrafter** [BeeStation/NSV13#146]
## Reproduction: Try upgrading a sleeper (not a stasis bed)

I tried upgrading a sleeper with the bluespace rped and it didnt work, after that i just disassembled it, but it didnt leave the sleeper board for some reason, after i got new boards i could put in advanced components like i was building a new sleeper.

**Comment by TheChosenEvilOne** [comment]
Sleepers remove their circuits on mapload as of tgstation/tgstation#43075, the initialize proc should be overwritten to fix this.

**Comment by francinum** [comment]
Regressed. issue active again as of Round ID 152
