### ISSUE TITLE
It is possible to grab gunpowder while it's loaded on a trolley

### ISSUE THREAD

**Issue by Omppusolttu** [BeeStation/NSV13#1469]
## Reproduction:

By placing propellant (atleast gunpowder, not tested on PKA) on a trolley you can click to pick the bottommost one up while not removing it from the trolley, effectively infinitely duplicating propellant.

**Comment by Bokkiewokkie** [comment]
Okay so this doesn't actually duplicate the item, it just doesn't "remove" the item from the trolley, which means you can pick it back up from anywhere after taking it out unless it's stored inside something else (like a naval gun powder loader) and after the powder gets deleted the reference to it on the trolley will also disappear
