### ISSUE TITLE
Augmented machines are invisible when augmented

### ISSUE THREAD

**Issue by Freakycrafter** [BeeStation/NSV13#148]
## Reproduction: Augment a machine person

Basically, if you augment a machine person they turn (or parts of them) invisible, probably another missing texture bug.
![image](https://user-images.githubusercontent.com/57047909/69484753-4f05ed00-0e37-11ea-8e40-898212dda9ac.png)

**Comment by Kmc2000** [comment]
I'm unable to reproduce this locally. Is there any further info you can provide?

**Comment by Vasily2013** [comment]
Is this an issue upstream as well?

**Comment by francinum** [comment]
Thinking about it, this is likely an issue with asset caching, But seeing as it's pre beebase, if it comes up again it'll be investigated, otherwise I'm calling it an edge case.
