### ISSUE TITLE
obj/effect/mob_spawn/corpse/assistant does a runtime

### ISSUE THREAD

**Issue by Ikalpo** [BeeStation/NSV13#1510]
## Round ID:
N/A
## Testmerges:
No
## Reproduction:
spawn one and oops, runtime
or get random maint room number 081 on your PR, causing the test to fail :agony:
```Runtime in _job.dm,306: Cannot execute null.get access().```

**Comment by Bokkiewokkie** [comment]
Unsure if this still happens after #1548 so I'm keeping it open until it's confirmed to be fixed.
