### ISSUE TITLE
Railgun and MAC kits are still available in trader stores

### ISSUE THREAD

**Issue by Karmic-Skink** [BeeStation/NSV13#1520]
Title:

![image](https://user-images.githubusercontent.com/45891563/124468567-690bfd80-ddd8-11eb-93a0-8dd42b84991e.png)

**Comment by RemervKeberb** [comment]
Flak ammo is also still in, also we now have two issues about this matter, https://github.com/BeeStation/NSV13/issues/1357

**Comment by Karmic-Skink** [comment]
Flak ammo is technically still viable.

**Comment by RemervKeberb** [comment]
Oh is it? Didn't know that.
