### ISSUE TITLE
Galactica - APC wires and AI sat power

### ISSUE THREAD

**Issue by ondrej008** [BeeStation/NSV13#1529]
On Galactica, the area called Engineering Storage (Engineering Equipment) next to the main entrance of upper engineering doesn't come with it's APC wired. 
On Galactica, the entirety of upper security isn't actually connected to the rest of the ship with a power cable.
On Galactica, the AI satellite/telecommunications satellite doesn't come with enough power or a connection to the main ship,
there are 20 solar panels, which at their peak can produce 30 kW of power, tcomms drains about 20 kW which means that on average, the SMES on that sattelite is going to be always draining.

!!! !!! !!!

This map is no longer supported. This issue template will be deleted eventually.

!!! !!! !!!

**Comment by AU518987077** [comment]
wonder if this can get added to #1521
