### ISSUE TITLE
Knpc boarders being far too powerful

### ISSUE THREAD

**Issue by Omppusolttu** [BeeStation/NSV13#1560]
On round 2783. Two Knpc boarders killed 15 crewmembers of a 20 player crew, and even then the TWO knpcs only died after an entire ERT squad was brought on and the NPCs ran dry of ammo (even then they pistolwhipped an ERT member to death), hell before the ERT arrived both Knpcs were at full health, meaning nobody managed to even scratch one.

This is frankly ridiculous especially since they were originally added to help with lowpop, this is just going to wipe out lowpop crews instead of helping it be more fun.

My personal advice would be to make them do each input slower, and perhaps even give them worse gear.

**Comment by James-source** [comment]
I want at least a 200 millisecond delay on most actions they do, thats the fastest reaction time for the average human.
In that round like 5-10 people got wiped in 4 frames or less due to spacelag, just no, make them a solid 1v1 match against your **average** seccie.

**Comment by Karmic-Skink** [comment]
> On round 2783. Two Knpc boarders killed 15 crewmembers of a 20 player crew, and even then the TWO knpcs only died after an entire ERT squad was brought on and the NPCs ran dry of ammo (even then they pistolwhipped an ERT member to death), hell before the ERT arrived both Knpcs were at full health, meaning nobody managed to even scratch one.
> 
> This is frankly ridiculous especially since they were originally added to help with lowpop, this is just going to wipe out lowpop crews instead of helping it be more fun.
> 
> My personal advice would be to make them do each input slower, and perhaps even give them worse gear.

KNPCs were not added to help with low pop.
