### ISSUE TITLE
Fighter cannot move, only turn to point at the mouse

### ISSUE THREAD

**Issue by maxion12345** [BeeStation/NSV13#1571]
Issue reported from  Round ID: 2822 (NSV 13 | Official | MRP | 98% Free Lag | Fresh Tupelo)

Reporting client version: 514.1554

When launched the fighter will not move foward/back or strafe, and you need to re-ignite to get control. Obviously not a good thing if you are in combat as you cannot dodge missiles, and will die sitting there waiting to re-spool the tiny bit of RPM you lost turning off your engine.

**Comment by covertcorvid** [comment]
Have not had anyone else report this and am unable to reproduce it in testing
