### ISSUE TITLE
Fleet spawning requires working on.

### ISSUE THREAD

**Issue by Omppusolttu** [BeeStation/NSV13#1573]
On round 2833 The crew after a successful shift was dropped in system between two nuclear frigates that proceeded to melt the ship from 3000 shield integrity to death.

The Bridge staff was unable to even start moving the ship before 6 nukes had landed and utterly destroyed the ship.

This is the worst case scenario but stories of ships getting screwed over by spawning into an enemy fleet are EXTREMELY common, I ask that someone adjusts fleet spawning so that this does not happen.

**Comment by Karmic-Skink** [comment]
It's Hot Drop O'clock.

**Comment by Bokkiewokkie** [comment]
Fixed now
