### ISSUE TITLE
Constrictor boards don't exist

### ISSUE THREAD

**Issue by SirRailOfGun** [BeeStation/NSV13#158]
The hammerhead has no plasma constrictor boards in tech storage, rendering them irreplaceable should an incident destroy the constrictors. Tech storage should have at least two, as it is likely that if one breaks, the other will as well.

**Comment by Karmic-Skink** [comment]
Constrictor boards aren't a real thing.

**Comment by francinum** [comment]
These things are snowflake and need to be made standardized and upgradable.
