### ISSUE TITLE
Ticket Objective Autocompleted

### ISSUE THREAD

**Issue by TheOneAndMightyRed** [BeeStation/NSV13#1602]
## Round ID:
2949 or 2950 (serb looked like it crashed after restart or whatever. We had aether that round and conquered rubi)

## Testmerges:
#1564 
#1586 
#1584 
#1566 
#1582 
#1598 

## Reproduction:
Mostly due to #1566 
When completing objectives a vote came up with [5 voting to continue and 3 voting to go home](https://i.imgur.com/pvQ1OEi.png).
Game then tells us that we got additional objectives and lets us alone.
About two minutes later [the game does a full 180, skips a vote we weren't even notified about and just decides to send us home forcefully](https://i.imgur.com/bhGgvef.png).

**Comment by Karmic-Skink** [comment]
I need more detail.

**Comment by AU518987077** [comment]
Shift 2953
![image](https://user-images.githubusercontent.com/24924661/131206310-9f5333a3-4051-4f93-86a7-13c9afa1053c.png)
I as the AI tried to cancel the jump as i noticed peopel were talking as if we  were jumping, and it wouldnt let me cancel and we jumped anyways
![image](https://user-images.githubusercontent.com/24924661/131206402-da118942-a067-43ad-9a1f-6445e8dad5ea.png)
as you can see in my second screen insert the FTL window the cancel jump button is available even though i 

and apparently U.S.S.R. tried to cancel as well
![image](https://user-images.githubusercontent.com/24924661/131206392-75cd5316-82e5-4c71-bb11-e30bd363269a.png)

**Comment by covertcorvid** [comment]
Being unable to cancel the jump to Outpost 45 is intentional. Having an immediate completion of the extra objective and two votes definitely isn't.
If anyone knows/remembers what the additional objective was, please let us know. We're wondering if it failed to initialize correctly and was then marked as "done" by the system.

**Comment by Karmic-Skink** [comment]
This appears to be a "tickets" objective, so instantly completed.

**Comment by Karmic-Skink** [comment]
I've pushed a fix for it.

**Comment by TheOneAndMightyRed** [comment]
Just happened again on Round Id: 2971


![grafik](https://user-images.githubusercontent.com/41807890/131257658-120495c9-841d-4474-aed4-16720384bdd5.png)

**Comment by covertcorvid** [comment]
This was resolved
