### ISSUE TITLE
Abrupt round end despite healthy ship and extended ship mission

### ISSUE THREAD

**Issue by williamcll** [BeeStation/NSV13#1630]
## Reproduction:
The ship just cleared romulus system after going through rubicon defense force. Of note the traitor went to cryo 10 minutes before this happened. as the ship didn't return to outpost nor the shuttle was called, only 30 torpcoins were given.

![](https://media.discordapp.net/attachments/602204464908075029/886230434852241458/unknown.png)

**Comment by Bokkiewokkie** [comment]
Still need verification that this is definitely not the traitor dying/cryo-ing bug again.

**Comment by williamcll** [comment]
> Still need verification that this is definitely not the traitor dying/cryo-ing bug again.

no idea

**Comment by Bokkiewokkie** [comment]
> Still need verification that this is definitely not the traitor dying/cryo-ing bug again.

Going to close it because I haven't seen evidence against it
