### ISSUE TITLE
fighter RPMs won't go up if you've failed to start previously

### ISSUE THREAD

**Issue by covertcorvid** [BeeStation/NSV13#1651]
## Round ID: 
test instance

## Testmerges:
boarding cleanup 2

## Reproduction:
try to start fighter, but forget to wait for ignition
turn everything off
turn off master caution
turn everything up to the APU back on
observe battery drain but no engine rpms

**Comment by RemervKeberb** [comment]
Isn't this somewhat intentional? IIRC that causes your engine to flood and you can screwdriver your engine to fix it. Though I think when someone else had this issue that didn't fix it for them.

**Comment by covertcorvid** [comment]
> 
> 
> Isn't this somewhat intentional? IIRC that causes your engine to flood and you can screwdriver your engine to fix it. Though I think when someone else had this issue that didn't fix it for them.

Oh, that could be. Some feedback on that would probably be good though.
