### ISSUE TITLE
The Cognitohazardous RnD consoles (Aka an unfunny RnD console bug that makes your game crash)

### ISSUE THREAD

**Issue by DrCrawler** [BeeStation/NSV13#1654]
Issue reported from  Round ID: 3104 (NSV 13 | Official | MRP | 98% Free Lag | Fresh Tupelo)

Reporting client version: 514.1561
Ok so on a normal round, while i wasnt expecting much to happen came out a peculiar bug that may be hard to replicate
The RnD console (the tech screen to be exact) made the game crash. It was tested on several players and their game crashed too. I tried to disassemble the console, but when i opened the tech screen again it was still bugged.

So, you might ask how it got to that point, and that is a question of quality.
All i did is rapidly research everything i could like usualy, and then my game crashed. I reconnected and thought that it was an issue on my end, but it became clear once i fell into the trap around 30 times. Then i decided to not touch anything at all and i stayed connected. I moved away from the console and everything was fine, but when i touched it again i got disconnected. After that i decided to try it on a few more people and they experienced the same.

My version was listed above. The bug still worked on version 513.1539 (it was stable at the moment as far as i know)

Ill make a comment if i find out that its still bugged on other consoles.

**Comment by Karmic-Skink** [comment]
If this happened around 30 times, why did you wait until after round end to ahelp?

**Comment by DrCrawler** [comment]
I ahelped while the round was going. Also im quite the slow thinker and thought that it was an issue on my end.

**Comment by 4310V343k** [comment]
Can be related to icons, as using non-iconified views of the console temporarily (until you turn on icons) fixes the error. After researching some nodes i switched back to iconified view and the bug disappeared
