### ISSUE TITLE
Hybrid Railguns disappearing during maintenance

### ISSUE THREAD

**Issue by SpagootyEggant** [BeeStation/NSV13#1656]
## Round ID: 3114
The durability of the hybrids drops as you fire it, and when it gets too low, you replenish durability with oil. Issue is, opening the maintenance panel for a re-oiling just appears to delete the gun.

## Reproduction:
1: Screwdriver, wrench, and crowbar the hybrid railgun for maintenance
2: Watch helplessly as your main offensive tool turns to dust before your eyes

**Comment by Karmic-Skink** [comment]
User error, you don't crowbar the railgun to enter maintenance.
