### ISSUE TITLE
No-kill traitor option not working for AI

### ISSUE THREAD

**Issue by williamcll** [BeeStation/NSV13#1675]
## Reproduction:
on merge 1617 regarding no kill traitor objectives: the current set minimum is 15, however it doesn't seem to apply on midround malf AIs with just 5 players in-game and 7 online: Which ended up with me killing all crew since the preventing shuttle could also mean killing crew instead of locking them up or put to sleep.
![image](https://user-images.githubusercontent.com/43061493/135705299-d4cd6344-1230-4607-ab90-0298c1ebfdce.png)
Additionally, Ion laws still have elimination laws on lowpop, not sure if that is intended or not:
![image](https://user-images.githubusercontent.com/43061493/135705355-cd398ed4-9b9b-4cae-8c6c-8d8886c17aa7.png)
![image](https://user-images.githubusercontent.com/43061493/135705351-ba12319e-c039-45d3-a543-41bac3b30d43.png)

**Comment by Karmic-Skink** [comment]
Admin intervention was involved in this round. Working as intended.
