### ISSUE TITLE
Ghosts can pulse the radar at a dradis console

### ISSUE THREAD

**Issue by VEN0M5** [BeeStation/NSV13#1677]
## Reproduction:
1) Be ghost
2) Find DRADIS computer at the bridge
3) Start spamming radar pulse while crew is repairing cuz I ded restart
4)???
5) Profit

**Comment by VEN0M5** [comment]
You can turn on active radar as well

**Comment by Karmic-Skink** [comment]
We keep having issues with this one, we'll look into it again.
