### ISSUE TITLE
Hotswappable Starmap via Json

### ISSUE THREAD

**Issue by Kmc2000** [BeeStation/NSV13#1716]
-SSstarsystem currently uses statically defined system types for its declaration.
-The system should be refactored to allow dynamic loading from disk, which will allow configurable maps & hot-loading with a view of (redacted).

Effort estimation: Low
ETA: 2d

**Comment by Bokkiewokkie** [comment]
- [ ] Making the CI not blow up
- [ ] Polishing the map and testing it
- [x] Ensure the box stays up to date as the json is changed around in the code PR
