### ISSUE TITLE
Outdated Sabres

### ISSUE THREAD

**Issue by TheScienceOfKSP** [BeeStation/NSV13#1729]
## Issues: 
1-Name option does not work
2-If you close the Dradis, you cannot reopen it without having to exit the console
3-All its support gear options are nonfunctional
4-Canopy glass serves no purpose
5-Interior has a redundant console that serve no purpose

## Reproduction: 
1-Attempting to use the name option in the player panel or ship panel does nothing, no pop-up, nothing.
2-Closing the Dradis while on the console prevents it from being re-opened, barring anything short of hopping on and off the console, this tends to be a bad idea mid-flight.
3-Refer to above, Air to Air Refuel/Resupply equipment can be attached to the craft, and even fed their "ammo", but remain unfunctional, regardless of weapon safeties, z-level/overmap, and distance between target and craft.
4-The pilot sits in a separate z-level, canopy glass has no impact on survivability or armor.
5-The pilot suites middle console to be exact, as far as memory serves.

**Comment by Bokkiewokkie** [comment]
It's been so long we need to verify this

**Comment by covertcorvid** [comment]
the verbs have actually never worked on stuff that's area-linked and it makes me sad.
