### ISSUE TITLE
Fighters do not go foward/backward, and you can hear the master caution after exiting the fighter

### ISSUE THREAD

**Issue by maxion12345** [BeeStation/NSV13#1748]
## Testmerges: 
#1719: 'Adds dynamic starmap loading (resolve #1716)' by Kmc2000 at commit b4e4704f02
#1747: 'Fixes AI bot control' by TheFakeElon at commit e5c60a3745
#1745: 'Armada Gamemode Update' by Karmic-Skink at commit 8e32c8a05e
#1737: 'Adds syndicate access to munitions cargo packs' by covertcorvid at commit b6bdfb258e
#1730: 'Unscrungles the Fist of Sol' by QAI-07 at commit 01062a151b
#1726: 'Re-adds escape pods' by covertcorvid at commit 8e64b5eca1
#1714: 'Adds spaceborn quirk' by TheFakeElon at commit bf901b3d66
#1713: 'KNPC cleanup and optimizations' by TheFakeElon at commit 9f6c37102b
#1692: 'Tweaks Radstorm event to be less impactful' by Absolutely-Steph at commit 46885e047b

## Reproduction:
I entered the fighter, started engines, and tried to move. Wouldn't move. W/S functionality doesn't work. You can strafe if IAS is disabled, but that's the only movement you get. Oh, this strafing movement isn't stopped by the brakes either so once you get going, you cannot stop. No fucking idea what triggers it, because we swapped fighters to one that worked, then stopped after I loaded it with arms (30mm cannon + missiles)

**Comment by Panicat** [comment]
I have also experienced the "you can hear the master caution after exiting the fighter". I get it after getting out of a fighter escape pod. 'Stop sounds' did not stop it the times I experienced it.
