### ISSUE TITLE
Cross server messages no longer work

### ISSUE THREAD

**Issue by someone543** [BeeStation/NSV13#1769]
## Description: 
Any message sent using the communication console "Send a message to an allied station” option are not received by Beestation Sage or Acacia and vice versa. News reports (eg The crew of [station_name] has been evacuated amid unconfirmed reports of enemy activity) have also stopped appearing. 

## Reproduction:

1. Send a cross server message using communications console 
2. Receive no reply

1. Watch a round end on Beestation Sage or Beestation Acacia on https://beestation13.com/stats while playing NSV13
2. Receive no news report

**Comment by red031000** [comment]
this is still an issue

**Comment by williamcll** [comment]
The same also applies on bee.

**Comment by someone543** [comment]
Seems to be working now. Closing.
