### ISSUE TITLE
Asteroid dissapeared while I was mining on it

### ISSUE THREAD

**Issue by Pontenerd** [BeeStation/NSV13#1785]
Issue reported from  Round ID: 3667 (NSV 13 | Official | MRP | 98% Free Lag | Spaceship Combat Server)

Reporting client version: 514.1575

![image](https://user-images.githubusercontent.com/68692362/149629074-5219dfe2-ab36-4ce1-a941-a1940f68f934.png)
i flew a raptor out to an asteroid to mine it, i began mining on it, then it dissapeared and put me on the overmap

**Comment by covertcorvid** [comment]
Hopefully maybe fixed by making the space on an asteroid part of the asteroid area, but only time will tell
