### ISSUE TITLE
Swarmers can destroy FTL spooling console and armor wells.

### ISSUE THREAD

**Issue by sunofang** [BeeStation/NSV13#1799]
## Round ID:
3753

## Testmerges:
BYOND Version: 514.1569
Server revision compiled on: 2022-01-29T18:25:43+00:00
Master commit: 70767af2f85bf88f9fbed8c1898c307dd2de8e05
The following pull requests are currently test merged:
#1778: 'Removes right-side squad role hud indicators and updates left-side lanyard squad hud indicators ' by IndusRobot at commit e930bef5a4
#1790: 'Fashionable Bomber jacket accessory' by Absolutely-Steph at commit f7303c261c
#1789: 'Fixes an oversight where silicon are not included when finding aggressors' by IndusRobot at commit e499af8d22
#1794: 'Tweaks overmap interior explosions on destruction' by DeltaFire15 at commit b8a7cb1dc8
#1788: '[Aetherwhisp] Mining hangar + bugfixes ' by IndusRobot at commit 582962087b
#1711: 'Significant physics subsystem optimizations' by TheFakeElon at commit 41a3e48198
#1793: 'Bloody Eye (Again, I'm sorry)' by BetaCentari at commit 1d6c750d74
#1762: 'Munitions Machinery Maintenance Mechanics: Ammo Stackers/Sorters' by Absolutely-Steph at commit 0f40fb7284

## Reproduction:
Just dismantle the spooling console and armor wells as a swarmer. They have no restrictions stopping it, Which doesnt make sense lorewise since they are meant to not cripple the ship to preserve themselves.

**Comment by DeltaFire15** [comment]
Not an upstream issue as bee does not have armor wells nor FTL. Nonetheless should be closed by the linked PR.
