### ISSUE TITLE
Impossible to disable Laser Guidance on small craft (at least on a sabre)

### ISSUE THREAD

**Issue by Kelnor277** [BeeStation/NSV13#1809]
Pressing C does not disable laser guidance. I made sure to test with my C key not being bound to anything else.
This means you always have mouse control on, and some functions require using the mouse.

This makes it annoying to park (ship orientates to the mouse when you try to exit ship)
Far more deadly when you have to disable safeties or docking mode and your ship flips end over end.
I don't understand why this was done?
If we're going to insist on this, then we need keybinds for just about everything.

**Comment by Karmic-Skink** [comment]
This was fixed well before you made this issue.
