### ISSUE TITLE
Sentient Disease cannot change Z-levels for initial infection vector

### ISSUE THREAD

**Issue by SerynEngi** [BeeStation/NSV13#1811]
## Round ID:
3793

In summary, for initial selection, you cannot select a target on a different Z-level, which largely limits your selection. This is particularly painful on the Aetherwhisp if you get the lower level, as you end up being stuck with a choice of medical or engineering, or on extremely rare occasions, security.

## Reproduction:
1. Become Sentient Disease
2. Attempt to switch Z-Levels to find a better target on initial selection
3. Be unable to click on ladders or have a button to switch Z-levels

**Comment by TheFakeElon** [comment]
relatively easy fix but I believe sentient diseases are pending removal on upstream
