### ISSUE TITLE
Volatility components do not appear to be set and acted upon correctly

### ISSUE THREAD

**Issue by Karmic-Skink** [BeeStation/NSV13#1813]
Things are not exploding when they should be exploding, at least as often.

![image](https://user-images.githubusercontent.com/45891563/152754382-9bac5a0d-5ec8-46cc-8fbd-6f8e6bc31c92.png)

Needs verification.

**Comment by TheFakeElon** [comment]
I believe this issue was fixed in #1871 and #2008
