### ISSUE TITLE
Unable to control ghost ship

### ISSUE THREAD

**Issue by someone543** [BeeStation/NSV13#1836]
Issue reported from  Round ID: 3858 (NSV 13 | Official | MRP | 98% Free Lag | Spaceship Combat Server)
Hopped on a Mako class patrol frigate and was unable to move, zoom out, or shoot. 
Reporting client version: 514.1571

**Comment by Bokkiewokkie** [comment]
Issue related to #1781

**Comment by Karmic-Skink** [comment]
Do you happen to know exactly how long that ghost ship had been sitting there for?

**Comment by Karmic-Skink** [comment]
This should be resolved with latest push.
