### ISSUE TITLE
Pilots cannot hear fleet hails after entering and exiting fighter

### ISSUE THREAD

**Issue by someone543** [BeeStation/NSV13#1865]
## Reproduction:

1. Enter a fighter 
2. Get out and wait for the main ship to enter combat
3. Enter combat and see no hails in chat as well as fail to hear textdraw.wav.

**Comment by TheFakeElon** [comment]
The only clear case I could see this happening if is a player wasn't part of the overmaps `mobs_in_ship` list, but that's updated every time the player moves so even if there is a bug in fighter dismounting, it shouldn't cause this 🤔

**Comment by someone543** [comment]
Did a bit of testing and I think I found out what's causing the issue. 

> The only clear case I could see this happening if is a player wasn't part of the overmaps `mobs_in_ship` list, but that's updated every time the player moves so even if there is a bug in fighter dismounting, it shouldn't cause this 🤔

When a pilot enters a fighter, the fighter will remove the pilot from the NSVs `mobs_in_ship` list. When the pilot gets out of the fighter and moves, `update_overmap` will see that the pilot's `last_overmap` is the same as the NSV and because of that do nothing.
