### ISSUE TITLE
You can load the same NAC shell into two gates at once

### ISSUE THREAD

**Issue by checkraisefold** [BeeStation/NSV13#1907]
## Testmerges:
[#1797: 'More Sabre fixes' by covertcorvid at commit 160253c4ec](https://github.com/BeeStation/NSV13/pull/1797)
[#1829: 'Self Surgery' by BetaCentari at commit 3bc3af01d1](https://github.com/BeeStation/NSV13/pull/1829)
[#1861: 'Snake Class medium gunboat' by Vasily2013 at commit 6e19f69307](https://github.com/BeeStation/NSV13/pull/1861)
[#1840: 'Race Specific Emotes' by BetaCentari at commit 1d251a83e9](https://github.com/BeeStation/NSV13/pull/1840)
[#1886: 'Implements spatial partitioning for physics collision detection' by TheFakeElon at commit 16734bd044](https://github.com/BeeStation/NSV13/pull/1886)
[#1848: 'Notoriety (aka NSV - Pulsar edition)' by DeltaFire15 at commit 7cb261214c](https://github.com/BeeStation/NSV13/pull/1848)
[#1894: 'More multi-Z stuff' by covertcorvid at commit 7366b7acb0](https://github.com/BeeStation/NSV13/pull/1894)
[#1900: 'fixes same rank text on examine' by red031000 at commit 8fd807e949](https://github.com/BeeStation/NSV13/pull/1900)
[#1899: 'Fixes issues with the naked outfit' by red031000 at commit 36a1131d32](https://github.com/BeeStation/NSV13/pull/1899)
[#1883: 'Rise of the Alicorn' by QAI-07 at commit 4235f41008](https://github.com/BeeStation/NSV13/pull/1883)
[#1873: 'Fixes fighter forcemove bug' by TheFakeElon at commit c94fdd1ed4](https://github.com/BeeStation/NSV13/pull/1873)
[#1905: 'Updating department_radio_keys localization' by Archemagus at commit a00edd9383](https://github.com/BeeStation/NSV13/pull/1905)
[#1904: 'Improper noun fixing' by TheFakeElon at commit fbcbf849fe](https://github.com/BeeStation/NSV13/pull/1904)
[#1901: 'Fixes overmap and overmap-relayed piercing projectiles' by DeltaFire15 at commit 20b54b5a75](https://github.com/BeeStation/NSV13/pull/1901)
[#1871: 'Fixes volatility component' by TheFakeElon at commit eb775112e0](https://github.com/BeeStation/NSV13/pull/1871)

## Reproduction:
Cost-cutting measures have allowed us to use half the powder bags and shells! Simply load the same NAC shell into two payload gates at once with click and drag, then when you load 3 powder bags into each NAC they will both go to 175% shell powder content! Then, go to each console and feed the shell. You can now fire both NACs separately.

**Comment by Crus0** [comment]
This also works for moving shells and powder into ammo stackers. In addition, you can (if done quickly) load the same shell/powder a large number of times into the same stacker to duplicate it, but this seems to have inconsistent results.

**Comment by TheFakeElon** [comment]
mutli-gate drifting
