### ISSUE TITLE
Various shrike atmos issues

### ISSUE THREAD

**Issue by williamcll** [BeeStation/NSV13#1930]
## Reproduction:
Most ships and stations have a scrubber pipenet that is completely vaccum at the start of the round, however for some reason, the scrubbers on shrike would quickly be filled with normal air, to the point of clogging 
![image](https://user-images.githubusercontent.com/43061493/171235125-d76b2b3e-bbfe-4c05-bd37-5a94d43fe76d.png)
Also one reason that the clogging can't be dealt with: it is impossible to change some of the pipe settings without breaking into the air chamber.
![image](https://user-images.githubusercontent.com/43061493/171235465-76107dba-cfb6-419a-ac1f-8859b94ae123.png)
This applies to the gas fuel chamber as well.

**Comment by Bokkiewokkie** [comment]
Afaik this is actually cause the tank ID code is kinda busted
