### ISSUE TITLE
so for some reason, when i get into the gunner seat and observe the background, for some reason, i get O2 damage. i have not encountered this before today, just until now.

### ISSUE THREAD

**Issue by thebruhdude** [BeeStation/NSV13#1934]
## Reproduction: N/A (because i don't know how it happened)

so, it was a casual round on atlas, i was minding my own business, tried out the gunner seat in the gauss gunner room and tried to unload all ammo. then, out of a sudden, i  take O2 damage and get a O2 warning. this has not happened until right now, and i do not know how this happened, and that is why im not providing a reproduction instruction.

**Comment by covertcorvid** [comment]
How late in the round was this? The gauss guns have a fixed amount of air in them, so it may have run out.
