### ISSUE TITLE
Bot Pathfinding

### ISSUE THREAD

**Issue by Bobbanz1** [BeeStation/NSV13#1973]
## Testmerges:
Issue discovered due to the test merge of [#1956: 'AI Bot Control Fix' by Bobbanz1](https://github.com/BeeStation/NSV13/pull/1956)

## Reproduction:
Bots are unable to calculate a route, for pathfinding, in and out of a room which has a door currently blocked with directional fire doors. 
Issue is temporarily solved through manually forcing every bot to find a way into a nearby room that isn't being blocked by firelocks? through maintenance, which also has chance to return a failed attempt at pathfinding. 

Once the bots have found their way to this room then one can manually open the door and assuming the air alarms doesn't trigger, the bots can navigate through this open door into this previously blocked off area, however if the firelock closed infront of the bot then, assuming it still has the route in memory, it will continue through the firelocks and to its destination. 

However if the route wasn't calculate before the firelocks closed down, then it will result in the pathfinding attempt failing. 

The bots also seem confused by elevators such as on the Aetherwhisp, sometimes they fail to calculate a route out of the elevator despite there being nothing that's blocking their way. 

Sometimes they also fail to calculate a route in the elevator itself even if they're standing inside the elevator.

**Comment by Bobbanz1** [comment]
Currently looking at what it takes to upgrade the Jump Point Search system to tgstation’s latest version, so far simply copying over the changes they’ve done to the path file just results in the bots becoming idiots incapable of pathfinding unless the destination is within their line of sight

**Comment by Bobbanz1** [comment]
Right to divide this into more manageable parts
- [ ] Pathfinding through firedoors
Bots are unable to calculate a route, for pathfinding, in and out of a room which has a door currently blocked with directional fire doors.
Issue is temporarily solved through manually forcing every bot to find a way into a nearby room that isn't being blocked by firelocks? through maintenance, which also has chance to return a failed attempt at pathfinding.

Once the bots have found their way to this room then one can manually open the door and assuming the air alarms doesn't trigger, the bots can navigate through this open door into this previously blocked off area, however if the firelock closed infront of the bot then, assuming it still has the route in memory, it will continue through the firelocks and to its destination.

However if the route wasn't calculate before the firelocks closed down, then it will result in the pathfinding attempt failing.

**Comment by Bobbanz1** [comment]
- [ ] Pathfinding inside elevators

The bots also seem confused by elevators such as on the Aetherwhisp, sometimes they fail to calculate a route out of the elevator despite there being nothing that's blocking their way.

Sometimes they also fail to calculate a route in the elevator itself even if they're standing inside the elevator.

**Comment by Bobbanz1** [comment]
- [ ] Pathfinding around Railings

Pathfinding seems confused by the existance of railings, seemingly trying to go through them, attempting to make them a dense object to the pathfinder has resulted in it being unable to pathfind around a railing facing this direction -->

**Comment by Karmic-Skink** [comment]
> * [ ]  Pathfinding around Railings
> 
> Pathfinding seems confused by the existance of railings, seemingly trying to go through them, attempting to make them a dense object to the pathfinder has resulted in it being unable to pathfind around a railing facing this direction -->

Everything has an issue pathfinding with railings due to the nature of them essentially blocking movement from a tile that they aren't on in a consistent manner, and such the path finding never knows which side of the railing it is currently on in order to navigate it.

See KNPCs/players endlessly climbing on railing that just drops them back in the same place they currently are, rather than crossing.
