### ISSUE TITLE
Ammo sorter TGUI error

### ISSUE THREAD

**Issue by benbot16** [BeeStation/NSV13#1986]
## Round ID:
4567

## Testmerges:
#1972, #1924, #1954, #1969, #1958, #1956, #1911, #1967, #1980, #1974, #1981, #1985, #1982

## Reproduction:
1. Open ammo rack console
2. Sometimes get this error
![image](https://user-images.githubusercontent.com/9423435/178067606-8d4ba4e8-1896-48a5-ba3b-088f187550ca.png)

**Comment by Karmic-Skink** [comment]
#1981

**Comment by Ikalpo** [comment]
> #1981

the latest commit should fix this
