### ISSUE TITLE
Snake Cargo shuttle and cargo shuttle airlock doors cannot be accessed with service door remote

### ISSUE THREAD

**Issue by Kenionatus** [BeeStation/NSV13#1987]
## Round ID:
4578

## Testmerges:
[#1972: 'Makes chameleon clothing work for NSV clothes' by Bokkiewokkie at commit 37bdc84221](https://github.com/BeeStation/NSV13/pull/1972)
[#1924: 'Squads 3!' by covertcorvid at commit 743b01fc54](https://github.com/BeeStation/NSV13/pull/1924)
[#1954: 'Galactic Conquest fixes' by someone543 at commit 6e3442bbc7](https://github.com/BeeStation/NSV13/pull/1954)
[#1969: 'Adds rule reminders to revivals of various kinds.' by Absolutely-Steph at commit 4f841bd05b](https://github.com/BeeStation/NSV13/pull/1969)
[#1958: 'Ports making vended items go into your hands and refactors item giving, table slapping now included!' by Bobbanz1 at commit 32b910ac03](https://github.com/BeeStation/NSV13/pull/1958)
[#1956: 'AI Bot Control Fix' by Bobbanz1 at commit f4f2beb004](https://github.com/BeeStation/NSV13/pull/1956)
[#1911: 'Another felinid PR, This one is serious for a change, Adds TG tail sprites' by Absolutely-Steph at commit d69d07e05a](https://github.com/BeeStation/NSV13/pull/1911)
[#1967: 'Ports Cargo Beret, Quartermaster Turtleneck' by Bobbanz1 at commit 448a16f737](https://github.com/BeeStation/NSV13/pull/1967)
[#1974: '[PORT] Converts ai tracking towards using signals' by Bobbanz1 at commit 1fb42da90d](https://github.com/BeeStation/NSV13/pull/1974)
[#1981: 'Ammo sorter features' by Ikalpo at commit 6dc0735385](https://github.com/BeeStation/NSV13/pull/1981)
[#1985: 'Ports the Species specific mutations from Upstream' by Bobbanz1 at commit 0bfb5f038d](https://github.com/BeeStation/NSV13/pull/1985)
[#1982: 'Knpc pathfinding pass (and a bit of normal pathfinding)' by DeltaFire15 at commit 39f3fafa79](https://github.com/BeeStation/NSV13/pull/1982)

## Reproduction:
Try to set those airlocks to emergency access with service door remote.

**Comment by Bokkiewokkie** [comment]
The service door remote doesn't open supply doors, that's normal behaviour. Instead you would have to use the Quartermaster's supply remote.
