### ISSUE TITLE
HoS jacket can't actually hold security items

### ISSUE THREAD

**Issue by dinnerwoerror** [BeeStation/NSV13#199]
the head of security peacekeeper jacket (the coat that replaced the HoS's old armored trenchcoat) can't actually hold security items in its suit storage slot, things like the multiphase gun and stun batons and energy guns and other security items of the sort

this is somewhat solved by the fact that you still get the security overcoat and the head of security's greatcoat in the HoS locker, which do fit security items in the suit storage slot, but it would be a shame to see this fine sprite go to waste

**Comment by Vasily2013** [comment]
Not an issue. 
![image](https://user-images.githubusercontent.com/43328793/73564600-ec7c2f00-442d-11ea-8dac-255a51347d85.png)
