### ISSUE TITLE
No medal box on Eclipse

### ISSUE THREAD

**Issue by Kenionatus** [BeeStation/NSV13#1996]
## Testmerges:
Lots, but none that change the Eclipse, as far as I can tell.

## Reproduction:
Look in captain and XO's offices. No medal box.

**Comment by someone543** [comment]
There is in fact a medal box in the captain's office. It's right under the jetpack
![medal](https://user-images.githubusercontent.com/95106800/180587855-4ee088de-7791-4779-9275-7fc6d7c5d480.PNG)
![medal2](https://user-images.githubusercontent.com/95106800/180587857-a79ffbf9-8429-465d-82f3-948382ceaed3.PNG)
.

**Comment by Kenionatus** [comment]
Sorry
