### ISSUE TITLE
Every Fleet in one system and Ships stuck in space

### ISSUE THREAD

**Issue by Florbman** [BeeStation/NSV13#2000]
## Reproduction:

As a miner i went out to mine and spooled the FTL of the mining fighter. When it was fully spooled i pressed it to check if it was working (with the main ship in the same system). After a short lag after i pressed the button the overmap was filled with friendly ships on the left and hostile ships on the right in a non-moving constellation. (Art Gallery)
Also present where a bunch of stations, including two Czanek shipyards, donkco emporium etc. 
It seems likely all Fleets and stations in every system gets teleported.

![grafik](https://user-images.githubusercontent.com/53752299/180660013-5f7ad8ed-ac16-48d2-91a0-46c7d0d048a9.png)

**Comment by Bokkiewokkie** [comment]
We fixed this in #1994
