### ISSUE TITLE
Invisible grilles outside of engineering on the Atlas

### ISSUE THREAD

**Issue by DrSirKnight** [BeeStation/NSV13#2016]
Title

## Reproduction:
![Untitled](https://user-images.githubusercontent.com/54851612/184549662-700b54ce-625a-4bbf-ab3c-6a7797c7c274.png)
Go to the spot at the picture, there's invisible grilles there

**Comment by Karmic-Skink** [comment]
The 3D grilles were broken by a beebase a while back, that is likely the entity.
