### ISSUE TITLE
[Hammerhead] the odd placement of the weapons bay conveyor belt

### ISSUE THREAD

**Issue by dinnerwoerror** [BeeStation/NSV13#202]
the munitions bay conveyor belt kind of just cuts through the main hallway, which can become a bit of an issue when some random ass Private walks through it and ends up pushing a crate off that just so happened to be full of armor piercing torpedo warheads

**Comment by Vasily2013** [comment]
Due to the placement of munitions and cargo this will be hard to fix, and will potentially be revisited at a later date.

**Comment by Karmic-Skink** [comment]
#pancakeissues

**Comment by francinum** [comment]
Now that there's a way to cycle-lock shutters, the previous status quo of a lockdown across the hallway while active should be returned
