### ISSUE TITLE
Asteroids use the wrong entrypoints

### ISSUE THREAD

**Issue by Ikalpo** [BeeStation/NSV13#2021]
## Reproduction:
enter a bunch of asteroids with a sabre, eventually you'll end up in an unloaded area.
look at the asteroid's docking_points var and it will have multiple objs in the list
at least one of the landmark/dropship_entry/ objs will be outside the asteroid, where the sabre ended up.

this is where the offending landmarks are added to the list
https://github.com/BeeStation/NSV13/blob/c5c1151b711bf2e03a8991f3b1d1782f08377d53/nsv13/code/modules/overmap/boarding/interiors.dm#L155

**Comment by jzburda** [comment]
A lot of this seems to happen on non-ferrous asteroids. I thought I entered some kind of weird-ass maze until I kept getting booted out

**Comment by covertcorvid** [comment]
thanks for the detective work.
game, why make landmark outside of template? why?
