### ISSUE TITLE
Research Tier System

### ISSUE THREAD

**Issue by Bobbanz1** [BeeStation/NSV13#2028]
## Round ID:
Rounds since Beebase merge

## Reproduction:
How the tier system currently works on Beestation is the following: 

Research 3 Tier 2 nodes then one tier 1/0 node to jump to tier 2. 

Research 7 Tier 3 Nodes and then one tier 2/1/0 node to jump to tier 3, which requires you to already be on tier 2. 

Research 8 Tier 4 Nodes and one tier 3/2/1/0 node to jump to tier 4 from tier 3. 

Research 4 Tier 5 Nodes and then one tier 4/3/2/1/0 Node to jump to tier 5 from tier 4 after which you no longer need discovery points to unlock nodes. 

In total this requires 22000 discovery points to accomplish. 

How NSV’s broken version works is the following: 

Find and scan 2 Overmap anomalies, then do the following: 
1: Research Industrial Engineering.
2: Research Basic Bluespace Theory
3: Research 1 Random Tier 1/0 Research
4: Research Applied Bluespace Theory
5: Research Bluespace Travel
6: Research 1 Random Tier 1/2/3/0 Research Node. 

Following this, you’ll have jumped from tier 1 to tier 4 and then straight to tier 5, at which point discovery points are now useless as everything now only requires general research points which can easily be gotten faster by building more research servers.

**Comment by Karmic-Skink** [comment]
Can we just throw research into the burn pit?

**Comment by Bobbanz1** [comment]
I believe that was what certain individuals wanted to accomplish

**Comment by covertcorvid** [comment]
Pretty sure this bug is fixed upstream

**Comment by Bobbanz1** [comment]
> Pretty sure this bug is fixed upstream

It is fixed upstream, only problem is that we never got the fix when porting it

**Comment by Karmic-Skink** [comment]
Well we have another beebase soon, so we'll see what we get.

**Comment by Bobbanz1** [comment]
Issue has been resolved following the Beebase
