### ISSUE TITLE
AI Hail Hearing Issue

### ISSUE THREAD

**Issue by Bobbanz1** [BeeStation/NSV13#2032]
## Reproduction:
Play as the AI
Summon an enemy fleet
You will not hear the associated hail message that usually accompanies the start of combat. 
Only indicator that there is an ongoing combat at all is the fact that people will usually be screaming about it.

**Comment by Bobbanz1** [comment]
Borgs can hear the combat announcement though so if you’re in a shell, you’ll hear the announcement

**Comment by covertcorvid** [comment]
oh for fuck's sake
I know why this is actually
mobs_in_ship gets updated on Move()
you never move so you're not on the list
