### ISSUE TITLE
Ship getting hung up on borders 

### ISSUE THREAD

**Issue by Bridge-Lizard** [BeeStation/NSV13#2037]
## Testmerges:[#2008: 'Torp (and volatility component fixes, again, this time for real)' by DeltaFire15 at commit 2ec3a0db16](https://github.com/BeeStation/NSV13/pull/2008)
[#1983: '[READY] Bot Multi-Z Movement' by Bobbanz1 at commit b1fc0ec638](https://github.com/BeeStation/NSV13/pull/1983)
[#1917: '[MDB ignore] Staff Judge Advocate, a lore-friendly Lawyer replacement. Also rank overhaul in anticipation of SOP and Law overhaul(Lore/RP Overhaul part 1 of many.)' by Absolutely-Steph at commit a15618821a](https://github.com/BeeStation/NSV13/pull/1917)
[#2025: 'Fixes invisible bullets for Glocks and pulse rifles' by someone543 at commit 5efa2c5dd6](https://github.com/BeeStation/NSV13/pull/2025)
[#2024: 'New glocks for security' by TheScienceOfKSP at commit a630326d74](https://github.com/BeeStation/NSV13/pull/2024)
[#2022: 'Adds selling boarder gear for cash with cargo' by Bokkiewokkie at commit 4eda384ba8](https://github.com/BeeStation/NSV13/pull/2022)
[#2017: 'Puts the Fist of Sol back in the bag.' by QAI-07 at commit 82e9d85fb6](https://github.com/BeeStation/NSV13/pull/2017)
[#1965: 'Ports The Multi-Cell Charger' by Bobbanz1 at commit 61044d9a28](https://github.com/BeeStation/NSV13/pull/1965)
[#2034: 'Adds Ration Packs to Sustenance Vendors' by Kenionatus at commit 3715d1a312](https://github.com/BeeStation/NSV13/pull/2034)
[#2033: 'Glass Tiles and Reinforced version now have a material var so they can be recycled' by Bobbanz1 at commit aacf9ce6b8](https://github.com/BeeStation/NSV13/pull/2033)

**Comment by Bridge-Lizard** [comment]
The Tycoon is getting hung up on over map borders im unsure whats causing this

**Comment by Kenionatus** [comment]
In my piloting experience, this seems to be inversely correlated to the ship's speed. Getting hung op on the map border seems to happen more when slower and boosting "through it" is sometimes possible.

**Comment by Kenionatus** [comment]
Does Need Verification mean it needs a test case? Because it happens (almost?) all the time for me when flying the Tycoon and I've seen it happen to other pilots a lot too.

**Comment by Kenionatus** [comment]
Video of it at current master (aa16f8d90c8a4162f0480fa04ccf2c4cbfe0c13b) running on BYOND version 514.1583:
https://youtu.be/9D_SxquiltM

**Comment by Kenionatus** [comment]
@covertcorvid Does this still need the "Needs Reproduction Steps" label?
