### ISSUE TITLE
Turnstiles can be destroyed by cultivators, such as those found in permabrig.

### ISSUE THREAD

**Issue by Terra1** [BeeStation/NSV13#2061]
## Round ID:

Rounds since turnstile merge.

## Testmerges:

https://github.com/BeeStation/NSV13/pull/2022
https://github.com/BeeStation/NSV13/pull/1814
https://github.com/BeeStation/NSV13/pull/2024
https://github.com/BeeStation/NSV13/pull/2017
https://github.com/BeeStation/NSV13/pull/2035
https://github.com/BeeStation/NSV13/pull/1965
https://github.com/BeeStation/NSV13/pull/2039
https://github.com/BeeStation/NSV13/pull/2054
https://github.com/BeeStation/NSV13/pull/2053

## Reproduction:

Be in the permabrig. Grab a cultivator. Start attacking the turnstiles in permabrig, then examine them - it will show damage. Keep attacking them until they break, allowing you to stroll on out of permabrig.

**Comment by covertcorvid** [comment]
You can eventually break doors too, but they'll electrocute you. It might make sense to have turnstiles do the same since they are electronic.
We should also check that there's a way to build one...
