### ISSUE TITLE
Shutter buttons inside cargo shuttles permanently stop working after some trips to centcom

### ISSUE THREAD

**Issue by Kenionatus** [BeeStation/NSV13#2065]
Version: at commit a2397cd18f2e4275a27ba9649f3278035ebed1a5

## Reproduction:
Call cargo shuttle. Press one shutter button twice. Send cargo shuttle back. Call shuttle again. Press the same button twice. Repeat until shutters stop opening and closing. Send cargo shuttle back and call it again. press button twice. Repeat until satisfied.

## Observed Behaviour:
Shutters work two times (two shuttle calls), but permanently stop working afterwards. That process only starts when the shutter button has been used. They continue to be not work for the rest of the round. If you view the button's variables, you will notice that the shutters stop working when the button's `device` variable gets set to `null`.

Addition: Buttons situated on the main ship don't appear to break, which is why it only really impacts gameplay on the Tycoon, which doesn't have any ship side buttons for the shuttle shutters (afaik).

## Expected Behaviour:
Pressing the button should always open the shutter as long as there is power and it wasn't manipulated in other ways.

**Comment by Bobbanz1** [comment]
Addendum: 
From what I can remember from the old days, one possible trigger for this issue was when someone used a screwdriver on the doors, merely opening and closing the button cover, this would trigger this issue, from what I can remember.

**Comment by Karmic-Skink** [comment]
Specify which maps you mean, as this tends to be a mapping issue that can be resolved by moving a few things around.

**Comment by Kenionatus** [comment]
@Karmic-Skink If you're asking me, I wrote "it only really impacts gameplay on the Tycoon" in the issue text.

**Comment by Karmic-Skink** [comment]
Blind

**Comment by Kenionatus** [comment]
NP, happens to everyone from time to time.
