### ISSUE TITLE
Moving up/down Z-levels while in fighter ejects while allowing you to still control the fighter

### ISSUE THREAD

**Issue by Derpguy3** [BeeStation/NSV13#2076]
## Testmerges: 
[#2053: 'Allows subjects of the dominion to speak to eachother' by Pontenerd at commit d4465e74be](https://github.com/BeeStation/NSV13/pull/2053)
[#2054: 'add MAA stamp' by Kenionatus at commit 097fce6caa](https://github.com/BeeStation/NSV13/pull/2054)
[#2059: 'Alters the Oozelings Last Name Generator' by Bobbanz1 at commit 34256186de](https://github.com/BeeStation/NSV13/pull/2059)
[#2035: 'Portable Gulag' by TheScienceOfKSP at commit 9e93b1b114](https://github.com/BeeStation/NSV13/pull/2035)
[#2063: 'Probably fixes some stuff about dynamic map entrypoints' by covertcorvid at commit ab8f9171db](https://github.com/BeeStation/NSV13/pull/2063)
[#2073: 'Ghost ships can now hear hails' by someone543 at commit ba03457cfc](https://github.com/BeeStation/NSV13/pull/2073)
[#2072: 'Fixes fighter fueling at any distance' by someone543 at commit a2ecbe1254](https://github.com/BeeStation/NSV13/pull/2072)
[#2070: 'Fixes that shuttle shutter button issue' by Bobbanz1 at commit 7674811d00](https://github.com/BeeStation/NSV13/pull/2070)
[#2069: 'Stormdrive overload numbers tweak' by Karmic-Skink at commit ae91c83394](https://github.com/BeeStation/NSV13/pull/2069)
[#2017: 'Puts the Fist of Sol back in the bag.' by QAI-07 at commit 32f4791cde](https://github.com/BeeStation/NSV13/pull/2017)
[#1997: 'Makes all of the NSV floor tiles one type of durasteel tile' by Bokkiewokkie at commit a7681715cc](https://github.com/BeeStation/NSV13/pull/1997)

## Reproduction:
While controling a fighter, pressing the move up/down button in the IC tab boots your character out of the fighter, yet retains your control over the fighter along with screen zoom. You cannot however, exit the fighter's camera unless you already had the canopy open, as it seemed to prevent accessing ship controls.

**Comment by TheFakeElon** [comment]
Piloting as a ghost?

**Comment by Derpguy3** [comment]
Occurred while I was still alive. Thought I was able to move fighters up and down between Z-levels using the move up/down and it ended up moving my character out of the fighter and down a Z-level.
