### ISSUE TITLE
ship bug

### ISSUE THREAD

**Issue by SpaceNarin** [BeeStation/NSV13#209]
I'm not really sure what the round number was but, when you click the "rename ship" button and decide to not change the name of the ship and click cancel it will still set the name and if there is no name in the tab it is invisible. According to an admin I asked about the problem, because it is invisible The ship verb menu doesn't appear
this is my first bug report so sorry if I'm not in the right format

**Comment by covertcorvid** [comment]
Did #213 fix this?

**Comment by SpaceNarin** [comment]
I'll need to test it during the next testing period I missed the last ones.

**Comment by Kmc2000** [comment]
resolved by #213
