### ISSUE TITLE
Shrike ammo sorters has excess railgun slugs

### ISSUE THREAD

**Issue by someone543** [BeeStation/NSV13#2122]
## Round ID: N/A 
Local tested on master

## Testmerges: N/A
Reproduced on master

## Reproduction:
The ammo sorters on the Shrike has more railgun slugs than it can hold, leading to the extra slugs being stacked ontop of the sorter
1. Be on the Shrike
2. Look at the ammo sorters
![AmmoSorterSlug](https://user-images.githubusercontent.com/95106800/198464194-55de19e3-0991-43bc-891d-7b28af9e76c8.PNG)

**Comment by Karmic-Skink** [comment]
I'm pretty sure those racks are var edited to hold 20 items and have 20 slugs placed on them.
Well they were anyway.

**Comment by Bokkiewokkie** [comment]
Turns out they can jam while loading in 🙃

**Comment by someone543** [comment]
> I'm pretty sure those racks are var edited to hold 20 items and have 20 slugs placed on them. Well they were anyway.

I examined the ammo sorters. It said they could only hold 12 slugs.

**Comment by Karmic-Skink** [comment]
> > I'm pretty sure those racks are var edited to hold 20 items and have 20 slugs placed on them. Well they were anyway.
> 
> I examined the ammo sorters. It said they could only hold 12 slugs. ![AmmoSorterSlug2](https://user-images.githubusercontent.com/95106800/198551700-b474b9d5-d26f-4ca5-b279-74618e9ad9cc.PNG)

Likely were broken when people messed with ammo sorters then, as they 100% worked when map was made.
