### ISSUE TITLE
bots stuck during patrol on tycoon

### ISSUE THREAD

**Issue by red031000** [BeeStation/NSV13#2178]
## Round ID:

5244

## Testmerges:

[#2085: 'Starmap V and a visit from an old friend!' by Bokkiewokkie at commit 9101517cd3](https://github.com/BeeStation/NSV13/pull/2085)
[#2096: 'Fixes the boarding objective' by covertcorvid at commit 096c0c7238](https://github.com/BeeStation/NSV13/pull/2096)
[#2103: 'Adding More Banners' by BetaCentari at commit 316e421f3d](https://github.com/BeeStation/NSV13/pull/2103)
[#2120: 'Cheers!' by bluewasabi24 at commit ae283ea408](https://github.com/BeeStation/NSV13/pull/2120)
[#2123: 'RCD constructed airlocks will now use NSV icons' by someone543 at commit 8ef162d3d1](https://github.com/BeeStation/NSV13/pull/2123)
[#2068: 'The blast shower: an abrasive solution to radioactive contamination' by covertcorvid at commit 60837d2a28](https://github.com/BeeStation/NSV13/pull/2068)
[#2133: 'Basepixels and Pixelshifting' by BetaCentari at commit 9c0d22b291](https://github.com/BeeStation/NSV13/pull/2133)
[#2135: 'Snake Atmos Plasma Routing Change' by Vasily2013 at commit f93228e909](https://github.com/BeeStation/NSV13/pull/2135)
[#2053: 'Allows subjects of the dominion to speak to eachother' by Pontenerd at commit 1ce8c79344](https://github.com/BeeStation/NSV13/pull/2053)
[#2157: 'Fixes some logout runtimes' by covertcorvid at commit d864ea278e](https://github.com/BeeStation/NSV13/pull/2157)
[#2163: 'Fixes some chairs being able to be picked up' by benbot16 at commit 8b58a16932](https://github.com/BeeStation/NSV13/pull/2163)
[#2164: 'Tweaks astrometrics scans' by benbot16 at commit 7b1745fdd1](https://github.com/BeeStation/NSV13/pull/2164)
[#2175: 'Fixes pilots being unable to hear hails' by someone543 at commit 76282c804a](https://github.com/BeeStation/NSV13/pull/2175)
[#2172: 'Executive Officer Stamp' by bluewasabi24 at commit eafa69edd7](https://github.com/BeeStation/NSV13/pull/2172)
[#2171: 'Reduce Crew Monitor Update Time' by bluewasabi24 at commit 3b3746673a](https://github.com/BeeStation/NSV13/pull/2171)
[#2162: 'Post-Beebase Shrike Update' by Karmic-Skink at commit 3b86d0ce8d](https://github.com/BeeStation/NSV13/pull/2162)
[#2129: 'Adds Highjack, a new drug for IPC's!' by Pontenerd at commit 5debcc14a0](https://github.com/BeeStation/NSV13/pull/2129)
[#2018: 'Fixes invisible grilles' by someone543 at commit 02270605f8](https://github.com/BeeStation/NSV13/pull/2018)
[#2116: 'Tweaks ammo sorter repairs and fighter armor repairs' by benbot16 at commit 034042e286](https://github.com/BeeStation/NSV13/pull/2116)
[#2167: 'Bulk Torpedo/Missile Crates' by BetaCentari at commit 10c3b8c51c](https://github.com/BeeStation/NSV13/pull/2167)
[#2170: '[PORT] Custom say emotes and Emphasis' by Bobbanz1 at commit 66cdc90887](https://github.com/BeeStation/NSV13/pull/2170)

## Reproduction:

set bot to patrol mode and see them get stuck here, always

![image](https://user-images.githubusercontent.com/13968885/201446272-3780d2c7-8fb3-44a1-97f7-761b6b2477d1.png)

**Comment by Karmic-Skink** [comment]
Resolved by forcing them to restart patrol ingame.

**Comment by Bobbanz1** [comment]
Managed to replicate this behavior, working on figuring out how to fix it.

**Comment by Bobbanz1** [comment]
From what I can gather. 

I never considered the possibility that the bots might somehow fail to use a bot elevator, as such they're getting stuck in a loop of trying to find the bot elevator on the current tile, which in this scenario, doesn't actually exist at all, so they're now stuck trying to find their elevator which doesn't exist, and failing to do so, which results in them looping around in the code, trying to use the ladder they can't reach.

**Comment by Bobbanz1** [comment]
Never mind that's not what's happening either...
