### ISSUE TITLE
[Hammerhead] Hangar does not have a lore console

### ISSUE THREAD

**Issue by ta3370** [BeeStation/NSV13#218]
Hammerhead hangar does not contain a lore console required for fighter repair and maintenance tutorial .txt, I don't remember if the Weapons Bay has one either.

**Comment by CoreFlare** [comment]
This is false. The seegson terminal is located inside of the storage room for the munitions trolleys and the two thermonuclear warheads, next to the ship viewer.

**Comment by CoreFlare** [comment]
[Example](https://i.imgur.com/zSJHbAb.png)

**Comment by GoatMonarch** [comment]
CoreFlare is correct, but I too noticed a certain lack of them. I'd advice to implement ones in the flight control rooms, and some place in the central hangar.

**Comment by francinum** [comment]
These are planned to be refactored in the future, and honestly should probably be viewed through something that isn't static.
