### ISSUE TITLE
Munitions Trolley holds too many torps

### ISSUE THREAD

**Issue by ta3370** [BeeStation/NSV13#219]
I personally feel that the Munitions Trolley's current ability to hold about 6 or more torpedoes is too much, since it's meant to be a large bulky item that gets transported more gradually, I think the trolley should only hold 2-3 torpedoes at a time.

**Comment by Corsaka** [comment]
It can only hold four.

**Comment by Vasily2013** [comment]
![image](https://user-images.githubusercontent.com/43328793/73565073-d7ec6680-442e-11ea-9a3e-fae98f3b0c49.png)
can confirm, only holds 4.
