### ISSUE TITLE
[Snake] Snake does not support KNPC or nukeops spawns

### ISSUE THREAD

**Issue by covertcorvid** [BeeStation/NSV13#2207]
## Round ID:

5326

## Testmerges:

https://github.com/BeeStation/NSV13/pull/2068
https://github.com/BeeStation/NSV13/pull/2133
https://github.com/BeeStation/NSV13/pull/2053
https://github.com/BeeStation/NSV13/pull/2157
https://github.com/BeeStation/NSV13/pull/2164
https://github.com/BeeStation/NSV13/pull/2175
https://github.com/BeeStation/NSV13/pull/2162
https://github.com/BeeStation/NSV13/pull/2116
https://github.com/BeeStation/NSV13/pull/2170
https://github.com/BeeStation/NSV13/pull/2030
https://github.com/BeeStation/NSV13/pull/2023
https://github.com/BeeStation/NSV13/pull/2136
https://github.com/BeeStation/NSV13/pull/2199
https://github.com/BeeStation/NSV13/pull/2203
https://github.com/BeeStation/NSV13/pull/2192
https://github.com/BeeStation/NSV13/pull/2189
https://github.com/BeeStation/NSV13/pull/2182
https://github.com/BeeStation/NSV13/pull/2197

## Reproduction:

Have KNPCs or a nuclear operative spawn trigger. The spawn is aborted. I don't know what spawner is needed for the nukeop, but the KNPCs need patrol nodes.

**Comment by Kenionatus** [comment]
Related to now closed #1964?
