### ISSUE TITLE
Slicing cheese is borked

### ISSUE THREAD

**Issue by benbot16** [BeeStation/NSV13#2238]
## Round ID:
5457

## Testmerges:
![image](https://user-images.githubusercontent.com/9423435/208325179-23aeba27-fe3e-478a-aa1d-71cb6e2857a3.png)

## Reproduction:
1. Place cheese down
2. try to slice cheese
3. cheese does not slice

**Comment by Bobbanz1** [comment]
Probably related to 
* https://github.com/BeeStation/NSV13/pull/2210

**Comment by Bokkiewokkie** [comment]
> Probably related to
> 
>     * [makes all food forkable #2210](https://github.com/BeeStation/NSV13/pull/2210)

Yep, fixed now
