### ISSUE TITLE
Railguns on the Shrike do not fire

### ISSUE THREAD

**Issue by bluewasabi24** [BeeStation/NSV13#2244]
## Round ID & Round Date: 
Round 5488 
Reporting client version: 514.1583

## Testmerges: 
#2053 
#2094 
#2211 
#2225 
#2221 
#2229 
#2227 
#2236 
#2240 
#2234 
#2233 
#2230 
#2237 
#2239 
#2210 

## Reproduction:

- Load the railguns as you would (load ammo, load, chamber, disable safeties)
- Procure your TAC console
- Switch to the railguns
- Click anywhere on the overmap
- Receive clicky noises, but no fire

Attempted Troubleshooting Steps:
- Switched to shells and back to see if we could fire with the NAC shells. We could not.
- Armed and disarmed the NAC shells to see if those would fire. They did not. 
- Attempted to disassemble the guns to see if rebuilding would fix it. Fun fact, it just disappears if you try and break it (whoops)

Important Notes:
- They had plenty of power; condition and calibration were at 100. 
- We did move the TAC console to muni. We did not see if the railguns fired before we moved the TAC.

**Comment by Karmic-Skink** [comment]
I may have forgotten to add a board into the code.

**Comment by Karmic-Skink** [comment]
Please post here if you get this again in a different round, and it wasn't just a Byond moment for a round.

**Comment by someone543** [comment]
Tested again in another round. Railguns still don't want to fire
