### ISSUE TITLE
Atmos backpack extinguisher doesn't propel in space.

### ISSUE THREAD

**Issue by CoreFlare** [BeeStation/NSV13#227]
## Issue
The atmospherics firefighting backpack is an item in atmospherics that uses an internal water supply to spray super cooled water like a fire extinguisher, shoot a blob of resin that explodes like metal foam, or spray single-tile resin for fine-tuning hull breaches.

The fire extinguisher items are able to propel you in space. If you spray one direction, you will be launched in the other.

The atmospherics backpack extinguisher doesn't work like this. You won't move trajectory or change momentum at all if you fire the extinguisher nozzle on extinguisher mode.

**Comment by Vasily2013** [comment]
Not an issue. Water from the backpack will change your velocity vector.
