### ISSUE TITLE
Biomatter and Biogenerator broken

### ISSUE THREAD

**Issue by Karpet12** [BeeStation/NSV13#2325]
## Testmerges:
[#2234: 'Make turnstiles shock when broken and make them repairable' by Kenionatus at commit 7af1daab32](https://github.com/BeeStation/NSV13/pull/2234)
[#2194: '[PORT] RPED Quality of Life Stuff' by Bobbanz1 at commit 4999fdc5a8](https://github.com/BeeStation/NSV13/pull/2194)
[#2136: 'Gladius Rework' by BetaCentari at commit 8c0ad404fb](https://github.com/BeeStation/NSV13/pull/2136)
[#2132: 'DLV Serendipity' by BetaCentari at commit 401b6adeac](https://github.com/BeeStation/NSV13/pull/2132)
[#2228: 'Targeting Overhaul' by benbot16 at commit c60ff496fc](https://github.com/BeeStation/NSV13/pull/2228)
[#2290: 'Tweaks KNPC initial detection range' by covertcorvid at commit c5756e4bb9](https://github.com/BeeStation/NSV13/pull/2290)
[#2286: 'Aetherwhisp Touchups' by BetaCentari at commit f9feecb2ea](https://github.com/BeeStation/NSV13/pull/2286)
[#2312: '[Upstream] The Snoot-ening, separates HIDEMASK and HIDESNOUT' by Bobbanz1 at commit 191195bfcb](https://github.com/BeeStation/NSV13/pull/2312)
[#2281: '[PORT] Holomaps' by Bobbanz1 at commit 5258808dc5](https://github.com/BeeStation/NSV13/pull/2281)
[#2317: 'Fixes EWAR consoles making infinite radios' by benbot16 at commit 699c2257af](https://github.com/BeeStation/NSV13/pull/2317)
[#2318: 'Fixes APC icon states and overlays not applying' by TaG2e at commit fd706a96fa](https://github.com/BeeStation/NSV13/pull/2318)
[#2322: 'Removes the annoying warning signs that show up in Visual Studio Code' by Bobbanz1 at commit 2729701ae6](https://github.com/BeeStation/NSV13/pull/2322)
[#2303: '[UPSTREAM] The Cats Sound Service' by Bobbanz1 at commit a918766c6c](https://github.com/BeeStation/NSV13/pull/2303)
[#2304: '[UPSTREAM] Orbit panel job icons' by Bobbanz1 at commit 68c4b02074](https://github.com/BeeStation/NSV13/pull/2304)
[#2305: '[UPSTREAM] Xeno-Artifact Updates' by Bobbanz1 at commit c4dce02f44](https://github.com/BeeStation/NSV13/pull/2305)

## Reproduction:
Attempt to use any plant on biogenerator or serendipity replicator
(Issue might only happen on the serendipity)

**Comment by Bokkiewokkie** [comment]
@BetaCentari Looks like it's from the dip

**Comment by Bobbanz1** [comment]
I'll take a look seeing as I ported the damn thing

**Comment by Bobbanz1** [comment]
Should be fixed with the latest commit to the dipper @Bokkiewokkie
