### ISSUE TITLE
Tiles "remember" items dropped on them + can't click items on floor + general overlay fuckery?

### ISSUE THREAD

**Issue by Sikroth** [BeeStation/NSV13#234]
Issue reported from  Round ID: 63 (NSV 13 | Official | "MRP" | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1505

![image](https://user-images.githubusercontent.com/7857084/71785235-80103a80-2ffd-11ea-8161-e98e9d1c6193.png)

The tile only had a syringe when this was screenshot but those items were on it before.

Trying to click anything on the tile counts as interacting with the floor. You have to alt+click to be able to interact with anything

Edit: Some sort of bug affecting overlayed stuff. Hit anything with an object, and the ghost sprite that shows to indicate the attack gets permanently stuck. Pictured me hitting myself and windows with a cardboard:

![image](https://user-images.githubusercontent.com/7857084/71785436-bea6f480-2fff-11ea-9b2e-10f184ff2c2a.png)

**Comment by Sikroth** [comment]
Overlays in general seem to be fucked. Attack something and the small transparent sprite of the weapon stays on it forever

**Comment by Sikroth** [comment]
Seemed to only happen during the first test of today for the record

**Comment by francinum** [comment]
Higgs Bugson related to timer subsystem sometimes dying for no good reason. Not much we can do about it.
