### ISSUE TITLE
Intergrated Tactical Console TGUI showing armour quadrant field on craft that do not have armour quadrants.

### ISSUE THREAD

**Issue by someone543** [BeeStation/NSV13#2409]
## Round ID: N/A
Local tested

## Testmerges: N/A
Local tested

## Reproduction:
Using a tactical console while in a utility fighter/dropship will show the armor quadrants to be displayed as NaN%.

This also happens when using a ghost ship fighter. 
1. Get in a Sabre/Dropship/GhostShipFighter
2. Use the TAC console
3. Look at armor

![GhostFighterArmorBug](https://user-images.githubusercontent.com/95106800/235146113-f9bba92b-46ff-4cf0-80d8-0f7e20bf39ca.PNG)

**Comment by Karmic-Skink** [comment]
Sabres do not have armour quadrants.
