### ISSUE TITLE
Exiting tugs moves camera one tile off centre

### ISSUE THREAD

**Issue by someone543** [BeeStation/NSV13#2449]
Issue reported from  Round ID: 6340 (NSV 13 | Official | MRP | 98% Free Lag | Spaceship Combat Server)

Reporting client version: 514.1589

**Comment by Bobbanz1** [comment]
I've taken a look at this and I'm unable to replicate it....wait what the fuck

![image](https://github.com/BeeStation/NSV13/assets/59128051/2bb463e0-4ee7-48b8-bb76-050924da54b2)
