### ISSUE TITLE
Fighters inside of main ship can't hear encounter hails

### ISSUE THREAD

**Issue by someone543** [BeeStation/NSV13#2456]
## Round ID: N/A
Local tested

## Testmerges: N/A
Tested on master

## Reproduction:
While pilots are in fighters inside of the ship, they cannot hear hails directed to the main ship, such as ones from Syndicate and Pirate fleets when encountered. 
1. Get in a fighter while inside the NSV
2. Have the main ship enter combat
3. Fail to hear the hail from the hostile fleet

**Comment by Karmic-Skink** [comment]
Not exactly a bug, more a feature of how hailing actually works.

Expect this to be resolved in a different manner.

**Comment by someone543** [comment]
Sorry, should have been more specific. I was referring to how fighters INSIDE of the main ship can't hear hails. It makes it a bit hard to tell exactly when we enter combat.

**Comment by Karmic-Skink** [comment]
> Sorry, should have been more specific. I was referring to how fighters INSIDE of the main ship can't hear hails. It makes it a bit hard to tell exactly when we enter combat.

Again, with how the hailing works, this is expected as carbon inside the fighter is not considered to be inside the ship that is being hailed.

We'll be addressing this is a different manner in future.
