### ISSUE TITLE
Invisa-Borgs

### ISSUE THREAD

**Issue by Crus0** [BeeStation/NSV13#2465]
## Round ID: 
6400

## Reproduction:
 It is possible to make cyborgs invisible.
 To do so: 
1. Choose cargo module 
2. Have your internal wires cut and mended
3. The cyborg will now be invisible 
4. RP as a poltergeist. 

Notes: Roomba style cargo-borg sprite chosen, recutting wires does not have any effect. The cyborg's panel, when opened, is visible. Hats, when thrown onto the borg, are also visible.

**Comment by Karmic-Skink** [comment]
#2427

**Comment by Bobbanz1** [comment]
> #2427 @Bobbanz1 Get on that please.

Should be fixed now
