### ISSUE TITLE
Ju Jitsu permanent slowdown issue

### ISSUE THREAD

**Issue by BlueHNT** [BeeStation/NSV13#2485]
Issue reported from  Round ID: 6487 (NSV 13 | Official | MRP | 98% Free Lag | Spaceship Combat Server)

Reporting client version: 514.1589
Active test merges: (IRRELEVANT)
[#2400: 'Enables Byond 515' by covertcorvid at commit 38f61a1394](https://github.com/BeeStation/NSV13/pull/2400)
[#2411: 'Updates client versions' by covertcorvid at commit c531cae54a](https://github.com/BeeStation/NSV13/pull/2411)
[#2445: 'Fixes holomap dels' by Bokkiewokkie at commit a0a2c06272](https://github.com/BeeStation/NSV13/pull/2445)
[#2447: 'AMS shot counter' by covertcorvid at commit e56882db62](https://github.com/BeeStation/NSV13/pull/2447)
[#2461: 'Fix the HomeOne' by SerynEngi at commit 460ddabb3b](https://github.com/BeeStation/NSV13/pull/2461)
[#2459: 'Personal Armor Bullet/Laser rebalance' by SerynEngi at commit 902859a8b3](https://github.com/BeeStation/NSV13/pull/2459)
[#2453: '[PORT] Gives foxes a walking animation' by Bobbanz1 at commit 8db23484c4](https://github.com/BeeStation/NSV13/pull/2453)
[#2427: '[PORT] Cargo and Cyborg Munitions Upgrade' by Bobbanz1 at commit 35b5a8f00a](https://github.com/BeeStation/NSV13/pull/2427)
[#2467: 'Fixes squad manager download and run permissions' by covertcorvid at commit 6c6277cc0d](https://github.com/BeeStation/NSV13/pull/2467)
[#2466: 'Makes latejoins wake up from cryostasis instead of arriving on a shuttle' by covertcorvid at commit 33b9f401a5](https://github.com/BeeStation/NSV13/pull/2466)
[#2472: 'Coffee typo fix' by BlueHNT at commit 02000e53ea](https://github.com/BeeStation/NSV13/pull/2472)
[#2473: 'Adds the black skirt and maid outfit to the torp shop' by DrSirKnight at commit 182e93c4aa](https://github.com/BeeStation/NSV13/pull/2473)
[#2469: 'Tycoon Request Consoles and Stormdrive Fix' by SerynEngi at commit 2370a369e5](https://github.com/BeeStation/NSV13/pull/2469)
[#2387: 'Hammerhead Atmos and Hangar Rebuild' by SerynEngi at commit 545dad7fe3](https://github.com/BeeStation/NSV13/pull/2387)
[#2274: '[PORT] Flavor Roleplaying Overhaul' by Bobbanz1 at commit 88f6bb36cb](https://github.com/BeeStation/NSV13/pull/2274)
[#2482: 'Replaces wardens energy gun' by BlueHNT at commit d1b20dee32](https://github.com/BeeStation/NSV13/pull/2482)
[#2478: 'Fixes the "Prisoner Management Console" circuitboard' by BlueHNT at commit 562cdb9af8](https://github.com/BeeStation/NSV13/pull/2478)
[#2474: '[Modular] Coffee Addictions' by Bobbanz1 at commit cdc96c01ff](https://github.com/BeeStation/NSV13/pull/2474)
[#2480: 'Fixes related to syndicate maid clothes and accessories, adds the syndicate maid kit as a 20 TC uplink item' by DrSirKnight at commit 9b2b059efb](https://github.com/BeeStation/NSV13/pull/2480)

While being knocked down by some kind of semi-stun like pepper spray or being pushed against the wall, you can still ju-jitsu someone with 2 disarm and it causes you to get a permanent slowdown until you aggressively grab someone or ju-jitsu someone again.

It is annoying and tedious to remove and can have a big effect on the outcome of a fight due to the huge spacelike movement slowdown.

**Comment by BlueHNT** [comment]
Fixed in the ju jitsu update reference

**Comment by Bokkiewokkie** [comment]
@BlueHNT Please don't put it in the commit but in the actual PR description next time
