### ISSUE TITLE
Sephora won't fit through it's own boarding tube

### ISSUE THREAD

**Issue by SpagootyEggant** [BeeStation/NSV13#2578]
## Reproduction: 
Take your Sephora full of boarders, and realize that you need to decon a wall to the top right of the Sephora (and I think one at the top left) to get it to move from the starting location.
Bring your Sephora to the launch tube, where you will need to deconstruct a row of walls to fit into said launch tube.
Perhaps it actually DOES fit, but if it does, then it requires a lot of finesse. I think the tube has to be expanded to be one wider for the Sephora to fit smoothly.

**Comment by Bokkiewokkie** [comment]
Small craft hitbox jank my beloathed
