### ISSUE TITLE
MaA bugs round 1

### ISSUE THREAD

**Issue by ta3370** [BeeStation/NSV13#258]
## Round ID:
67

## Testmerges:
Munitions Department (Pucegang)

## Reproduction:
Join as MaA, attempt to do your job.

## Issue:
MaA does not have Command or ATC radio
MaA does not have munitions crate access
MaA does not get a PDA
It may be a good idea to add a munitions budget card

**Comment by ta3370** [comment]
Further info on the Radio aspect: Desc has the ":c for command :y for ATC" but the actual channel list does not, nor does the menu of the radio, and the radio can neither hear nor send to these channels.

**Comment by Karmic-Skink** [comment]
I typo'd the key it started with.
