### ISSUE TITLE
Munitions Tech - Possible dupe bug and some QoL things

### ISSUE THREAD

**Issue by redztarLenin** [BeeStation/NSV13#260]
Might have found a dupe bug, If you fill the munitions trolley with two torpedoes, unload them between two torpedo tubes and drag the same torpedo to both tubes they will register as filled and be loadable while theres still one torpedo left on the ground. They werent fired after that so i dont know, one might be empty but register as loaded but it could be worth looking into.

Also munitions techs dont have access to open the crates containing torpedo components, warheads, casings, railgun ammo and the rest of the relevant crates.

Also also, since MTs get bomb suits, which feels fitting it might be worth noting that they cant completly assemble the torpedoes without taking off the helmet to put on a welding mask. Its not really an issue but if I was working with welding on armed torpedoes and had a bomb suit to protect me a bit I would prefer not having to take the helm off when I use a flame near the explosive.

**Comment by Karmic-Skink** [comment]
The first part was already posted in issue #212 .

The second part has already been fixed and merged.

Third part is thematic.

**Comment by redztarLenin** [comment]
Ah, must have missed that when I checked for it, yes third part was only thematic.

**Comment by ta3370** [comment]
Third part can be solved by finding welding goggles
