### ISSUE TITLE
Viper fighter has passenger popup despite not having a passenger slot.

### ISSUE THREAD

**Issue by ta3370** [BeeStation/NSV13#261]
## Round ID:
67
## Testmerges:
Munitions Department
## Reproduction:
Attempting to click a viper (small fighter) to enter it.
## Issue:
Viper has a passenger button popup despite being a single seat fighter.

**Comment by Plotron** [comment]
That thing almost got me killed. That button does nothing, of course.

**Comment by Vasily2013** [comment]
verified

**Comment by Kmc2000** [comment]
Resolved in fighter vibecheck (to my knowledge)
