### ISSUE TITLE
Borg munitions upgrade duplicates gunpowder

### ISSUE THREAD

**Issue by Ikalpo** [BeeStation/NSV13#2616]
you can grab one gunpowder and insert it into multiple gates at once. This counts as multiple gunpowder when packing a shell.
you can also do this with PDC, but it doesn't actually add any ammo.

**Comment by Crus0** [comment]
To add on this, you can still duplicate shells and powder by quickly and repetitively click-dragging them into an ammo stacker. 

There was a previous fix which prevented this from being done with the shell chamber, but it did not fix the ammo stackers.

**Comment by Bobbanz1** [comment]
Fuck, right seeing as I added the damn thing I'll look into it to try and make it not possible to duplicate powder using the borg munitions upgrade
