### ISSUE TITLE
Can't pick up PDC bullets with PDC ammo container

### ISSUE THREAD

**Issue by Corsaka** [BeeStation/NSV13#263]
The PDC ammo container cannot pick up any PDC bullets after flicking them out of the magazine, claiming "You fail to collect anything!"

It's also impossible to see how many bullets are left in a PDC magazine and that'd be nice to have.

**Comment by Vasily2013** [comment]
verrified

**Comment by Vasily2013** [comment]
Verrified again and confirmed that it is also a problem with flak rounds
