### ISSUE TITLE
Munitions control computer opens unnecessarily

### ISSUE THREAD

**Issue by Corsaka** [BeeStation/NSV13#264]
Clicking any of the buttons on a munitions control computer means that after closing the window (to try and multitask with two control computers) it opens again once the operation has completed.

Reproduce:

1. Click "Load tray" on the top computer while it's loaded.
2. Close window.
3. Open bottom computer, attempt to click "Load tray".
4. Observe as you accidentally unload the top missile tube.

**Comment by Vasily2013** [comment]
unable to reproduce

**Comment by Corsaka** [comment]
reproduction: https://youtu.be/l12BdFfO5P0
