### ISSUE TITLE
Nerf Etheral Charge

### ISSUE THREAD

**Issue by deadmomo69** [BeeStation/NSV13#266]
Etherals have to charge so often, that every five minutes I have to go to robotics to charge, with the huge walk to it, it puts me about to yellow health  with toxin damage, it really needs to be fixed.

**Comment by GoatMonarch** [comment]
I am fairly certain etherials can recharge by interacting with a light fixture to recharge their hunger.

There's also etherial food within food vendors. I'd advice for someone to playtest the race before making a balance change.

**Comment by Vasily2013** [comment]
So, from what i'm reading on Goat's comment, IC issue.
