### ISSUE TITLE
Broken black hole

### ISSUE THREAD

**Issue by DeanYktRu** [BeeStation/NSV13#2701]
Issue reported from  Round ID: 7665 (NSV 13 | Official | MRP | 98% Free Lag | Spaceship Combat Server)

Reporting client version: 515.1641

On round 7663 in NSV Snake I made a flight to Veneto and into the black hole. The result? Pirates and our ship just pass through the hole harmlessly, the screen wasn't darkened and no gravitational pull, only disabling the inertia dampeners.

It worked properly before.

**Comment by DeltaFire15** [comment]
Unable to replicate on my local with my only PR touching them, will keep my eyes out for it anyways, maybe testmerges meshing.

**Comment by jet-pack-cat** [comment]
Was able to replicate and completely forgot to actually comment anything.

This was in the real server.

Might have been related to that slowprocess() initialization bug or whatever it is. The one that fixes itself for a cycle when *any* map is loaded, and makes all the sparks stay forever and ship ai break... but its been too long to remember if that was it.
(on another note you can get it to fix itself on demand by using the miner bluespace pods!) useful for.... boarding, combat (if you dont like easy mode), and i guess getting destroyed floors to load properly for draining the stormdrives fuel tank.

![2024-08-18 16_11_29-NSV 13 _ Official _ MRP _ 98% Free Lag _ Spaceship Combat Server_ NSV _)](https://github.com/user-attachments/assets/66488942-1a0b-48e8-9c10-84ab9d034089)
![2024-08-18 16_11_43-NSV 13 _ Official _ MRP _ 98% Free Lag _ Spaceship Combat Server_ NSV _)](https://github.com/user-attachments/assets/8cbd8ccc-cd65-4c5b-a06c-e3f09a254749)

^^ fun screenshots! Notice how the ship is completely fine. no pull or anything. (yes this was veneto also) same as the effects mentioned.
