### ISSUE TITLE
Access restriction problem with reactor console

### ISSUE THREAD

**Issue by covertcorvid** [BeeStation/NSV13#273]
## Round ID:
70

## Reproduction:
Be an atmos tech (or possibly any role, I dunno)
Try to use the nuclear reactor console
Get "Access denied" warning in chat but have screen come up and be able to control it anyways

**Comment by francinum** [comment]
Improper access checking, the computer also fails to handle remote interaction (such as admin AI interact) properly, as the mob must be within 1 tile, this may be due to the fact it's not really a computer.

**Comment by Vasily2013** [comment]
KMC, this is why I hate how you hard-set access on everything!

**Comment by francinum** [comment]
Well, it IS a computer, it's just KMC overrode interactions violently

**Comment by Karmic-Skink** [comment]
Access restrictions isn't part of base computers.

There is an issue when a child is calling attack_hand
