### ISSUE TITLE
[Hammerhead] Inter-department access restrictions for engineering don't make sense

### ISSUE THREAD

**Issue by covertcorvid** [BeeStation/NSV13#274]
## Round ID:
72

## Reproduction:
Be atmos tech. Be unable to enter engineering lobby or engineering main doors. Have access from atmos to hanger and hanger to engineering though, and also to the maint door in the FTL/SMES room.

**Comment by francinum** [comment]
Engineering access names are a goddamn mess and should honestly be restructured and renamed.

The primary shared access between the two jobs isn't a nice `ACCESS_ENGINEERING`, but `ACCESS_CONSTRUCTION`. `ACCESS_ENGINE` exists but is private to station engineers, and is what most of engineering should ideally be using, however these issues were also likely caused during KMC's rushed remap of all the airlocks.

Honestly we just need a new map

**Comment by CoreFlare** [comment]
Just give atmos techs full/near-full engineering access because god knows they need it. After all, who else is gonna help an incompetent engineering team fix the stormdrive loop when the CE is absent?

**Comment by francinum** [comment]
How about we just nix that entire job and fold it into engineering as should have been done years ago.

**Comment by covertcorvid** [comment]
But muh firesuit

**Comment by francinum** [comment]
Their gear still exists, it's just staffed by station engineers instead of fusion-huffing plasmamen

**Comment by Vasily2013** [comment]
The main issue is that low-pop causes atmos techs to have full engineering access, but as soon as you get to higher population levels atmos techs get reduced to JUST atmospherics access. (As far as I can tell that is)

**Comment by covertcorvid** [comment]
Fairly certain I had the same doors open to me all round but I can do more
testing on it

**Comment by Karmic-Skink** [comment]
access = list(ACCESS_ENGINE, ACCESS_ENGINE_EQUIP, ACCESS_TECH_STORAGE, ACCESS_MAINT_TUNNELS, ACCESS_MECH_ENGINE, ACCESS_EXTERNAL_AIRLOCKS, ACCESS_CONSTRUCTION, ACCESS_ATMOSPHERICS, ACCESS_MINERAL_STOREROOM)
	minimal_access = list(ACCESS_ATMOSPHERICS, ACCESS_MAINT_TUNNELS, ACCESS_CONSTRUCTION, ACCESS_MECH_ENGINE, ACCESS_MINERAL_STOREROOM)

check the IDs

**Comment by Vasily2013** [comment]
Attempted reproduction. Could open all doors in atmos and engineering as both engineer and atmos tech.
