### ISSUE TITLE
Unable to late-join as a miner/miner job priority seems to be acting oddly.

### ISSUE THREAD

**Issue by Corsaka** [BeeStation/NSV13#277]
## Round ID:
 Round 72 Previous test.

## Testmerges:
Uncertain. May be related to munition puchi-gang or the mining re-work.

## Explanation:
Apparantly the option to late-join as a miner was not possible.
title, shaft miner cannot be joined if entering round late - seems to also have issues with high priority

"Baldir had set miner to high with no other roles and spawned in as a lawyer, with no miners aboard the station"

**Comment by Karmic-Skink** [comment]
![image](https://user-images.githubusercontent.com/45891563/72244979-52e80b80-363f-11ea-8ef5-2682be6afa42.png)
???

**Comment by GoatMonarch** [comment]
Closing this since:
![Issue closed](https://user-images.githubusercontent.com/43185112/72251692-89e9fd00-35fe-11ea-9dc5-d5e4e397e2b1.JPG)

Unless a guide to repeat the issue or round ID is given, pops up I am certain this is not an actual bug.

**Comment by Corsaka** [comment]
roundID 72: Baldir had set miner to high with no other roles and spawned in as a lawyer, with no miners aboard the station

**Comment by GoatMonarch** [comment]
Responce to Karmic got me confused. Seems to actually still be an issue.

**Comment by francinum** [comment]
https://github.com/BeeStation/NSV13/blob/78b032176d03415c2561c430e816eca09d3d4486/code/modules/jobs/job_types/shaft_miner.dm#L7

Loading jobs from txt, which is repo default, obscures this issue. Any PR that resets this should update that config entry.

**Comment by Karmic-Skink** [comment]
So are we using the hardcode system or the softcode system?
![image](https://user-images.githubusercontent.com/45891563/72288489-1517d100-3699-11ea-9531-5fbf1cc52dbe.png)

**Comment by francinum** [comment]
Beestation has this config enabled by default, as they store some of their configs as part of their repo... For some reason.
