### ISSUE TITLE
Exiting fighter cam after adming "get" use teleports you back to the fighter.

### ISSUE THREAD

**Issue by Vasily2013** [BeeStation/NSV13#283]
As titled. The player panel "get" verb does not remove the player from the fighter, they retain control over it after having been teleported out.

**Comment by Jalleo** [comment]
I dont know if mechs or any ridden vehicles manage that either actually.

**Comment by Vasily2013** [comment]
Okay, update. 

Now if you get the person and they exit using the camera cancel they are teleported back to the fighter.
