### ISSUE TITLE
Overmap sprites are off-center

### ISSUE THREAD

**Issue by Corsaka** [BeeStation/NSV13#288]
All overmap sprites are misleading (this is also true for fighters in the hangar bay) as their sprite is one tile down and left to where it actually is.
![RNXhQf8ptc](https://user-images.githubusercontent.com/23699128/72671107-57e0fc80-3a3d-11ea-97c4-ffdce7f5b371.gif)

**Comment by Kmc2000** [comment]
This is not something that can be easily fixed. BYOND absolutely HATES large sprites and tile based movement

**Comment by Corsaka** [comment]
escape pods are 16x16 how is this so hard

**Comment by Kmc2000** [comment]
resolved in fighter vibecheck
