### ISSUE TITLE
Ipc component research missing (?)

### ISSUE THREAD

**Issue by Freakycrafter** [BeeStation/NSV13#289]
Issue reported from  Round ID: 75 (NSV 13 | Official | "MRP" | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1507

I cant print any ipc components in exosuit fabricators and cant find them under the misc tab (where they should be otherwise) either. I also cant seem to find the related research for it to enable making those.

**Comment by Vasily2013** [comment]
Is this an issue upstream?
