### ISSUE TITLE
Red lights are extremely annoying for Xenobiology

### ISSUE THREAD

**Issue by Sikroth** [BeeStation/NSV13#290]
Issue reported from  Round ID: 75 (NSV 13 | Official | "MRP" | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1505

What it says in the title. Bonus points if you can tell me what colors these slimes all are

![image](https://user-images.githubusercontent.com/7857084/72671440-78638380-3a4a-11ea-879f-2ca63ac59ef0.png)

**Comment by Sikroth** [comment]
I know it's technically a bug but I would rather not sacrifice my retinas or stop playing xenobio entirely every time the enemergency lights go on. Can we have non-red lights that don't change to red maybe?

**Comment by Vasily2013** [comment]
I agree with this being an issue. Perhaps if there was a way to make a switch or something for battle lighting?
