### ISSUE TITLE
Hallucinations doesn't respect new rank code

### ISSUE THREAD

**Issue by Karmic-Skink** [BeeStation/NSV13#298]
Hallucinations are not prefaced with a rank as per normal chatter:

![image](https://user-images.githubusercontent.com/45891563/73135603-dc61f980-4093-11ea-9a40-f1738a2d57e6.png)

They do respect the first name call though:

![image](https://user-images.githubusercontent.com/45891563/73135631-2e0a8400-4094-11ea-9248-0b4697f8ac90.png)

**Comment by francinum** [comment]
Considering the rank is sourced from the speaker itself (Their ID card), there's no origin speaker here, the best you could probably do is check against the manifest, but that'd be quite expensive at the speed these calls are made.

**Comment by Vasily2013** [comment]
This isn't a huge issue. Gonna close.

**Comment by Karmic-Skink** [comment]
Y U DO DIS?
