### ISSUE TITLE
KMC's snowflake interior windows don't autosmooth like the ugly exterior ones.

### ISSUE THREAD

**Issue by Vasily2013** [BeeStation/NSV13#302]
These windows don't smooth like the exterior ones do, and thus Valk is also still not ready, because these windows are sloppily coded.

![image](https://user-images.githubusercontent.com/43328793/73497069-e9c6fe80-4387-11ea-9686-67f70190f091.png)

**Comment by Kmc2000** [comment]
Window panes (what these are) aren't designed to smooth though....

**Comment by Vasily2013** [comment]
Then they're poorly named/pathed.

**Comment by Kmc2000** [comment]
This is how the superclass works anyway. Not an issue
