### ISSUE TITLE
Torpedo's have the same explosion size when fired at the ship

### ISSUE THREAD

**Issue by CoreFlare** [BeeStation/NSV13#321]
It doesn't matter if you use a NTNK nuke or NTP-1 high velocity, the explosion size is the same. Even the NTP-0x EMP torpedo has the same explosion size as the nuke?

**Comment by Karmic-Skink** [comment]
Firstly, stop shooting our ship.
Secondly, arming distance. They aren't supposed to be fired at close range.

**Comment by CoreFlare** [comment]
Okay, I'll accept that, but there is a small problem. Maybe two
One: I'm not sure an EMP torpedo causes visible explosion? If it explodes on the ship shouldn't it make an actual EMP?
Two: Limiting all torpedos to the same explosion size drastically lowers possibilities for traitors to get involved.

**Comment by Karmic-Skink** [comment]
One: There are no EMP torpedoes.
Two: This is entirely intentional for balance reasons.

**Comment by CoreFlare** [comment]
So it turns out I was wrong about an EMP torpedo, it's actually a blank. But in my opinion that just makes it worse since... It's a blank? The warhead description for the 0x states that it forms an inert torpedo so I wouldn't expect it to explode with the same force as a nuke.
If it's purely for balance reasons, I don't see why a nuke couldn't be at least _slightly_ larger than a normal payload, or if a blank only did the explosion equivalent of a 10u water potassium reaction. Having them all the same doesn't make sense from a gameplay standpoint to me, especially the nukes, since, they are harder to obtain than regular torpedoes.

**Comment by CoreFlare** [comment]
The NTP-0x for reference https://i.imgur.com/CEgYCnN.png

**Comment by Karmic-Skink** [comment]
Because the only thing that is exploding is the fuel for the burner on the back.

Again, torpedoes etc are not designed to be fired at our own ship, and severely affect gameplay balance.

**Comment by Vasily2013** [comment]
There are code, lore, and balance reasons for why we aren't going to be increasing the damage radius of torpedoes. Soon enough the plan is to make sure that our overmap items (such as fighers, ship weapons, etc...) have their own type of damage, and thus can only properly be utilized on the overmap, as intended.
