### ISSUE TITLE
Vago Pre-merge Fixlist

### ISSUE THREAD

**Issue by Vasily2013** [BeeStation/NSV13#322]
This issue is for debugging Vago during closed testing and will be closed with the full merge of the map.
- [x] disconnected pipes: virology, brig, brig control, kitchen
- [x] no viewscreens
- [x] fighter pilot spawns
- [x] munitions tech spawns
- [x] airless plate fob airlock
- [x] set detective access for brig.
- [x] add wood to mining
- [x] make clown office tumor
- [x] no autodrobe
- [x] Shuttle windows on fob shuttles.
- [x] warden office dupe APC
- [x] Vago Maint Expansion

The update list from test 1
- [x] Vago specific arrivals shuttle.
- [x] MAC console out of position, move 1 tile back
- [x] change .json webmap pointer
- [x] Better signs for science directions
- [x] no maa spawn
- [x] light and camera in tool room have wrong dirs.
- [x] Station and FOB side mining shuttle control
- [x] add tools to munitions
- [x] change plastic in robotics to metal
- [x] fully constructed PDC mounts, FOB and main
- [x] floating intercomms on deck 1 behind ship
- [x] no camera in FTL control
- [x] repipe engine to have proper waste pipes
- [x] multi-deck pipe adapter is under floor
- [x] find better place for FOB grav gen
- [x] Add cargo techfab
- [x] Munitions hallway needs cameras
- [x] make proper airlocks for escape
- [x] remove one of the grav generators, move other to centerline
- [x] add munitions cart to the hangar
- [x] carp spawns
- [x] move bridge vent and add dradis to helm operator
- [x] engine aux apc gets grid checked
- [x] connect disposals to power grid
- [x] quick cycle airlocks in evac

**Comment by Vasily2013** [comment]
The update list from test 1
- [ ] Better signs for science directions
- [ ] light and camera in tool room have wrong dirs.
- [ ] Station and FOB side mining shuttle control
- [ ] add tools to munitions
- [ ] MAC console out of position, move 1 tile back
- [ ] change plastic in robotics to metal
- [ ] fully constructed PDC mounts, FOB and main
- [ ] change .json webmap pointer
- [ ] floating intercomms on deck 1 behind ship
- [ ] no camera in FTL control
- [ ] repipe engine to have proper waste pipes
- [ ] multi-deck pipe adapter is under floor
- [ ] find better place for FOB grav gen
- [ ] Add cargo techfab
- [ ] Munitions hallway needs cameras
- [ ] make proper airlocks for escape
- [ ] remove one of the grav generators, move other to centerline
- [ ] add munitions cart to the hangar
- [ ] carp spawns
- [ ] move bridge vent and add dradis to helm operator
- [ ] engine aux apc gets grid checked
- [ ] connect disposals to power grid
- [ ] quick cycle airlocks in evac

**Comment by Cenrus** [comment]
Put a DRADIS console next to the helm control console. We had a helmsman flying around without knowing where the enemy was during todays test
