### ISSUE TITLE
Enterprise Superthread

### ISSUE THREAD

**Issue by Vasily2013** [BeeStation/NSV13#324]
- [x] cameras coverage is spotty in some hallways.
- [x] two scrubbers behind the PA are right next to one another.
- [x] constrictors need to be in parallel, not in series.
- [x] rework access and ensure it is set.
- [x] Paramedic station has no access restriction.
- [x] Maintenance does not have access restrictions.
- [x] place departmental signs and directional signs around the ship.
- [x] Place a windoor between botany and the kitchen. It should have botany access.
- [x] HOP office no cameras
- [x] Captain's office no cameras
- [x] Captain's bar no camera.
- [x] Turret in top right corner of AI upload will not be able to shoot anything.
- [x] Electrify brig cell windows.
- [x] Electrify security entrance windows.
- [x] Add some sort of cradle for escape pods to seat in 
- [x] add engineering radiation shower somewhere.
- [x] put lights in tech storage. 
- [x] Tech storage APC has no cable going to it.
- [x] antag spawn waypoint
- [x] Move walls in SMES room one right, then move CE's things into his office, then add a shower to that toilet area.
- [x] make the arrivals shuttle point forward when docked.
- [x] ferry shuttle conflicts with escape shuttle
- [x] mass driver button access restriction
- [x] Rwall around the CMO's bedroom.
- [x] fix active turfs
- [x] Add more posters and the like around the ship to clutter the walls some. I advise random posters.
- [x] Vault motion sensor camera?
- [x] Add MAA locker
- [x] Run camera coverage checks. Normal areas should have two cameras, high security should have three, maint tends to be none, low low traffic areas can be 1.
- [x] Remove execution chamber camera
- [x] Run continuous pipes check
- [x] Run active turfs check
- [x] Run no-cameras check
- [x] Run no-lights check
- [x] Run no-apc check (ALL AREAS should have an APC)
- [x] Run no-airalarm check
- [x] binoculars for ATC towers
- [x] Extend a scrubber and vent into the high security armory
- [x] Electrify high security armory window
- [x] Add a morgue door to maint, make sure it has med access, not maint
- [x] No scrubber in operating room
- [x] No scrubber in hall intensive care hallway
- [x] no scrubber in medbay entrance hallway
- [x] no scrubber/vent in gravity generator
- [x] add a door into maint for the ferry shuttle or make a custom variant. 
- [x] reduce mining airlock size by one tile so the shuttle doesn't autosmooth with the far wall.
- [x] remove the RD hardsuit from toxins testing.
- [x] use multi-deck hallway areas from NSV.
- [x] For symmetrical purposes move the engines and heaters on the armory 1 north so it looks like its own isolated ship. (this is personal opinion)
- [x] keep the grav gen SMES' power terminal out of the wall please.
- [x] make turfs under windows plating turfs.
- [x] APC south of head briefing room has no knot under the terminal position.
- [x] use red wires for distribution to APCs, yellow for hot line from engine to SMES.
- [x] make engine pipes visible
- [x] rework atmos to have a separate pipe to the engine than to pure pipe.
- [x] Walls bordering space should be Rwall
- [x] answer Karmic's overmap questions.

--------------------------Fixlist 2-------------------
Superthread 2 fixer's boogaloo

- [x] I'm going to enjoy watching Cargo techs get gibbed by arriving shuttles.
- [x] I really hate that you abuse the pure line to ship plasma, but I won't make you change it.
- [x] The practice of requiring someone to go outside to start the engine is questionable, but at the same time acceptably cheap and cost effective.
- [x] add near ship area around the ship.
- [x] add directional signs to the bridge.
- [x] medical sign in medbay lobby can not be seen from the hallway. Either add another sign or move the current one.
- [x] Engineering sign at bar should point north
- [x] No engineering directional signs outside of arrivals
- [x] No way to deactivate AI core turrets with ID card.
- [x] AI core and upload should not start bolted
- [x] No O2 tank dispenser in engineering storage.
- [x] Ensure ATC has maint access, or ATC is a req_one_access on the required doors and that they know where the ladder is.
- [x] Genetics has multiple APCs
- [x] /area/ai_monitored/turret_protected/aisat has multiple APCs

- [ ] Warehouse should have shutters, not doors IMO.
- [ ] Captain's spare still shouldn't start in the locker.
- [ ] CMO bedroom shouldn't have glass door imo.

The following areas lack air alarms
- [x] RD Server
- [x] Disposals
- [x] Chapel Office
- [x] Cargo maint (can be left this way)
- [x] /engine/atmospherics_engine
- [x] grav gen
- [x] /engine/storage
- [x] hanger/deck 3
- [x] aft primary hallway
- [x] deck 1 hallway

RC Consoles
- [x] Head RC consoles should have 'announceAuth' and 'announcementConsole' set to 1
- [x] HEADS OF STAFF NEED RC CONSOLES

The following areas should probably have lights
- [x] Chapel office
- [x] /engine/atmospherics_engine

- [x] All heads should have an intercomm in their office
- [x] add an intercomm to the briefing room.
- [x] add an intercomm to torpedo room and fighter bay.

-and I hate to do this, but you were right, you may re-add the tiny fans under the escape pod templates.
-ship exterior still has a TON of active turfs.

**Comment by Vasily2013** [comment]
What in the nine hells is the other docking port? Also those tiny fans are lazy and should not be there. New objective created.
- [ ] Purge tiny fans
![image](https://user-images.githubusercontent.com/43328793/74210016-1e746900-4c58-11ea-9564-47482f466345.png)

**Comment by Vasily2013** [comment]
Why is there a hole here?
![image](https://user-images.githubusercontent.com/43328793/74210833-55984980-4c5b-11ea-8635-5f7d7c3a54ff.png)

**Comment by Kmc2000** [comment]
> What in the nine hells is the other docking port? Also those tiny fans are lazy and should not be there. New objective created.
> 
> * [ ]  Purge tiny fans
>   ![image](https://user-images.githubusercontent.com/43328793/74210016-1e746900-4c58-11ea-9564-47482f466345.png)

They need to be there or air will leak past the pod's engines. This is taken direct from meta

**Comment by Vasily2013** [comment]
> > What in the nine hells is the other docking port? Also those tiny fans are lazy and should not be there. New objective created.
> > 
> > * [ ]   Purge tiny fans
> >   ![image](https://user-images.githubusercontent.com/43328793/74210016-1e746900-4c58-11ea-9564-47482f466345.png)
> 
> They need to be there or air will leak past the pod's engines. This is taken direct from meta

Put plating under them and place a housing around the escape pod. When the template loads it will leave the plating under it, use the walls of the pod to seal it off.

**Comment by Vasily2013** [comment]
Going through some more things. (Yes, I know, i'm drowning you in bugs.
- [ ] Custodial has camera not attached to wall
- [ ] two cameras on the same spot in hanger bay
- [ ] Camera in t-comms is connected to a door.
- [ ] update C-tags for motion sensitive cameras so it is not 'null'
- [ ] camera blindspot in medbay entrance hall southern end.
- [ ] No cameras in armory (motion sensors in high security area, normies in the normie area)
- [ ] Add more intercomms around the ship (there's a debug verb to view range)
- [ ] Add requests consoles around the ship.

**Comment by Cenrus** [comment]
There is a camera stuck to an airlock in Telecommunications, which doesn't have its own SMES.

**Comment by Cenrus** [comment]
Walking downstairs shows a visible falling message, https://github.com/tgstation/tgstation/pull/47588 fixes this

**Comment by Cenrus** [comment]
- Engineering lacks electrical supplies lockers
- There is no RD console in engineering, so engineers can't use their imprinter
- There is a vent but no scrubber in the engineering lobby
- No Engi-vend vending or YouTool machines

**Comment by Cenrus** [comment]
No gateway on the map, could be intentional but it prevents swarmers from spawning.

**Comment by Cenrus** [comment]
![image](https://user-images.githubusercontent.com/31044876/74339564-42d95e00-4d9c-11ea-9fa2-693a5be04ab9.png)

CentCom officials have access to the airlock above the Aux shuttle dock, but not to the left airlock.

**Comment by Cenrus** [comment]
![image](https://user-images.githubusercontent.com/31044876/74339755-9e0b5080-4d9c-11ea-988d-dba072367c57.png)

using the light switch in the Chapel office toggles the light fixture here in maintenance.

**Comment by Cenrus** [comment]
The doors into Hydroponics should be called Hydroponics instead of Botany, for consistency

**Comment by Cenrus** [comment]
No library on the map, how will the beloved curator fill the common radio with "literature"?

**Comment by Cenrus** [comment]
![image](https://user-images.githubusercontent.com/31044876/74341819-4b339800-4da0-11ea-9f24-0c767a9badd6.png)

No airlock cyclelink helper here, so both airlocks tend to open at once and depressurize the room

**Comment by Cenrus** [comment]
![image](https://user-images.githubusercontent.com/31044876/74341937-8b931600-4da0-11ea-9219-7222cd51cdb2.png)

external cables are at great risk from space dust, as there are no grilles for shielding

**Comment by Cenrus** [comment]
![image](https://user-images.githubusercontent.com/31044876/74342234-17a53d80-4da1-11ea-86ff-b238740af8e2.png)

Fitness ring is real dark. I need to be able to SEE my opponent, damnit!

**Comment by Cenrus** [comment]
No holodeck on the map, may want to cut out some of the Gym to make room for it.

**Comment by Cenrus** [comment]
Pun Pun is not on the map, and cargo's pet sloth is nowhere to be seen.

**Comment by Cenrus** [comment]
![image](https://user-images.githubusercontent.com/31044876/74343223-a36b9980-4da2-11ea-8758-cf60a0dd3801.png)

There are no Emergency Storage rooms with fire closets and water tanks, so crewmembers are at great risk from plasma fires.

**Comment by Cenrus** [comment]
![image](https://user-images.githubusercontent.com/31044876/74344530-ad8e9780-4da4-11ea-8f59-452edfc13aba.png)

No Atmospherics lobby room with spare canisters and station alerts consoles.

**Comment by Cenrus** [comment]
Can't reach the AI upload turret control panel.

**Comment by Cenrus** [comment]
- [ ] Telecommunications doesn't have an independent SMES

**Comment by Cenrus** [comment]
![image](https://user-images.githubusercontent.com/31044876/74379560-ef88ff00-4ddf-11ea-9d74-a4f55b1907be.png)

- [ ] Floating camera in the custodial closet.

**Comment by Vasily2013** [comment]
> ![image](https://user-images.githubusercontent.com/31044876/74379560-ef88ff00-4ddf-11ea-9d74-a4f55b1907be.png)
> 
> * [ ]  Floating camera in the custodial closet.

please read above to make sure that you're not giving duplicate issues.

**Comment by Cenrus** [comment]
I noticed a similar floating camera that was marked as complete, so I'm assuming this camera is a different issue.

**Comment by Cenrus** [comment]
- [ ] Missing disposal pipe under a maintenance airlock. 
![image](https://user-images.githubusercontent.com/31044876/74380774-206a3380-4de2-11ea-97ad-1a32d31521f7.png)

**Comment by Cenrus** [comment]
Hydroponics oversights

- [ ] No vendor for botanist clothing
- [ ] No toaster for storing plant data disks
- [ ] No water tanks.
- [ ] No backpack water tank
- [ ] No condimaster

**Comment by Cenrus** [comment]
- [ ] Bartender has no BarDrobe, Condimaster, shotgun, and booze locker
- [ ] No water tank in the primary tool storage
- [ ] No xeno spawnpoints
- [ ] Chef doesn't have pete
- [ ] No dressers in the clown's room or the dorms
- [ ] Officers mess can be accessed by anyone
- [ ] Heads are missing their respective departmental stamps, telescreens and request consoles
- [ ] No medicine closet in the infirmary
- [ ] Doors into the custodial closet should name named "Custodial Closet" instead of "Janitorial"
- [ ] Missing plating under the door seperating the Custodial Closet from the Janitor Storage

**Comment by Cenrus** [comment]
- [ ] Missing area in these locations

![image](https://user-images.githubusercontent.com/31044876/74541139-0000bd00-4f39-11ea-9213-18ab6c11a806.png)
![image](https://user-images.githubusercontent.com/31044876/74541151-098a2500-4f39-11ea-837d-7443cf07db86.png)

**Comment by Cenrus** [comment]
- [ ] No smartfridge for extracts in xenobiology
- [ ] One of the doors leading into the science lobby is incorrectly named "Chemistry"
- [ ] No way to cycle the airlock into the Toxins Mixing Chamber
- [ ] Sci has no toxins storage, making toxins impossible without atmospherics assistance
- [ ] No engineering secure storage with emitters, field generators and plasma for the PACMAN generators

**Comment by Cenrus** [comment]
![image](https://user-images.githubusercontent.com/31044876/74558186-bbd1e480-4f59-11ea-9f84-f511c0afe1ea.png)

- [ ] Missing cable in Telecomms prevents the APC from charging

**Comment by Cenrus** [comment]
- [ ] Security doesn't have a departmental protolathe
- [ ] Cargo doesn't have a departmental protolathe
- [ ] Cargo doesn't have an autolathe or materials to load it with
- [ ] Engineering has no station/atmos alert consoles
- [ ] Virology access button serves no purpose
- [ ] The ORM deposits north instead of west as it should ( this can be fixed by setting the input_dir variable to 4)

**Comment by Cenrus** [comment]
- [ ] Anyone can access the lawyers office

**Comment by Vasily2013** [comment]
Superthread 2 fixer's boogaloo

- [ ] add near ship area around the ship.
- [ ] add directional signs to the bridge.
- [ ] medical sign in medbay lobby can not be seen from the hallway. Either add another sign or move the current one.
- [ ] CMO bedroom shouldn't have glass door imo.
- [x] I'm going to enjoy watching Cargo techs get gibbed by arriving shuttles.
- [ ] Warehouse should have shutters, not doors IMO.
- [ ] Engineering sign at bar should point north
- [ ] No engineering directional signs outside of arrivals
- [ ] Captain's spare still shouldn't start in the locker.
- [ ] No way to deactivate AI core turrets with ID card.
- [ ] AI core and upload should not start bolted
- [ ] No O2 tank dispenser in engineering storage.
- [x] I really hate that you abuse the pure line to ship plasma, but I won't make you change it.
- [ ] Ensure ATC has maint access, or ATC is a req_one_access on the required doors and that they know where the ladder is.
- [x ] The practice of requiring someone to go outside to start the engine is questionable, but at the same time acceptably cheap and cost effective.
- [ ] Genetics has multiple APCs
- [ ] /area/ai_monitored/turret_protected/aisat has multiple APCs


The following areas lack air alarms
- [ ] RD Server
- [ ] Disposals
- [ ] Chapel Office
- [ ] Cargo maint (can be left this way)
- [ ] /engine/atmospherics_engine
- [ ] grav gen
- [ ] /engine/storage
- [ ] hanger/deck 3
- [ ] aft primary hallway
- [ ] deck 1 hallway

RC Consoles
- [ ] Head RC consoles should have 'announceAuth' and 'announcementConsole' set to 1
- [ ] HEADS OF STAFF NEED RC CONSOLES

The following areas should probably have lights
- [ ] Chapel office
- [ ] /engine/atmospherics_engine

- [ ] All heads should have an intercomm in their office
- [ ] add an intercomm to the briefing room.
- [ ] add an intercomm to torpedo room and fighter bay.

-and I hate to do this, but you were right, you may re-add the tiny fans under the escape pod templates.
-ship exterior still has a TON of active turfs.

**Comment by Cenrus** [comment]
- [ ] Remove the current xeno spawnpoint and add some more above vents around the ship

Xenos rely on vents to move around, and their only spawnpoint is currently in a maintenance room with no vents or scrubbers, and have no access to leave.
