### ISSUE TITLE
Shuttle Manipulator on the Hammerhead

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/NSV13#330]
The shuttle manipulator in the Hammerhead isn't just for show, it works identically to the admin tool. Should be modified so the crew can't play god with it

**Comment by Vasily2013** [comment]
where is it on the map?

**Comment by Cenrus** [comment]
It's in the war room, above the CIC. 
However you can't use it while deadmined, so it should be fine to keep

**Comment by francinum** [comment]
This is related to the fact that Bee hasn't ported tgstation/tgstation#44655
