### ISSUE TITLE
Cargo Shuttle leaves behind a broken area when leaving the cargo bay

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/NSV13#331]
## Reproduction

1. Call the cargo shuttle

2. Send the cargo shuttle back

3. After the shuttle has left, the area it occupied appears broken

![image](https://user-images.githubusercontent.com/31044876/74562175-2424c400-4f62-11ea-8fa2-9eeb2c8ec1a3.png)

Should be fixed by https://github.com/BeeStation/BeeStation-Hornet/pull/1042 but I'd need to test it

**Comment by Vasily2013** [comment]
If it is fixed by 1042 then all we need to do is merge from upstream to resolve it.

**Comment by Cenrus** [comment]
fixed from bee upstream merge
