### ISSUE TITLE
Issues with Magnetic Constrictor construction

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/NSV13#342]
- Build a vertical pipe on layer 2 with the RPD, hold it in your active hand, and click the constrictor. The pipe will magically teleport onto your tile.

- Can't alt click to rotate constrictors like the examine text implies.

- Magnetic constrictors don't connect to nearby pipes when constructed

![image](https://user-images.githubusercontent.com/31044876/74961145-80c22c00-5405-11ea-9092-71c3c0c65d38.png)

**Comment by francinum** [comment]
Any runtimes related to this if possible would be great.

**Comment by Cenrus** [comment]
Couldn't find any.

**Comment by francinum** [comment]
This is some pretty bad oldcode, @Karmic-Skink are constrictors getting a changeup in your new PR by chance?

**Comment by Vasily2013** [comment]
Verrified

**Comment by francinum** [comment]
```
(E) (C) (M) piping_layer = null
```

**STILL** an issue...
