### ISSUE TITLE
Munitions construction bugs

### ISSUE THREAD

**Issue by covertcorvid** [BeeStation/NSV13#357]
## Testmerges:
#344 #125 

I'll be fixing this, just keeping track.
- Guns deconstruct into south-facing position
- Munition console linking is still in the wrong direction
- Railgun overlays aren't getting deleted when a gun is deconstructed
- Make it harder to accidentally deconstruct railguns

**Comment by Cenrus** [comment]
Some other strange behaviour I discovered.

1. Unscrew and unbolt the railgun, then click it with an empty hand to remove the tray.

2. Put the tray back into the unfinished railgun frame

3. Clicking the railgun again with an empty hand will cause you to take the railgun tray out, despite the maintenance panel being closed.
