### ISSUE TITLE
Suffocation with broken canopy in normal atmosphere

### ISSUE THREAD

**Issue by Freakycrafter** [BeeStation/NSV13#358]
## Reproduction: broken canopy in a fighter

Basically, when youre in a fighter and the canopy is broken you suffocate even if youre in normal atmosphere. (Reported by Tristan63/Uriel Jacobsen)

**Comment by Vasily2013** [comment]
Unable to replicate, attempted in thunderdome, Ambient atmosphere does not appear to have an effect on canopy breach at this time.

**Comment by Vasily2013** [comment]
Verrified, you have to re-enter the fighter and then it has the effect after var breaking the canopy.

**Comment by francinum** [comment]
One last grace period.

**Comment by Bokkiewokkie** [comment]
I tested this and I think it was fixed (don't know where or by who though) but I flew into space and broke the canopy, after this I re-entered the atmosphere when flying in space earlier and I could breathe perfectly fine in the atmos with a broken canopy. I also did a control test and when the canopy breaks in the hangar itself (both times I did the re-entering after the canopy broke btw) I could still breathe fine.

**Comment by Bokkiewokkie** [comment]
okay nevermind it took a minute but after that I started suffocating while in atmos with a breached canopy

**Comment by Bokkiewokkie** [comment]
fix for this would probably just be making a similar system mechs have btw (or even just literally copying that system)

**Comment by Jalleo** [comment]
It is the system that mechs use. This is not easy to properly fix.
