### ISSUE TITLE
[Enterprise] My Observations

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/NSV13#366]
- [x] Toxins could use some more gas tanks.
- [x] Engineers need atmos access to set up the engine
- [ ] Tcomms needs a double airlock to prevent the freezing gas from escaping the server room
- [x] Flight Deck ATC/Fighter pods need vents and scrubbers as frequent airlock usage results in depressurization
- [x] Engineering could use an extra hardsuit
- [x] Engineering needs durametals and nanocarbon glass for hull breach repairs
- [x] Turf decal in the wall above the ORM
- [x] robotics exofabs print to the right instead of the turf below them, likely due to their dir vars.
- [x] add two buckets and a sink to the permenant brig so the prisoners have something to do.
- [x] The brig EATS power and runs out shortly after roundstart if the engineers are incompetent. split up the area some more with the Security office area type (area/security/main) or add a higher capacity power cell to the brig APC.
- [x] hangar needs nuclear waste spawner
- [x] armoury needs lethal pulse rifle bullets
- [x] Conveyor leading into the north of cargo doesn't work, it can't be activated with the nearby lever
- [x] toxins needs another air pump
- [x] Cargo uses the wrong kind of protolathe, so it can't make express supply consoles etc. the typepath should be /obj/machinery/rnd/production/techfab/cargo instead of /obj/machinery/rnd/production/protolathe/cargo. Same goes for security
- [x] Xenobiology needs at least two scientist bio lockers
- [x] Xenobio needs two droppers

**Comment by Vasily2013** [comment]
Tcomms honestly shouldn't start freezing

**Comment by Vasily2013** [comment]
All issues have been addressed. Closing.
