### ISSUE TITLE
[PVP] PVP MEGATHREAD

### ISSUE THREAD

**Issue by Kmc2000** [BeeStation/NSV13#389]
Please dump all PVP feedback, complaints, bugs etc. here.

I'll get to it eventually :tm:

**Comment by DrSirKnight** [comment]
The syndicate missles and railguns broke once I fired them once lol

**Comment by Koekiegast** [comment]
> The syndicate missles and railguns broke once I fired them once lol

Just like the enterprise's torpedo tubes

**Comment by Cancan1203** [comment]
Having Syndies with set roles like regular crew would be nice. I know it'd be more crap to sort out on the antag pref screen but I think it'd be nice

**Comment by Kmc2000** [comment]
We should timelock FTL jump for 15 mins on both ships to give people time to prep.

**Comment by Cenrus** [comment]
Syndicate stormdrive announces over the Engineering radio, it should broadcast over the syndicate radio instead.

Comms console on the Hammurabi does nothing because it's not on the station z-level.

Engineering need tools/mats to fix hull damage

No ammo for SMGs

**Comment by Kmc2000** [comment]
Syndicate roles are required.
Auto assigned roles that tell you what to do, ignorable as optional
