### ISSUE TITLE
Can't construct basic metal walls

### ISSUE THREAD

**Issue by Vasily2013** [BeeStation/NSV13#39]
Don't know why, just couldn't patch a hole in the hull with metal.

edit: Engineering on Ageis is also lacking in the project-specific materials required to create project-specific walls.

**Comment by Karmic-Skink** [comment]
In theory the alloys were going to be linked into some sort of mining smelter system in the future using already existing materials.

**Comment by covertcorvid** [comment]
Fixed by #248
