### ISSUE TITLE
Chemistry record function unresponsive

### ISSUE THREAD

**Issue by Anonmare** [BeeStation/NSV13#393]
## Round ID:
109

## Testmerges:
#386: '[EXPERIMENTAL] [DNM] Pvp gamemode' by Kmc2000 at commit c9d68c5559
#347: '[READY] NSV Hammerhead additions and fixes' by Cenrus at commit 92ab81d10b

## Reproduction:
Access machine
Put beaker in
Hit record
No effect

**Comment by Cenrus** [comment]
Should be closed in #396

**Comment by francinum** [comment]
Resolved in #396
