### ISSUE TITLE
Fighter ejection pods qdel pilot on kill instead of ejecting them

### ISSUE THREAD

**Issue by francinum** [BeeStation/NSV13#407]
## Round ID:
121

## Testmerges:
#386 

## Reproduction:
Put a pilot in a locked canopy fighter
Shoot them with small arms until the fighter breaks
put like 3 bullets into the escape pod
bam, pilot qdels with all their shit.

**Comment by francinum** [comment]
@Karmic-Skink Is this planned to be handled in DI?

**Comment by Vasily2013** [comment]
As well, is this intentional, and if so why? I want to know why we're permanently removing peeps from the round.

**Comment by francinum** [comment]
@Karmic-Skink @Kmc2000 is this intended behavior on ship z-levels?
