### ISSUE TITLE
Auto-Mute can be triggered by security aim function.

### ISSUE THREAD

**Issue by Firefox13** [BeeStation/NSV13#414]
## Reproduction:

Talk alot, use emotes alot, write runes alot and the game mute you for it. Usually it mutes when player wasn't spamming intentionally.

**Comment by Firefox13** [comment]
It's still unironically an issue

**Comment by Vasily2013** [comment]
@Firefox13 does this happen on Beestation too?

**Comment by francinum** [comment]
These systems need to have `forced` set and anti-spam implemented at their level.

**Comment by Vasily2013** [comment]
This can happen with literally any emote. It's only an issue when you spam it. I'm closing this in 7 days if it is not specifically kept open by another maintainer.

**Comment by Jalleo** [comment]
If Kmc wants to fix it then we fix it otherwise it can get closed.
