### ISSUE TITLE
[Enterprise] No bio suits for Xenobio

### ISSUE THREAD

**Issue by GoatMonarch** [BeeStation/NSV13#415]
## Issue:
There's no biosuit lockers on station, so they can't get bio bags for the monkey cubes and slime cores.

**Comment by Tennessee116** [comment]
Absolutely none? On which map?

**Comment by GoatMonarch** [comment]
Ship name's in the title.
And that'd cause all scientists to spawn in with a bio bag in their backpack.
Also, that would just harm it if someone got a job change.

**Comment by Tennessee116** [comment]
Oh didn't see that. Hmm. Ok.

**Comment by Cenrus** [comment]
Damnit, I knew something was missing...

Looking at the webmap it appears that virology does have biosuit lockers.

**Comment by Vasily2013** [comment]
Virology has 3x biosuit lockers in the airlock.

**Comment by Cenrus** [comment]
This is about Xenobiology, xenobio needs at least two biohazard lockers as biobags can collect slime extracts

**Comment by GoatMonarch** [comment]
> Virology has 3x biosuit lockers in the airlock.

The title states xenobio. Pardon the descriptive part, but this issue is still very much a thing.
