### ISSUE TITLE
Hangar/MAA access not on the HTML ID console

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/NSV13#419]
Title

## Reproduction

Use an ID console, check for munitions access. It doesn't show.

**Comment by Karmic-Skink** [comment]
![image](https://user-images.githubusercontent.com/45891563/77704631-6d5e3e00-700d-11ea-9ccb-db86df12260a.png)

Works on my machine.

**Comment by Karmic-Skink** [comment]
Okay so. This isn't an issue if people didn't for some reason put the old HTML based identification consoles in.

They were supposed to be obsolete.

**Comment by Vasily2013** [comment]
Which map is this and what is the proper object path?

**Comment by Karmic-Skink** [comment]
/obj/machinery/computer/card is the HMTL based ident console.

/obj/machinery/modular_computer/console/preset/command has the TGUI based functional console.

It is apparently now on all maps.
As I tend to test only on hammerhead for reasons. I can tell you this change to hammerhead was recent.

![image](https://user-images.githubusercontent.com/45891563/77726635-4f61ff00-7048-11ea-87bf-5831308611ae.png)
Computer at top is BAD.
Computer at bottom is GOOD.

**Comment by Vasily2013** [comment]
This issue will be fixed on Vago and Hammerhead when #423 is merged.

**Comment by francinum** [comment]
No.

**Comment by Kmc2000** [comment]
We're deleting these consoles.

TODO: Port the job slot management to the modcomp ones and make the preset buildable via research

**Comment by Corsaka** [comment]
Fixed this, didn't see it when I made the pr. Requesting closure.
