### ISSUE TITLE
Syndicate Drop Troopers have no antag datum

### ISSUE THREAD

**Issue by francinum** [BeeStation/NSV13#425]
## Round ID:
Irrelevant

## Testmerges:
Irrelevant

## Reproduction:
Get spawned in as a Syndicate Drop Trooper
Open your own traitor panel
See no active selections or objectives
Check-Antagonists doesn't list you.
Check your mind and realize that you have `assigned_role` but no antag datum.

**Comment by Vasily2013** [comment]
Still an issue

**Comment by francinum** [comment]
Silently fixed...
