### ISSUE TITLE
Seegson TAC does not provide accurate "Active Armour" count

### ISSUE THREAD

**Issue by Shadow-Quill** [BeeStation/NSV13#431]
## Testmerges:

#421 #423 

## Reproduction:

1) Repair plating after damaged
2) See how Seegson TAC shows one more plating in active platings, even though bar may be maxed.

**Comment by Kmc2000** [comment]
Due to how many plates there are, 1 plate is less than 1% of that bar's progress. It's closer to 0.22%. This'll likely mess with the bar's display.

**Comment by Shadow-Quill** [comment]
Last round I played on the Enterprise, I got up to 1000+ active platings

**Comment by Kmc2000** [comment]
Please check that this still exists after my fixes to armour plates. If it does, remake this.
