### ISSUE TITLE
M4-B Torpedo tubes "Not being detected" with new GUI

### ISSUE THREAD

**Issue by jzburda** [BeeStation/NSV13#432]
## Reproduction:

Loading a tube with a torpedo, safety on or off, will not be able to be fired by the bridge officers. Sometimes, they are "Detected" but most times they can't be. It seems cleaning them out after each firing fixes it sometimes.

**Comment by Bokkiewokkie** [comment]
I've noticed this same thing happening and from what I've seen it looks like you have to fully reload the tubes after each jump. Which would mean you can't have your torpedoes loaded before you enter combat.

**Comment by jzburda** [comment]
> 
> 
> I've noticed this same thing happening and from what I've seen it looks like you have to fully reload the tubes after each jump. Which would mean you can't have your torpedoes loaded before you enter combat.

that's kinda ouch

**Comment by Vasily2013** [comment]
Recent reports through ahelp warrant removal of stale tag. @Karmic-Skink did you correct this with Disco Inferno?

**Comment by francinum** [comment]
Not reverified after grace period.
