### ISSUE TITLE
webmap vago when

### ISSUE THREAD

**Issue by Firefox13** [BeeStation/NSV13#437]
## Round ID:
doesn't matters
## Testmerges:
probably same as above

## Reproduction:
press this
![изображение](https://user-images.githubusercontent.com/57810301/77857791-69e2d680-7208-11ea-9b27-8ff34404222a.png)
see this
![изображение](https://user-images.githubusercontent.com/57810301/77857796-72d3a800-7208-11ea-8e8c-67d1bdd88e31.png)

**Comment by Vasily2013** [comment]
Soon.tm Affected is working on it.
