### ISSUE TITLE
Add wayfinding beacons and pinpointers to Vago

### ISSUE THREAD

**Issue by Victor239** [BeeStation/NSV13#438]
Map is confusing and the signs are insufficient, please [add these](https://github.com/tgstation/tgstation/pull/48326) to aid with navigation.

**Comment by Vasily2013** [comment]
Are these assets in Bee?

**Comment by francinum** [comment]
May have been silently fixed, Needs reconfirmation.

**Comment by Bokkiewokkie** [comment]
> May have been silently fixed, Needs reconfirmation.

I can confirm it has not been fixed (probably cause vago = die)

**Comment by theboy6545** [comment]
can we close the issue considering vago is kill
