### ISSUE TITLE
You can telepathically toggle brakes on munition trolley without TK

### ISSUE THREAD

**Issue by Firefox13** [BeeStation/NSV13#439]
## Round ID:

145
## Testmerges:

#421 #423 
## Reproduction:

1. See a Munitions Trolley 
![изображение](https://user-images.githubusercontent.com/57810301/77860338-5f7c0900-7217-11ea-9304-cdf4cee3ecb1.png)
2. alt+click it while staying close to it
![изображение](https://user-images.githubusercontent.com/57810301/77860356-76226000-7217-11ea-8957-d9cfa714203e.png)
![изображение](https://user-images.githubusercontent.com/57810301/77860358-77ec2380-7217-11ea-9614-c4f565af2459.png)
3. step back 
![изображение](https://user-images.githubusercontent.com/57810301/77860368-863a3f80-7217-11ea-97a2-43f9081140a4.png)
4. alt+click it, you still can toggle the brakes
![изображение](https://user-images.githubusercontent.com/57810301/77860376-92260180-7217-11ea-98a3-232c587d4a48.png)

**Comment by Vasily2013** [comment]
verified, Not sure if this is a bug or a feature.

**Comment by francinum** [comment]
Bug. This isn't about the genetic power, it's a lack of range check. Should be doing a can_interact check, likely.

**Comment by francinum** [comment]
If we ever give traitors a reason to make off with shells this will cause problems. Though even now it's an inconsistency

**Comment by Vasily2013** [comment]
I still don't really see the issue with it. KMC has also said it's more of a feature than an issue.

**Comment by francinum** [comment]
This is still a bug.
