### ISSUE TITLE
Lathes can't print NSV13 mettals!

### ISSUE THREAD

**Issue by GoatMonarch** [BeeStation/NSV13#445]
## Round ID:
Irrelevant.

## Testmerges:
Always been like this as far as I know.

## Reproduction:
Cargo, sci, engineering tech fabricators can't print durrasteel. Even though we got it in our code
https://cdn.discordapp.com/attachments/605904125028204554/694467036121923594/unknown.png
(Crediting to Karmic for the screenshot)

**Comment by GoatMonarch** [comment]
https://cdn.discordapp.com/attachments/605904125028204554/694468618221781033/unknown.png
Apparantly the ORM can though. :thonk:

**Comment by Karmic-Skink** [comment]
Fixed in Disco Inferno P2 - aka fighters
