### ISSUE TITLE
Core overheat announcement triggers way too aggressively way too early.

### ISSUE THREAD

**Issue by francinum** [BeeStation/NSV13#448]
## Round ID:
150

## Testmerges:
Irrelevant

## Reproduction:
let temperatures heat up to minorly dangerous level

ENTIRE CREW CHARGES ENGINEERING BECAUSE THE SOUND MAKES IT FEEL AS IF THE SHIP IS ABOUT TO DETONATE IN 30 SECONDS.

**Comment by Karmic-Skink** [comment]
Give me some numbers for where you want it to be.

**Comment by Corsaka** [comment]
consider that it can be saved even at 400deg; i'd say around 325 should be a decent warning level

**Comment by ta3370** [comment]
The stormdrive is set up so that if you hammer the engine to max, by the time that alarm goes off, you have very little time, the reason it seems so aggressive is it triggering from creeping over slowly. But if somebody tries sabotaging it, that alarm is barely any warning.
