### ISSUE TITLE
AI Unable to interact with objects

### ISSUE THREAD

**Issue by Harry-Jubilee** [BeeStation/NSV13#450]
The AI is unable to actually use the RMBK Reactor Control Console and The FTL Drive. It can open the windows but not actually interact with any of the buttons. This was actually a round-ending problem on a particular round when I was playing the AI and was unable to prevent meltdown.

Reproduction:

Play AI, attempt to use consoles.

**Comment by Karmic-Skink** [comment]
Not a bug.

**Comment by Harry-Jubilee** [comment]
@Karmic-Skink How is this not a bug?

**Comment by Kmc2000** [comment]
resolved
