### ISSUE TITLE
Teleporting on the Nostromo (and possibly FOB) doesn't work (Missing Z-traits for mining)

### ISSUE THREAD

**Issue by Bokkiewokkie** [BeeStation/NSV13#457]
## Round ID:
Today (technically 4-4-2020) at around 3:00 am (the round ended with a crash so idk the id)
## Testmerges:
none
## Information:
When you use an item which is supposed to teleport you while you are on the Nostromo (or maybe just the mining ship Z level in general) you are unable to use it. This looks like it works the same way as the anti-teleporting of the Central Command Z level.  
## Reproduction:
1 Go to the Nostromo
2 Activate an item that teleports you, for example: A bluespace crystal, Quantum spin inverter, bluespace pad, admantium armor, etc. (effect of conventional teleporting still unknown)
3 Wait for the normal time it would take you to teleport and realize you're in the exact same place without any teleporting having even occurred.

**Comment by Vasily2013** [comment]
Specifically you can not go FROM a place TO mining.
