### ISSUE TITLE
[PVP] Syndicate fighters have no thrust animations

### ISSUE THREAD

**Issue by Vivalas** [BeeStation/NSV13#462]
## Reproduction:
When turning or maneuvering the syndicate fighters, there are no thrust animations like there are on NT fighters.

**Comment by Vasily2013** [comment]
You also have to still hold forward while starting to get the engines going.

**Comment by Jalleo** [comment]
Going to close this issue as its old and create a new issue report saying that syndie PVP needs a overhaul before it comes back as a gamemode to make sure its up to standard with latest normal versions with how it works.
