### ISSUE TITLE
Gauss Turret are Glass Cannons

### ISSUE THREAD

**Issue by Firefox13** [BeeStation/NSV13#463]
## Reproduction:
1. shoot/punch gauss turret with pistol/sec rifle/stun baton/literally almost anything
2. gauss turret gets destroyed

I thought it's like sci-fi tank turret with atleast a bit of armour padding, it shouldn't get destroyed easy as that

**Comment by Vasily2013** [comment]
11 shots with a pulse laser (kill mode) to be specific. I'd suggest upping the integrity some, I agree they should be a bit more hefty.

**Comment by francinum** [comment]
Could probably do with damage deflection.

**Comment by Vasily2013** [comment]
Was able to magdump a full pulse pistol on kill. Issue appears to be solved.
