### ISSUE TITLE
Deconsturcting NSV specific windows drops insufficient materials to reconstruct them.

### ISSUE THREAD

**Issue by GoatMonarch** [BeeStation/NSV13#469]
## Round ID:
Irrelevant.

## Testmerges:
Likely been the same since #241 was made.

## Reproduction:
Deconstruct base internal walls from our renforced wall spawners. They'll drop renforced windows instead.

Likely the same for Nanocarbon windows, yet to test that though.

**Comment by Vasily2013** [comment]
pretty sure the sprites are now correct, but deconstructing the interior reinforced window only yields 1 sheet of Rglass instead of two.
