### ISSUE TITLE
Syndicate Radio Implant bugs normal headsets?

### ISSUE THREAD

**Issue by MessoDepresso** [BeeStation/NSV13#472]
Issue reported from  Round ID: 176 (NSV 13 | Official | MRP | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1507

Might have been round 175, the Report Issue wasn't working.

Got the implant and couldn't use my headset channels, even if I disabled the Syndicate Channel and the Speaker. Maybe there was a missing function button that's supposed to disable the implant? The description said it can be disabled to use a normal headset, but the only function was Activate, which opened it like a headset.
Was told to post here when I ahelped it.

**Comment by francinum** [comment]
telcom code is made of jank, Extends #253

**Comment by Vasily2013** [comment]
Verified in private instance of the code.

**Comment by francinum** [comment]
Likely fixed due to a recent update from upstream, Needs reverification.
