### ISSUE TITLE
Bridge Officer Weapons

### ISSUE THREAD

**Issue by RuneQuester** [BeeStation/NSV13#478]
Issue reported from  Round ID: 179 (NSV 13 | Official | MRP | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1517

So.as bridge officer,I cant ever seem to fire the weapons while I have a target lock on a syndie ship,except for the railgun. When Im using manuel aim,I can fire torps,PDC,and railgun,while I have a target lock,I can only use the railgun.

**Comment by Vasily2013** [comment]
KMC, please remember to remove stale tags when you prioritize something as high. <3

**Comment by Vasily2013** [comment]
Unable to replicate. Was this fixed @Kmc2000?
