### ISSUE TITLE
Ejecting can't be cancelled

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/NSV13#489]
[Round ID]: N/A, tested in localhost

## Reproduction:

1. Get in a viper and fly to the overmap

2. Hit eject.

3. Before you can eject, hit the button again to cancel the ejection process.

4. you eject anyway, ree

ejecting also seems to leave behind the craft you ejected from.

**Comment by Kmc2000** [comment]
I think we resolved this with DI

**Comment by Cenrus** [comment]
Can this be reopened? the issue is still prevalent
