### ISSUE TITLE
Starsystem Laziness punishments can't retrigger

### ISSUE THREAD

**Issue by francinum** [BeeStation/NSV13#490]
## Round ID:
Irrelevant

## Testmerges:
Irrelevant

## Reproduction:
`var/modifier` is never reduced/reset.

`/datum/controller/subsystem/starsystem` penalties such as reminder messages and financial penalties will never retrigger.

**Comment by Karmic-Skink** [comment]
var/modifier is reset by _overmap_event_handler currently.

**Comment by Karmic-Skink** [comment]
I'll move the reset to the combat check I guess.
