### ISSUE TITLE
Oculine's a PITA to make

### ISSUE THREAD

**Issue by Anonmare** [BeeStation/NSV13#494]
## Round ID:
Not relevant

## Testmerges:
Not relevant

## Reproduction:
Add charcoal
Add hydrodgen
Add carbon
Sometimes make oculine, sometimes make hydrocarbon - it depends on the planetary alignment

**Comment by francinum** [comment]
```
/datum/chemical_reaction/hydrocarbon
	name = "Hydrocarbon"
	id = /datum/reagent/hydrocarbon
	results = list(/datum/reagent/hydrocarbon = 5)
	required_reagents = list(/datum/reagent/hydrogen = 1, /datum/reagent/carbon = 1)
	required_temp = 333
```
Keep your mixture below 333 to prevent creating hydrocarbon.
