### ISSUE TITLE
Airlock painters break the texture of double airlocks and makes them look like a normal airlock.

### ISSUE THREAD

**Issue by ghost** [BeeStation/NSV13#499]
Issue reported from  Round ID: 195 (NSV 13 | Official | MRP | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1517

![grafik](https://user-images.githubusercontent.com/47011211/79078921-f793eb00-7d0b-11ea-95f3-97cc7fb778aa.png)

it still acts like a double door the other tile is invisible.

**Comment by francinum** [comment]
Double-wide airlocks are terrible and should be yeeted from every map. Change my mind.

**Comment by francinum** [comment]
These things suck in general

**Comment by Vasily2013** [comment]
I'm going to make sure we purge all of them and then close this.

**Comment by covertcorvid** [comment]
I believe we've yote the double airlocks from every active map
