### ISSUE TITLE
Fighters duping because of tugs + other issues

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/NSV13#500]
[Round ID]:195

## Testmerges:

#467: 'Adds AI zup and zdown sprites' by DrSirKnight at commit 09dda06f85
#465: '[Balance] SHIP FIGHTER, SHIP FIGHTER, WHERE WILL HE BOMB???' by Kmc2000 at commit ba8cd51884

## Reproduction:

Steps unknown, maybe spamming the load/unload fighter button?

Fighters duping when placed on tugs, occasionally fighters absolutely cannot be loaded on despite the tug being empty and close enough for loading.

The internal air canister can't be ejected either

![image](https://user-images.githubusercontent.com/31044876/79079588-fcef3680-7d07-11ea-8f6d-1e6210d1ecf5.png)

**Comment by ta3370** [comment]
Noticed the same "ghost-duping" fighter bug, discovered it to be 100% reliably replicate-able in thunderdome:
Load fighter on tug
Drive to the far west side, line it up so your tug's nose is in line with roughly the middle of the yellow-marked tiles
Launch fighter west
While it is still moving back towards you, load fighter again.

Actual fighter will teleport behind you, you will have a fighter sprite on you that sometimes phases under you, fighter on you does not _appear_ to exist properly and does not show up in tug UI.
Loading the real fighter fixes the error.

**Comment by francinum** [comment]
@Kmc2000 Is this still an issue?

**Comment by Kmc2000** [comment]
Resolved as far as I can tell!
