### ISSUE TITLE
Airlock painter wrong sprites

### ISSUE THREAD

**Issue by GoatMonarch** [BeeStation/NSV13#510]
## Round ID:
Every round

## Testmerges:
From the airlock resprite.

## Reproduction:
Using an airlock painter on causes it to become the old airlock sprites.

**Comment by Karmic-Skink** [comment]
Link #499

**Comment by Bokkiewokkie** [comment]
Also happens with the RCD

**Comment by francinum** [comment]
This is due to the magic that is KMC's airlock sprites. This is gonna be some messy code.

**Comment by Vasily2013** [comment]
Still an issue

**Comment by GoatMonarch** [comment]
Still an issue. Honk!

**Comment by francinum** [comment]
part of #558
