### ISSUE TITLE
[HAMMERHEAD] No APC in bridge

### ISSUE THREAD

**Issue by Corsaka** [BeeStation/NSV13#512]
## Round ID:
203

## Testmerges:
irrelevant

## Reproduction:
![image](https://user-images.githubusercontent.com/23699128/79382138-f99fb900-7f5a-11ea-829d-dbbf6e69d6a7.png)
fix

**Comment by Cenrus** [comment]
There's an APC, it's by the bridge doors.

**Comment by francinum** [comment]
Not a bug, This shares the area/APC with the primary bridge.
