### ISSUE TITLE
Map bounds now exceed DRADIS overlay

### ISSUE THREAD

**Issue by Karmic-Skink** [BeeStation/NSV13#534]
https://cdn.discordapp.com/attachments/602204840180842497/702163953354276965/unknown.png

Keep flying right etc to find problem.

**Comment by francinum** [comment]
Could likely be patchfixed by adding scaler math to the DRADIS display, but honestly the DRADIS needs to be reimplimented in a better form, as the current one isn't really great.

**Comment by Kmc2000** [comment]
I've done a bodge fix for now but dradis needs reworking urgently
