### ISSUE TITLE
Torps are completely broken and hit the main ship

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/NSV13#539]
## Testmerges:

#536: '[DNM](Testing only) Trying to fix slideshow mode' by Kmc2000 at commit 36acebcae4
#501: '[FIX] Full auto improvements' by Kmc2000 at commit ee2b5b5668
#519: 'Galactica Spacetrials' by MayhemSailor at commit 783cb09a85

## Reproduction:

1. make torp. load torp. launch torp.

2. explode as the torp hits the ship immediately.

**Comment by Cenrus** [comment]
Happened on the hammerhead and is likely because of the new hitboxes

**Comment by Kmc2000** [comment]
Fixed!
