### ISSUE TITLE
[Hammerhead] Chemistry access strangeness

### ISSUE THREAD

**Issue by Vivalas** [BeeStation/NSV13#540]
The chemistry windows on hammerhead are set up in a wonky way.

The door has required_one_access of 33, which is Chemistry. But the south window has ReqOne of medical and chemsitry, meaning doctors can open it and use it to go inside.

Meanwhile the east window just has req_access for 33 AND 5, meaning someone needs medical and chem access to open it.

Ideally both windows should just have req_one_access of 33.

Picture:
![image](https://user-images.githubusercontent.com/6334647/80287919-ee3a5380-86f9-11ea-9bb0-86af7abd4a32.png)

**Comment by francinum** [comment]
Please properly title your issues.
