### ISSUE TITLE
Kudzu can grow in blank areas on multi-z

### ISSUE THREAD

**Issue by covertcorvid** [BeeStation/NSV13#546]
## Reproduction:
![kudzu](https://user-images.githubusercontent.com/17987483/80333206-4cab2300-881b-11ea-91e6-5fc98923229c.png)

**Comment by francinum** [comment]
open_space should probably not be valid tiles for kudzu growth

**Comment by francinum** [comment]
🤷 Still an issue on latest.

**Comment by Vasily2013** [comment]
Unable to replicate
