### ISSUE TITLE
Distro Mapping Issues

### ISSUE THREAD

**Issue by MiniMeatwad** [BeeStation/NSV13#55]
## Round ID: 
10

## Reproduction:
![image](https://user-images.githubusercontent.com/22848292/65821331-de10d300-e201-11e9-9338-da761c390d81.png)
Empty node is to the right.
Gases come from atmos to the left.
![dreamseeker_7ofVGWqcUH](https://user-images.githubusercontent.com/22848292/65821336-e49f4a80-e201-11e9-9691-add754ca4943.png)

Caused by dual-port vents, likely related to issue #54
Someone used dual-port vents and assumed they're just a vent that lets gases through and can be used as an in between for air supply. This is wrong, however, and dual-port vents let in seperate gas mixes from two different pipes. There is also some scrubbers underneath vents which hides the scrubbers and looks odd. RD room gets cold and it's missing a pipe underneath the server room door.

**Comment by Kmc2000** [comment]
hnngnhghgh

that's really annoying

**Comment by Vasily2013** [comment]
DP Vent pumps are bugged and should not be used for any mapping purposes. Closing issue.
