### ISSUE TITLE
Galactica maint airlock wrong access reqs

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/NSV13#563]
![image](https://user-images.githubusercontent.com/31044876/80847928-52cd4500-8c09-11ea-9101-44daa2cf3767.png)

this airlock uses access type 25 when it should be defaultaccess.

**Comment by MayhemSailor** [comment]
[Map Issue Fixes for StarMap](https://github.com/Kmc2000/sephora/pull/9)

Issues fixed there
