### ISSUE TITLE
Vago - Turret control panel in the wall

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/NSV13#568]
![image](https://user-images.githubusercontent.com/31044876/80872277-d68a3e80-8ca8-11ea-9c67-1890433c8137.png)

Command maintenance, can access turret panel from outside the room.

**Comment by Vasily2013** [comment]
Wouldn't be much use if it were in the AI core.

**Comment by francinum** [comment]
The idea with the AI core panel is that only the AI can turn it off.

**Comment by Vasily2013** [comment]
That is specifically the upload turret control, which on all other maps is accessible from outside of upload. There is also a bug with the turret controllers that you can not access them unless you are on the turf that they are on.
