### ISSUE TITLE
Weapon overlay persistance

### ISSUE THREAD

**Issue by SgtxRootbeer** [BeeStation/NSV13#57]
basically, i stabbed myself with a fork and the ghost image of the fork stayed stuck on my character for a long while. this is possibly due to intense lag and poor hardware, but might also be indicitive of an underlying issue. feel free to close this report if it is simply the code running slowly.

**Comment by Kmc2000** [comment]
This sounds like an issue caused by the overlays subsystem breaking when we had 80 players on

**Comment by francinum** [comment]
MC level issue, Still an issue.

**Comment by Kmc2000** [comment]
This isn't something I can fix. It's more than the box can handle.
