### ISSUE TITLE
[Galactica] Hull plating inside a wall

### ISSUE THREAD

**Issue by Bokkiewokkie** [BeeStation/NSV13#571]
The leftmost wall of the command top deck maintenance bit next to the meeting room has hull plating  on the same tiles as the wall.
![image](https://user-images.githubusercontent.com/43698041/80912995-5663e780-8d41-11ea-89df-484aae8c21ea.png)

**Comment by francinum** [comment]
Hull plating code at the moment is super weird.

It should be turf but isn't.

**Comment by Bokkiewokkie** [comment]
Yeah it just kinda hides under the wall in-game right now, (this screenshot was from the webmap which does show it above the wall tiles) but that does mean that it can't be repaired without removing the wall because you have to weld it.

**Comment by MayhemSailor** [comment]
[Map Issue Fixes for StarMap](https://github.com/Kmc2000/sephora/pull/9)

Issues fixed there
