### ISSUE TITLE
Hephaestus Superthread

### ISSUE THREAD

**Issue by MayhemSailor** [BeeStation/NSV13#575]
Creating this thread for bug reporting on Hephaestus.

**Comment by Bobbanz1** [comment]
Comms don't work on one level

**Comment by Vasily2013** [comment]
Miners do not start with maint access.

**Comment by Cenrus** [comment]
Miners have no rewards vendor

**Comment by Cenrus** [comment]
Station Engineers cannot access Hephaestus engineering (intentional?)

**Comment by MayhemSailor** [comment]
@Cenrus access in the areas that were designed to be off limits to miners were changed to the new mining_engineer and mining_flight jobs. It will probably stay in a broken state until the new roles are actually added, or it goes back to being actual engineers and bridge staff.

**Comment by Bobbanz1** [comment]
Maintenance didn't have any gravity meaning the second one step into one they enter zero gravity

**Comment by MayhemSailor** [comment]
@Bobbanz1 Gravity issues have been resolved.

**Comment by MayhemSailor** [comment]
Anything above has been addressed here: https://github.com/Kmc2000/sephora/pull/15

**Comment by Bobbanz1** [comment]
Telecomms downstairs still don't work

**Comment by Bobbanz1** [comment]
Correction Telecomms above botany bay isn't linked to a hub meaning it c an't transmit nor recieve

**Comment by MayhemSailor** [comment]
I am no longer actively supporting Hephaestus. I don’t know who is taking over.
