### ISSUE TITLE
Starmap Superthread

### ISSUE THREAD

**Issue by Vasily2013** [BeeStation/NSV13#576]
Please place your bugs for the starmap PR here.

**Comment by Firefox13** [comment]
You can't see your current location on starmap, only in ship information.
We can add the location as small white arrow
![изображение](https://user-images.githubusercontent.com/57810301/81438954-43ed1200-9176-11ea-94c8-5fc3b074c36b.png)

**Comment by Firefox13** [comment]
Add ability to lock-on on anomalies. It's really fucking awful to target and shoot them.

**Comment by Abloobloo** [comment]
Allow fighters to fly into wormholes, it would be fuckin sick.

**Comment by Firefox13** [comment]
Piloting and jumping on under-staffed ship is hard. FTL spool is too slow and sometimes there's simply nobody to start it.

**Comment by Firefox13** [comment]
Ship should start at edge of safe systems. It's really boring sometimes.
