### ISSUE TITLE
Crashing into the main ship with docking mode on

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/NSV13#582]
## Reproduction:

1. Enter a Sabre and fly into the overmap.

2. Engage the docking console and fly into an allied ship.

3. You may crash into the hull of the ship and take integrity damage before being transferred to the ship Z level.

Normally this wouldn't be so much of a problem, but modules can now be destroyed if an overmap craft takes too much damage.

**Comment by francinum** [comment]
Needs verification on modern code.

**Comment by Vasily2013** [comment]
Haven't seen it in a while, consulting with other admins we haven't seen it, so assuming resolved.
