### ISSUE TITLE
Tugs can Load Fighter a magcatted fighter and cause the magcat to seemingly break

### ISSUE THREAD

**Issue by Robotonic** [BeeStation/NSV13#593]
## Round ID:
312 (and surrounding rounds before and after too, it's not specific to any one round.)

## Testmerges:
I didn't look at it at the time, sorry. But I know it had to have had #514 since I was a deck technician, and on-and-off I think there was also #501, #553, #574. 

## Reproduction:
Using a tug:
- Unload a fighter onto a magcat.
- Load the fighter off of the magcat, for example if you were swapping it out for another fighter.
- Unload any fighter - the same fighter or any other fighter - onto the same magcat and it will fail to latch because the previous fighter is still considered attached to the magcat already.
- _**Optional:**_ Proceed to launch 'still attached' fighter from ATC console.
- _**How to actually fix it in-game:**_ Just hit the release for the 'broken' magcat on the ATC console and you can load another fighter in.

This was very confusing since the ATC role isn't taken very often and even if it was they probably wouldn't have seen it. We resorted to just manually launching in the broken Galactica launchtubes by using the tug launch system.

If you're going to tackle this you might want to look at #488 as well.

**Comment by Kmc2000** [comment]
Resolved! as far as I can tell anyway.
