### ISSUE TITLE
Ship Exterior is part of area/maintenance and thus inherits immunity to radiation storms

### ISSUE THREAD

**Issue by Altangy** [BeeStation/NSV13#598]
## Reproduction: On hammerhead look directly outside the launch tubes

Space is also supposed to be fully irradiated during radiation storms with only maintenance being shielded. Any ship that uses /area/maintenance/ship_exterior for it's space area will inherit the immunity granted to the /area/maintenance/ path

![image](https://user-images.githubusercontent.com/25562238/81996331-b9475f80-961a-11ea-814f-8294964d2bed.png)
Picture for proof

**Comment by Karmic-Skink** [comment]
We can remove the ship exterior stuff now anyway.

**Comment by francinum** [comment]
there's a separate type of ship_exterior which does not have this issue, but serves the purpose of handling starlight dynamic lighting. The current stuff needs to be stripped and anything that requires starlight re-area'd.

**Comment by Kmc2000** [comment]
ship exterior can safely be yeeted

**Comment by francinum** [comment]
This was given the yeet recently.
