### ISSUE TITLE
Mjolnir fits in satchels

### ISSUE THREAD

**Issue by Firefox13** [BeeStation/NSV13#605]
![изображение](https://user-images.githubusercontent.com/57810301/82092359-cc812a80-9701-11ea-8000-ea959bc5c491.png)
Fairly too overpowered.

**Comment by francinum** [comment]
Should probably be looked at as part of #607

**Comment by Kmc2000** [comment]
There shouldn't even be any mjolnirs left after I nuked that balance nightmare

**Comment by francinum** [comment]
Then put `closes #605` in the body of that PR.
