### ISSUE TITLE
Constricted plasma issues

### ISSUE THREAD

**Issue by Vasily2013** [BeeStation/NSV13#611]
## Reproduction: Start game, do things

Constricted plasma does not do any of the following: 
- [x] show up on air alarms
- [x] have a gas sprite
- [x] deal toxic damage to humans
- [x] burn
- [ ] Have any special defining behaviors outside of running the storm drive and existing.

**Comment by francinum** [comment]
This is *absolutely* national debt, but not a bug.

Constricted plasma is old as, and the fact that it doesn't really *do* anything outside of having an absurd specific heat and fueling the engine is notable.
