### ISSUE TITLE
Cigars don't satisfy nicotine addiction

### ISSUE THREAD

**Issue by Koekiegast** [BeeStation/NSV13#613]
## Round ID:
362

## Testmerges:
Surviving edged weapons and the other one

**Comment by Karmic-Skink** [comment]
At a guess there were runtimes occurring due to server load and skipping parts of this cycle as it has done before.

**Comment by Koekiegast** [comment]
i've never had this problem with cigaretes though

**Comment by Karmic-Skink** [comment]
We have.

**Comment by francinum** [comment]
I'm gonna go ahead and blame timers. Cannot reproduce.
