### ISSUE TITLE
Some of the AI turrets do not have lethals

### ISSUE THREAD

**Issue by DrSirKnight** [BeeStation/NSV13#619]
Title

**Comment by francinum** [comment]
Which turrets specifically?

**Comment by DrSirKnight** [comment]
![410a35119f74c787846e4f66dcfccb17](https://user-images.githubusercontent.com/54851612/82915136-0e6b6580-9f79-11ea-86fa-e3a4071bdc87.png)
It was these turrets, but I am unable to do any testing in a private game because my byond is being fucky. It could potentially be that the turrets are connected to the wrong turret control
