### ISSUE TITLE
Bots don't have set pathways

### ISSUE THREAD

**Issue by Drobe50** [BeeStation/NSV13#62]
Issue reported from  Round ID: 11 (NSV 13)

Reporting client version: 512.1484

Bots that patrol like medibots or janibots don't have set pathways to patrol on and immediately disengage.

**Comment by francinum** [comment]
Bot beacons aren't mapped in.

**Comment by GoatMonarch** [comment]
I think additional z-level code is required to make it possible for robots to traverse multi z-levels before this becomes a high priority fix.

**Comment by francinum** [comment]
Even having them local to the Z-Level would work, the beacons physically aren't mapped in.
