### ISSUE TITLE
A torpedo can get stuck in a Trolley

### ISSUE THREAD

**Issue by TheFenix323** [BeeStation/NSV13#620]

**Comment by francinum** [comment]
Is this really the first time someone logged this on github? This is *ancient* debt.

**Comment by Vasily2013** [comment]
This is a high priority issue. This breaks the cart and makes it unusable until admins intervene. This is an administrative issue.

**Comment by Karmic-Skink** [comment]
Does server explode or is security breach? No. Not high priority.

**Comment by Vasily2013** [comment]
This is a high priority issue due to the fact that it takes up administrative resources.

**Comment by francinum** [comment]
Trolleys don't have a way to sanitize nulls or improperly removed items from their contents list.
