### ISSUE TITLE
JEPPISON MEGATHREAD

### ISSUE THREAD

**Issue by Corsaka** [BeeStation/NSV13#624]
do the bug things!

* Hangar door buttons don't work.

**Comment by ondrej008** [comment]
you can't fucking dock

**Comment by ondrej008** [comment]
the hangar only has 1 type of ammo (dunno if this is a bug)

**Comment by Corsaka** [comment]
> you can't fucking dock
this is because kmc didn't tell anyone that you needed a mag-cat to allow you to dock

**Comment by ondrej008** [comment]
> 
> 
> > you can't fucking dock
> 
> this is because kmc didn't tell anyone that you needed a mag-cat to allow you to dock

i mean launching out of a tug is pretty nice, i'm guessing you need a mag-cat so that it knows the z-level of the hangar? can't it be recoded to check for the hangar area instead?

**Comment by Corsaka** [comment]
there's meant to be a helper to notify it, it's hidden inside the mag-cat anyway but apparently kmc didn't want to go to the effort of doing that

**Comment by Corsaka** [comment]
https://github.com/BeeStation/NSV13/issues/608

**Comment by Return-To-Sender-Fender-Bender** [comment]
Arrivals shuttle south airlocks drop you into maintenance with no way back up. if you're unlucky you will fall into a completely walled off area with a friendly, immoveable, torpedo named Jorge.
