### ISSUE TITLE
Can build torp in hand (and also throw them)

### ISSUE THREAD

**Issue by Bokkiewokkie** [BeeStation/NSV13#643]
## Round ID:
Not relevant
## Testmerges:
Not relevant
## Reproduction:
Step 1: grab 15 metal
Step 2: make torp fram
Step 3: Congratulations! you now have a torp in your hand, feel free to put it in your backpack and never take it out again because it's too heavy to pick up.
Step 4 (optional): when the torp finishes building it will spawn it on the ground and remove it from your inventory.
Step 5: if you drag a torp onto a munitions trolley from your backpack you will have a permanent torp in the bottom of your screen where it would be in your backpack. now you can see exactly what state the torp is in at all time! and it never goes away!

**Comment by Firefox13** [comment]
You can drag your backpack on floor to dump all items out. Should do with torp, too.

**Comment by francinum** [comment]
This is honestly a buggy issue with the fact that in-progress torps are objects instead of what they should be, structures.

**Comment by francinum** [comment]
Verified on live as of 8/2/20

**Comment by francinum** [comment]
Why the fuck are these items...
