### ISSUE TITLE
shield perma from radiation, at least a little bit.

### ISSUE THREAD

**Issue by Vasily2013** [BeeStation/NSV13#650]
title

**Comment by francinum** [comment]
Sounds like security's job, really. Counts as 'Dangerous Environment'

**Comment by Corsaka** [comment]
Who's gonna do that? No security officer would risk having the perma prisoner escape, which yes, IS their problem, but it's also unfair to the perma prisoners, who are EVEN MORE out of the round than they were previously.

**Comment by francinum** [comment]
![](https://file.house/ERPT.png)

![](https://file.house/mR0z.png)
