### ISSUE TITLE
Ship Torps and Point defense refuse to fire.

### ISSUE THREAD

**Issue by MrNebbercracker** [BeeStation/NSV13#653]
## Round ID: 

431

## Testmerges:

I'm not sure if these have anything to do with the issue but I'm including them anyway

#572: '[ready] NSV Jeppison' by Vasily2013 at commit 13c42dd3aa
#607: 'NSV13: Surviving edged weapons' by Kmc2000 at commit fb2b14306d
#646: 'adds fun!' by Kmc2000 at commit 6c2334c2e2

## Reproduction:

Noticed this throughout the entire invasion event round on June 6th, clicking on the tactical console with torpedoes selected never actually fires them, and with point defense selected it only seems to fire roughly 60% of the time. locking on or having someone in munitions use the gauss turret also seems to lower the chance of point defense firing considerably. Railgun is the only weapon I found that shoots 100% reliably. This issue was, as far as I could tell, limited to point defense last time the server was up (weekend of may 30) but now it has spread to torpedoes it seems.

**Comment by francinum** [comment]
Seems to not be a problem anymore.
