### ISSUE TITLE
Anti-drop implant item can still drop when messing with teleporters

### ISSUE THREAD

**Issue by GoatMonarch** [BeeStation/NSV13#667]
## Round ID:
469 (I believe)

## Reproduction:
Clown had a teleportation gun combined with the drop implant. A sec officer tried to detain said clown. Some kind of stun were done, or prone. They fell over and slid into a portal, whence the portal gun were dropped. Sec officer picked it up, and still had the "glue" effect of not being able to drop it.

I genuinely have no idea what the issue is here, you'll most likely have to check logs what caused the clown to drop said portal gun.

**Comment by GoatMonarch** [comment]
Not experienced this for some time, but is probable to still be a possible bug that could happen.

**Comment by francinum** [comment]
Upstream bug, please report it there if it is still an issue on modern rounds.
