### ISSUE TITLE
can't zoom out on the overmap in pixel perfect 2x mode

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/NSV13#694]
1. Use the scroll wheel while viewing the overmap

2. Nothing happens.

**Comment by Corsaka** [comment]
Not a bug. You're forcing it to be pixel perfect 2x, so it won't become antialiased and smaller if you scroll.

**Comment by francinum** [comment]
Something's wrong with the auto-adjustment. It should be breaking you out of 2x when this happens.
