### ISSUE TITLE
Delinquent clown uniform's sprite randomly becomes the base clown sprite

### ISSUE THREAD

**Issue by GoatMonarch** [BeeStation/NSV13#699]
## Round ID:
494 (Was a-helped, Kmc read Kmc's text to see if anything changes in the meantime. Went from "it's a non issue" to "oh shid now it's borked for me too")

## Testmerges:
Been an issue for a while.

## Reproduction:
The clown uniform has some odd graphical error where it reverts to the vanilla clown uniform at random. For Kmc durring the round, I had the delinquent, at first, but then it became the vanilla one. For me it was the vanilla clown uniform since round start.
May be something wierd with the clothes pathing.

**Comment by GoatMonarch** [comment]
Seemingly, when this issue is not in place. You put on the formal clown attire from within your box, it uses the delinquent sprite instead. _I am having my doubt that it just works._

**Comment by francinum** [comment]
This issue's super old, if it's still a problem please create a new issue.
