### ISSUE TITLE
Medical Doctor jumpsuit

### ISSUE THREAD

**Issue by Firefox13** [BeeStation/NSV13#701]
All of medical currently is using old, sprited by someone bad, doctor jumpsuit. It looks gross, especially with new outfits from Beestation. We should remove those jumpsuits and use new jumpsuits from beestation.
~~they're so sexy just fucking look at them~~
![изображение](https://user-images.githubusercontent.com/57810301/86286659-8cadce00-bbef-11ea-82fa-409f8572372c.png)
![изображение](https://user-images.githubusercontent.com/57810301/86286664-8e779180-bbef-11ea-998d-68e44e77255f.png)
Original PR that introduced them:
https://github.com/BeeStation/BeeStation-Hornet/pull/1663

**Comment by francinum** [comment]
Updated from beestation, Acquired as a consequences.
