### ISSUE TITLE
Telekinesis from DNA scanner doesn't work.

### ISSUE THREAD

**Issue by Comxy** [BeeStation/NSV13#716]
When using the DNA scanner (Round: 509) I couldn't use my telekinesis when sitting in the DNA scanner. I also tested it with lockers afterwards, and it also failed with lockers when trying to use telekinesis.

I hope this can be fixed as soon as possible.

**Comment by francinum** [comment]
Upstream bug, please report it there if it is still an issue on modern rounds.
