### ISSUE TITLE
When tugs pick up fighters from a mag-cat, it will still be linked to the fighter.

### ISSUE THREAD

**Issue by ikalpo** [BeeStation/NSV13#720]
## Round ID:
Null

## Testmerges:
No

## Reproduction:
Put a fighter on a mag-cat, pick it up with a tug, and drop it somewhere else.
The mag-cat will still be linked to the fighter, and you can PM the pilot, and launch the fighter, even if it's in space already.

[video evidence](https://streamable.com/zmaw7l)

this is the same as #593

**Comment by francinum** [comment]
It seems to delink on launch, likely as it's being connected to the tug's internal magcat.

They should be delinking immediately and hooking to the internal magcat.

**Comment by Vasily2013** [comment]
We haven't had tickets about it, we're pretty sure it's fixed. Fighters aren't getting stuck any more.

**Comment by ikalpo** [comment]
@Vasily2013 [this has not been fixed](https://streamable.com/zmkmzk)
you misunderstand the issue, the fighters don't get stuck in place, they just are magically linked to the ship's magcat wherever they are, also preventing them from being placed on a new magcat.
