### ISSUE TITLE
Boarder ship TGUI is broke

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/NSV13#736]
## Reproduction:

1. Spawn them boarders

2. When you're in the ship, click the show control panel verb under the Ship tab.

3. It displays a tgui bluescreen error.

**Comment by francinum** [comment]
This prevents opening the canopy, preventing the pilot from exiting the raptor.

**Comment by francinum** [comment]
Continued issue. Needs addressing as it's detrimental to live rounds.

**Comment by Cenrus** [comment]
Only the lead of the boarding team spawns in the ship, everyone else in the team doesn't

**Comment by Vasily2013** [comment]
Issue has been resolved since launch.
