### ISSUE TITLE
[Jeppison] Gauss doesn't work

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/NSV13#739]
1. Enter gauss

2. Try to load and chamber the payload

UI seems to be out of reach, gauss machines may not be aligned with the chairs below.
![image](https://user-images.githubusercontent.com/31044876/87819052-89f3df80-c863-11ea-8312-5f6a03975375.png)

**Comment by francinum** [comment]
Map issue.

Gauss Gun has no power.
