### ISSUE TITLE
Aetherwhisp Megathread

### ISSUE THREAD

**Issue by Corsaka** [BeeStation/NSV13#742]
## Testmerges:
#738 

## Issues I've found:
* mag-cat console isn't linked
* heavy fighters aren't prebuilt
* supply shuttle is in the wrong place

**Comment by DrSirKnight** [comment]
The passive gates used at the reactor don't seem to work, they aren't letting any gas trough

**Comment by Corsaka** [comment]
![image](https://user-images.githubusercontent.com/23699128/88458862-dc975200-ce88-11ea-88e6-01e84413f7a4.png)
Telecomms doesn't have any more than one server

**Comment by Vivalas** [comment]
Munitions Techs start on the Roci

**Comment by Vasily2013** [comment]
all issues resolved
