### ISSUE TITLE
Objects with some null features are impossible to interact with.

### ISSUE THREAD

**Issue by Bobbanz1** [BeeStation/NSV13#755]
## Reproduction: All I did was try to rename a slice of meatbread but clicked cancel meaning it got renamed to nothing and I was unable to target it or pick it up. If I alt clicked the tile the bread would show up in the list as something that didn't have a name.
![bild](https://user-images.githubusercontent.com/59128051/88423245-c2f3fd00-cdeb-11ea-8063-d77d91edb3dd.png)

**Comment by francinum** [comment]
🤷

**Comment by francinum** [comment]
This includes but is not limited to:
Null names
Null icons
Empty icon_states.

**Comment by Vasily2013** [comment]
gonna throw upstream at this too.

**Comment by Bobbanz1** [comment]
@covertcorvid Don't know if this will help but I managed to reproduce the thing yet again and recoreded it in a video.


https://user-images.githubusercontent.com/59128051/209472184-787cf48a-a555-4eb5-8441-1ba5178aeebb.mp4

**Comment by covertcorvid** [comment]
Issue seems to be resolved on current master
