### ISSUE TITLE
After the ship engine explosion, fighter pilot docked back in null space

### ISSUE THREAD

**Issue by GoatMonarch** [BeeStation/NSV13#767]
## Round ID:
610

## Testmerges:
Happened on the whisp ship. Could be unrelated.

## Reproduction:
Byond key: ScientistMan 
IC name: Fukiro Nagashima
Went on a joy ride, when they returned to dock to the ship, they spawned into a completely empty area.

**Comment by Vasily2013** [comment]
Haven't had any tickets like this, so just gonna...
