### ISSUE TITLE
Mech Pilots for order are missing their sprites

### ISSUE THREAD

**Issue by challade** [BeeStation/NSV13#768]
Recently ordered the mech pilot suits from Cargo, red pilot suit, white pilot suit, blue pilot suit, all a reference to Neon Genesis: Evangelion.

When they arrived the sprites were an orange t-shirt with honk written above it, the placeholder for a missing sprite. When placed on your body you're naked and honk is floating above your torso. 

Please fix this so I can be the ultimate mech pilot.

**Comment by francinum** [comment]
Upstream issue, likely already patched, I'll see if this is the case.

**Comment by Jalleo** [comment]
Someone check if this still is a issue.
