### ISSUE TITLE
tactical console (and flight, I think) work even with no power and heavily damaged

### ISSUE THREAD

**Issue by ondrej008** [BeeStation/NSV13#779]
## Round ID:

all

## Testmerges:

doesn't matter

## Reproduction:

turn off APC, shoot the console a bunch, then click it and it works

**Comment by ondrej008** [comment]
nsv13/code/modules/overmap/components.dm
line 50, line 121

**Comment by francinum** [comment]
Most ship consoles, due to having their own interaction code, never actually pass checks.

This is some old ass kmree code.

**Comment by Vasily2013** [comment]
was fixed
