### ISSUE TITLE
Non anchored windows and fake walls are invisible

### ISSUE THREAD

**Issue by DrSirKnight** [BeeStation/NSV13#784]
Fake walls are only invisible when closed

## Reproduction:
Windows:
1. Use glass in hand to make a window
2. See that it's invisible
Fake walls:
1. Place metal on unanchored grider
2. See that it is invisible when closed

**Comment by Corsaka** [comment]
The code for this is weird. The icon is inherited from the parent's parent for the non-anchored window, which might be the cause of why, but setting the icon for either anchored or unanchored doesn't fix the problem.

Falsewalls have their icons declared immediately, so they also shouldn't have a problem.

It should be noted that using `View-Variables` on either of these will cause a runtime, stating `bad resource file`.

**Comment by francinum** [comment]
This issue is related to them not having a base icon, it's completely constructed for them in smoothing.

**Comment by Vasily2013** [comment]
Update, if you alt+click on the tile and then open the wall it updates the sprite and works properly both closed and open.

**Comment by Vasily2013** [comment]
This is still an issue, specifically on initilization.
