### ISSUE TITLE
[Tycoon] Gauss stunlocking people without ear protection

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/NSV13#785]
I've seen people without ear protection repairing the hull get stunlocked by the loud gauss turrets nearby

**Comment by Corsaka** [comment]
And since sound shouldn't travel in space... This is gonna be a bitch to code. My condolences to whoever does.

**Comment by francinum** [comment]
Yep, this should probably be a hearing check.

**Comment by Vasily2013** [comment]
I believe this means "railguns" and they are no longer used.
