### ISSUE TITLE
Clown uniform sprites not working: The sequel

### ISSUE THREAD

**Issue by GoatMonarch** [BeeStation/NSV13#792]
## Round ID:
494 (Was a-helped, Kmc read Kmc's text to see if anything changes in the meantime. Went from "it's a non issue" to "oh shid now it's borked for me too")

## Testmerges:
Been an issue for a while.

## Reproduction:
The clown uniform has some odd graphical error where it reverts to the vanilla clown uniform at random. For Kmc durring the round, I had the delinquent, at first, but then it became the vanilla one. For me it was the vanilla clown uniform since round start.
May be something wierd with the clothes pathing.

Seemingly, when this issue is not in place. You put on the formal clown attire from within your box, it uses the delinquent sprite instead. _I am having my doubt that it just works._

**Comment by francinum** [comment]
Has this been reverified on a recent round, if so, what ID?

**Comment by GoatMonarch** [comment]
> Has this been reverified on a recent round, if so, what ID?

It reoccurs ever single round. Either it's the jojo uniform, or normal uniform that is the wrong sprite.
From what I understood with the dialogue betwen me and Kmc from round 494 is that the ingame sprite isn't wrong right away, but later gets updated to the wrong one. 
My experience as the clown is the on wear sprite is always incorrect betwen one of the two, never had a round where both the jojo uniform, and normal clown uniform actually display the right sprite as you wear them.

It's easy to test, just spawn yourself in on CC check that the Jojo uniform looks as it should, then put on the formal clown uniform from the box clowns starts with.

**Comment by francinum** [comment]
Issue confirmed Round 941.

`nsv13/code/modules/clothing/custom_clothes.dm#L419`

https://file.house/wa_q.png

**Comment by francinum** [comment]
The icon state likely needs to be modified, This should be a simple task.
