### ISSUE TITLE
Ethereals borked

### ISSUE THREAD

**Issue by Vivalas** [BeeStation/NSV13#793]
Throwing up here for reference.

34d2ffd0156ec7e52e7a23de38dac5d479d2c0e6 badly broke a bunch of things, ethereals one of them. Fixing it is going to be more complicated than just a few online changes, so it needs to be looked at in more detail by someone.

Basically, there are two variables for ethereal charge now. crystal_charge, which is stored on the stomach organ and used to determine the health status of the ethereal based on how much charge they have. there is no way to increase this, at all, without admin intervention because it is not at all referenced anywhere else

and the other variable is ethereal_charge, which is the old variable that was used. it seems like it was half-refactored, and now both instances are lying around. crystal_charge is used to determine if you die from running out of charge, but doesn't actually ever go up from recharging, because all of the recharge methods use ethereal_charge still. just a huge clusterfuck really

**Comment by francinum** [comment]
Patched in an upstream pull.
