### ISSUE TITLE
Bad icon_state icon combination: Monogrid tiles.

### ISSUE THREAD

**Issue by francinum** [BeeStation/NSV13#820]
## Round ID:
766

## Testmerges:
#814: 'Autofire that isn't objectively terrible. We truly live in a society.' by Kmc2000 at commit a9beb05543
#818: 'Okay but what if you could just build constrictors and they'd connect to pipes' by Bokkiewokkie at commit a6aaf4ef4d
#819: 'NSV Pegasus - The battleship' by Kmc2000 at commit 3d2e7b9bfb

## Reproduction:
Spawn a room of `/turf/open/floor/plasteel/grid/mono`

Set it on fire.

### Reason
(E) (C) (M) icon = /icon (nsv13/icons/turf/floors.dmi)

icon_state = "floorscorched1"
icon_state = "floorscorched2"
burnt_state list contains invalid iconstates.
```
(E) (C) (M) burnt_states = /list (2)
1 = "floorscorched1"
2 = "floorscorched2"
```

**Comment by Bokkiewokkie** [comment]
I'll fix this and also add some actual icon states for the damaged/burnt nsv tiles that don't have em yet
