### ISSUE TITLE
DRADIS access not checked

### ISSUE THREAD

**Issue by extramrdo** [BeeStation/NSV13#822]
Issue reported from  Round ID: 769 (NSV 13 | Official | MRP | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1528
Round 769, on the Aetherwhisp.

error: Clicking on Mining DRADIS. Get "access denied" in chat, but a DRADIS window pops up anyways, with appropriate blips.

**Comment by francinum** [comment]
Our computers override the access check...

@Kmc2000 This is an ancient one...
