### ISSUE TITLE
TAC Tactical Systems Control Console activating window but not view

### ISSUE THREAD

**Issue by AU518987077** [BeeStation/NSV13#826]
Issue reported from  Round ID: 810 (NSV 13 | Official | MRP | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1528

multiple times i was unable to re-enter TAC console as AI, after have interfaced just seconds before to open a  door or locate a crewmember or look for boarders.

i will try and replicate this issue on my server and provide reproduction steps in an edit.

but the jist of it was, enter console, leave console, enter console, not see view change but have TAC window populate,

i ahelped twice, don't know if the admins did anything
 but i did try reconnect, and closing the TAC widow and closing all windows i had opened. and eventually i was able to get back in eventually,
 tried battle-bridge and main bridge consoles neither changed views

This is the only screenshot i took, with this issue however this was the only time wehre the human level view was zoomed out, 
![Screenshot 2020-08-17 16 19 47](https://user-images.githubusercontent.com/24924661/90454929-d07e6900-e0b1-11ea-8bb4-ddca63049f3e.png)

**Comment by AU518987077** [comment]
have yet to reproduce on my own servers, might need to spend some timeon the live servers to try and reproduce this if i cant on my own server

**Comment by francinum** [comment]
Note that the full AI, as in, *outside of a shell*, *using the cameranet to see*, **SHOULD NEVER BE ABLE TO USE THE HELM OR TAC CONSOLES.**

This is due to a low-level conflict with the way the system works.
