### ISSUE TITLE
Atmospherics Updates and Oversights

### ISSUE THREAD

**Issue by Vasily2013** [BeeStation/NSV13#836]
- [x] The atmos being in space is kind of weird, since it's all enclosed anyway and feels like it should be inside especially from the glass.
- [x] There is no roundstart gas going into distro, so if there are no atmos everyone dies.
- [x] The pipes to fuel the turbines start on making it hard to make tritium since the input is good for burn rather than tritium and should start off instead
- [ ] The pipes feel cramped together, but there is a lot of empty space that could be used to make the pipes feel more spread out
- [ ] No spawns for atmos techs

**Comment by DrSirKnight** [comment]
There are no cameras in atmospherics

**Comment by Bokkiewokkie** [comment]
Issues pretty much fixed in #1170 I think
