### ISSUE TITLE
Morphine is impossible to make

### ISSUE THREAD

**Issue by izeot** [BeeStation/NSV13#843]
Issue reported from  Round ID: 835 (NSV 13 | Official | MRP | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1527

Morphine's recipe is 
2 parts Carbon
2 parts Hydrogen
1 part Ethanol
1 part Oxygen
Tempurature 480k

hydrocarbons recipe is
1 part Hydrogen
1 part Carbon
temperature 333 K

you cannot make morphine without it making hydrocarbons 1st. This is a massive problem and has ruined my dreams of a krokodil factory. please fix

**Comment by francinum** [comment]
Higher temperature reactions override lower temperature reactions.
Preheat your reactants and you won't have this issue.
