### ISSUE TITLE
Overmap viewing went fucky

### ISSUE THREAD

**Issue by covertcorvid** [BeeStation/NSV13#848]
## Round ID:
847

## Reproduction:
Towards the end of the round, I tried looking at a viewscreen. It crashed my client, and when I reloaded, the view was still on my mob and jerking back and forth and intercepting movement until I exited the "camera". One of the officers was also having trouble firing overmap weapons due to some kind of glitch.
Anyways I can't actually view logs, but it'd be good if someone dug those up and figured out what happened.

**Comment by Grabovvski** [comment]
Happened to me and my bridge staff as well on round 857.
