### ISSUE TITLE
Squad Comms work during comms outage

### ISSUE THREAD

**Issue by Grabovvski** [BeeStation/NSV13#850]
## Round ID:
Multiple rounds

## Testmerges:
I dont know, sorry

## Reproduction:
Turn off Tcomms. Altough I dont know if the reason it turns off (eg. Ion anomaly or simply turning off the APC) matters

**Comment by Bokkiewokkie** [comment]
pretty sure this is intended as squad comms are (as far as I can tell) more like pagers which wouldn't need a special telecomms signal but instead act more like radios (unrelated note: telecomms should not exist)

**Comment by francinum** [comment]
They are *completely* divorced from standard radio code. They won't shut down when telecom is tampered with and they aren't meant to.
