### ISSUE TITLE
SSCrit is too static and will result in unintended effects on incorrect ship instances

### ISSUE THREAD

**Issue by Karmic-Skink** [BeeStation/NSV13#870]
Ship go boom.

**Comment by francinum** [comment]
Static is the correct word here, as the system was likely not designed with the dynamic systems in mind, it assumes that the statically mapped "Main" ship is the only one with a concept of SSCrit.

**Comment by Vasily2013** [comment]
We're pretty sure this is still happening.

**Comment by Jalleo** [comment]
Likely fixed. Closing unless someone can provide evidence of how it still occurs.
