### ISSUE TITLE
Spelling Inconsistency: Armo(u)r

### ISSUE THREAD

**Issue by francinum** [BeeStation/NSV13#873]
The majority of the codebase uses the american `Armor` spelling, while our systems use the UK `Armour` spelling.

This should be standardized for consistency with upstream on the `Armor` spelling.

**Comment by Vasily2013** [comment]
I'm just gonna remove stale and say that this will probably be an issue until we move one half of our development team to the opposite side of the Atlantic from where they currently are.

**Comment by theboy6545** [comment]
Bring them to the UK so i can talk to them at normal daylight hours.

**Comment by covertcorvid** [comment]
These have actually come to symbolize the two separate damage reduction systems. I think it's fine.
