### ISSUE TITLE
Fighter pilots are unable to dock

### ISSUE THREAD

**Issue by DrSirKnight** [BeeStation/NSV13#881]
## Testmerges:

#853 #828 #857 #856 #862 #877 

## Reproduction:
I wasn't the person affected by the bug, a person in a mentorhelp explained how it happened and I made the issue for him.
He was flying a fighter on the overmap and when going in to dock he had docking mode enabled but it wouldn't let him dock, he just went trough the ship.

**Comment by Vasily2013** [comment]
Not reported since launch. Likely no longer an issue.
