### ISSUE TITLE
Ghosts can change the reasearch focus on the astrometrics computer

### ISSUE THREAD

**Issue by DomKot** [BeeStation/NSV13#884]
Issue reported from  Round ID: 969 (NSV 13 | Official | MRP | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1526
Im unsure if I did something weird previously that caused this bug

**Comment by francinum** [comment]
@Kmc2000 This is once again related to the interaction for ship-type computers being completely overridden.

**Comment by Vasily2013** [comment]
Still an issue.
