### ISSUE TITLE
Lack of nuclear waste spawners - Jeppison

### ISSUE THREAD

**Issue by Karmic-Skink** [BeeStation/NSV13#907]
This map is missing nuclear waste spawners that are universally used for both the Stormdrive and Nuclear Reactor.

Type paths are as follows:
/obj/effect/landmark/nuclear_waste_spawner
/obj/effect/landmark/nuclear_waste_spawner/strong

Please place these sporadically around the map, and make use of the strong spawners near engineering.

Example provided:
![image](https://user-images.githubusercontent.com/45891563/94391958-142abf00-0196-11eb-9e5b-c4ca5ab5a944.png)

**Comment by theboy6545** [comment]
Apparently these were removed intentionally, not on error.

**Comment by Vasily2013** [comment]
These were removed intentionally in PR #805 specifically citing the irrecoverable nature of a core failure with those spawners in place. They remained on the Whisp due to the Whisp having an abundance of anti-radiation equipment, and thus being able to cope with a reactor failure-state.

**Comment by Karmic-Skink** [comment]
They are required for #908 as meltdowns have been reworked.
