### ISSUE TITLE
overmap overlays are STILL broken

### ISSUE THREAD

**Issue by ikalpo** [BeeStation/NSV13#927]
## Round ID:
NULL

## Testmerges:
no

## Reproduction:
pilot the main ship
hold W and spin the mouse around in front of the ship
there are now 10'000 nulls in the list "overlays" in the ship's vars
keep doing this and you will lag your client so bad you will lose connection to the server
now anyone who views the ship will get bad lag, and may also lose connection
this is a problem on AI ships too, but it mostly just has the effect of making their RCS "stick" since they aren't as active as the player ship

**Comment by Jalleo** [comment]
Reported as fixed. Report again if it isnt fixed.
