### ISSUE TITLE
Fixing Atmosia

### ISSUE THREAD

**Issue by SirRailOfGun** [BeeStation/NSV13#93]
this should help fix atmosia. Do not forget to fix the airlocks, as they still use Engineering access, not Atmos

![Atmos fix, minor changes](https://user-images.githubusercontent.com/26176840/66708078-18599480-ed19-11e9-844a-ae8da949219b.png)

**Comment by Corsaka** [comment]
Adding to this - the bottom part of the waste loop is an output, meaning there's no input to the waste loop anywhere.

**Comment by Corsaka** [comment]
The Lexica Atmosia is a 404 page.

**Comment by Corsaka** [comment]
![image](https://user-images.githubusercontent.com/23699128/67633862-2aa50800-f8ad-11e9-9a25-648922d128e5.png)
At the bottom here is a waste in - don't forget it.
