### ISSUE TITLE
KNOWN ISSUE: Cargo Shuttle's Shutters refusing to open.

### ISSUE THREAD

**Issue by Bobbanz1** [BeeStation/NSV13#947]
## Note: This has been reported to the admins over and over again, and usually the shutters just get's replaced with atmos blockers as a temporary patch. This has happened every single round from a certain point.

**Comment by Bobbanz1** [comment]
## Additional Note:
Top shutters seem to work most of the time however they sometimes fail aswell

**Comment by QAI-07** [comment]
Also worth noting is, when opened. The door shutter button has no electronics in it, which is why it doesn't function, the only thing that needs to be found is when and where and why the electronics go missing.

**Comment by Bobbanz1** [comment]
Could be that they get sold somehow which doesn't make sense as the other shutter button works just fine
