### ISSUE TITLE
Asteroids got some fuckywucky generation now

### ISSUE THREAD

**Issue by GoatMonarch** [BeeStation/NSV13#949]
## Round ID:
Chasm issue example: ID 1039

## Testmerges:
Has come to be an issue after our server returned.
Ore generation may be due to my new ruins using the wrong rock type, but I doubt it.

## Issues:
Ore generation seems to only happen by the mineral rich core. I only experienced this on one of my ruins, but suspect that it's a general problem.
Chasms appeared on round ID 1039, acording to Altangy our seniormin.

A wishlist as a mapper is for us to have the ability to place down a marker for where the central ores spawn. And make it optional for more unique ruins.

**Comment by Corsaka** [comment]
Believe this was reverified recently.

**Comment by covertcorvid** [comment]
I believe chasms are gone.
