### ISSUE TITLE
Chat client error, forcibly reloaded the chat three times in total.

### ISSUE THREAD

**Issue by Xoxeyos** [BeeStation/NSV13#958]
Issue reported from  Round ID: 1060 (NSV 13 | Official | MRP | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1536

https://imgur.com/a/8Ry2Xo6

I am running windows ten, however I am unaware of the current update I am on, probably the most recent. I don't use internet explorer.

**Comment by QAI-07** [comment]
This has been a fairly unpredictable issue, but the best way we've found of fixing is to either switch between dark and light mode or simply just reconnecting to the server.
