### ISSUE TITLE
Issue with boarder as pilot

### ISSUE THREAD

**Issue by RaiIsNotYourGuy** [BeeStation/NSV13#961]
Issue reported from  Round ID: 1063 (NSV 13 | Official | MRP | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1532

Spawning as a boarder, I was placed into the pilot's spot on a sabre. I couldn't get out due to the canopy being closed. I couldn't open the canopy due to the ship spawning without a battery. I adhelp'd to get unstuck.

**Comment by francinum** [comment]
@Kmc2000 The canopy should probably have a release if the ship's battery is completely fucked.
