### ISSUE TITLE
Felinds ear go ow even with bowmans

### ISSUE THREAD

**Issue by Autisem** [BeeStation/NSV13#964]

**Comment by Autisem** [comment]
I went code diving, and felinds gain no buff from there mores sensitive ears(some one ingame claimed just checked it). Maby we should increase there ban_protect at last? It makes sec slightly anoying and munations close to impossible unless you ONLY opertate gause guns

**Comment by Bobbanz1** [comment]
According to Francium back when I made a report on this it's supposed to be Intentional or in his own wording.
![bild](https://user-images.githubusercontent.com/59128051/96673591-20ee9d00-1367-11eb-9c17-e713f6404c2a.png)

**Comment by Autisem** [comment]
Iam working on fix myself, PR coming soon

**Comment by MacBlaze1** [comment]
This is a snowflake complaint that should be closed for not being a bug or oversight

**Comment by Jalleo** [comment]
Closed now. This is intended.
