### ISSUE TITLE
Respawning Issue

### ISSUE THREAD

**Issue by jdeuce22** [BeeStation/NSV13#969]
in NSV you will die. sometimes you'll die and be unable to be revived! so what did the other server devs do? they added SPAWNERS, ways to get back in the game as something/someone new, usually they have 0 influence on the station (in this case ship) itself! and let's say that people get in-game, suicide or observe quickly to get in as a spawner, why don't we remove suiciding, but only allow admins to observe! but still, we need spawners, let's say the ship gets attacked and a lot of people die and cloning is destroyed, how do they get back in the game? right now, they wait till the next round, but I think there should be spawners or a mini-game for people who died and which to do something while they wait for the next round! I hope spawners get added, but to help here's a few ideas!
1. Lost pilot: basically you get spawned in a fighter or small ship and have to fly around trying to survive this has good roleplay do to the chances of accidentally running into the ship
2. broken station: basically, survivors and a broken station.. do I need to go on?
3.syndicate fighter: this, THIS could be a good one, so basically a small fighter gets spawned on the same area as the ship (let's say it can only be done in neutral or syndicate zones and can only be used during a fight!)  and the fighter is controlled by the ghosted player, THEY ARE NOT ARMED WELL, at most they have a small pistol or something weak, possibly a mere dagger, discouraging boarding, but they can dock to carriers, which should at most refill health, ammo, armour, and fuel after a mere delay.
4. NT fighter. same as syndicate fighter but they are extremely weak and completely unarmed, and sure, let's say that the fighters self destruct upon docking with the main ship (NSV)
5. this one could be an event that happens with every battle, but a random ship that is NOT SPECIAL, is chosen to have a player crew, there are fighters, which will however self destruct upon docking with NSV.
I hope this helps! sorry if it's clunky!

**Comment by francinum** [comment]
`why don't we remove suiciding and observing, but let admins do it`
...What?

**Comment by jdeuce22** [comment]
I meant, remove suiciding, but allow only admins to observe

**Comment by jdeuce22** [comment]
so, uh, how difficult would it be to add the ability to respawn other than random events?

**Comment by Bokkiewokkie** [comment]
As far as I'm aware there has been talk about ghostrole spawners but the main reason they're not here yet is simply because they haven't been created. I like the idea of giving ghosts control of the weaker overmap ships though.

**Comment by jdeuce22** [comment]
thanks, but yeah ghosts controlling weak overmap ships I totally support, do think that there'd need to be a way for the ghost controlled syndie ship to prepare before combat.. maybe make them be in a jump for a while?

**Comment by Bokkiewokkie** [comment]
> thanks, but yeah ghosts controlling weak overmap ships I totally support, do think that there'd need to be a way for the ghost controlled syndie ship to prepare before combat.. maybe make them be in a jump for a while?
I think just let people have a chance to gain control of the carrier-spawned syndicate interceptors (and maybe bombers), they're very weak so they (hopefully) can't be used to completely stop the main ship but can still make for a fun time when assisting the carriers etc.

**Comment by jdeuce22** [comment]
good idea, would need to give them a way to re-arm re-supply and re-pair, dock with carriers?

**Comment by francinum** [comment]
haha like we have the spare processing capacity to do that.

Rearm like the AI by standing near carriers.


I really, **REALLY** dislike the idea of restricting the ability for players to observe.

If we do restrict it, congratulations they aren't going to observe.

They're going to go assistant and suicide.
