### ISSUE TITLE
Fighter dying

### ISSUE THREAD

**Issue by AlucardHellsingChapel** [BeeStation/NSV13#975]
Issue reported from  Round ID: 1107 (NSV 13 | Official | MRP | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1536
So i started fighter got out into space left ship i had 100%  hull 0%  armor cuz there was none to replace  it i left main ship and exploded that shit makes no sense and is annoying you can even sometimes die with 50%  hull. One  shift i had 100%  hull 100% armor in hangar and ship just exploded why no clue but thats annoying

**Comment by francinum** [comment]
Fighters seem to be having issues related to damage in gravity areas, This is also not helped by #407, causing any death from these issues to be permanent and irrevocable, @Kmc2000?
