### ISSUE TITLE
Pegasus Issue Superthread

### ISSUE THREAD

**Issue by Vasily2013** [BeeStation/NSV13#982]
All the reasons it should have never been merged in the first place... not enough QC testing.

- [ ] No NTNet relay
- [ ] Space tiles over sealed areas
- [ ] HOS shutters do not work
- [ ] Reconfigure some of munitions to retrieve ammo
- [ ] Gauss gun rounds get lost on unload
- [ ] Fake elevators
- [ ] Stairwells should be two tiles long whenever possible
- [ ] AI upload has minimal protection
- [ ] NE corner of ship uncovered.
- [ ] Mining dock uncovered
- [ ] Chapel uncovered

**Comment by theboy6545** [comment]
You can tick off the munitions one, I have fixed it.

**Comment by francinum** [comment]
@theboy6545 PR ID?

**Comment by francinum** [comment]
The hallway outside arrivals contains an infinite disposals loop.
https://file.house/Ezo6.png

**Comment by Kmc2000** [comment]
Reinforced bits in maint should be turned into openspace.
