### ISSUE TITLE
[Hammerhead] Issue HoS office & Execution Room

### ISSUE THREAD

**Issue by Googles-Hands** [BeeStation/NSV13#991]
## Reproduction:

The HoS office and the Execution room are only accessible by walking through an section that is exposed to space, thereby using the office vents both it and the brig, this is an rather large oversight and makes both the office and execution room unusable

**Comment by theboy6545** [comment]
Not an issue, designed this way.

**Comment by Bokkiewokkie** [comment]
it's intended and also educates people about the importance of firelocks (don't be so impatient)
