### ISSUE TITLE
Docking: Exploding After One Minute

### ISSUE THREAD

**Issue by Sgtwok** [BeeStation/NSV13#996]
## Round ID: 1139

 1139

## Reproduction:

 I do not know what caused it exactly however I will explain what happened: in the middle of a fighter sortie, I found myself heavily damaged, to somewhere inbetween 7-13% hull, on the way to the ship I took a hit and my durability was at 20%, which was odd, but I made my way back to the mothership, I successfully docked, and waited a minute for the Traffic Controller to let me in, while waiting, and, again, after a minute, my fighter exploded, and with it, myself, which was a bit odd, and frankly, a little unfair and left the Traffic controller scratching his head just what had happened when I mentioned that i've docked successfully.

**Comment by Kmc2000** [comment]
I've seen this a fair bit, for some reason fighters just gain health magically and then enter crit. I think it's to do with ancient "ship disable" code

**Comment by Sgtwok** [comment]
Isn't there an eject function? Could that be causing issue?
